### ISSUE TITLE
> We need to implement the basic ChugSplash executor service. Blocked by getting the rest of the contract changes through.

### ISSUE THREAD

**Issue by cklim483** [actions/cache#1037]
> We need to implement the basic ChugSplash executor service. Blocked by getting the rest of the contract changes through.

_最初由 cklim483 在 https://github.com/chugsplash/chugsplash/issues/36#issuecomment-1363395678 发布_

**Comment by tanuj077** [comment]
Hi,

It is not very clear to me as to what is the expectation here, can I have some more details please that might help me get a better grasp of the ask.

**Comment by tanuj077** [comment]
Closing the issue as stale/invalid.
