### ISSUE TITLE
Unable to restore symlinks from cache on Windows

### ISSUE THREAD

**Issue by jonkoops** [actions/cache#1043]
We noticed that since version 3.2.1 of `actions/cache` that our CI jobs have started failing. This seems to be caused by the inability to restore symbolic links, resulting in the following output in our [failing job](https://github.com/Leaflet/Leaflet/actions/runs/3765137242/jobs/6400318277):

```log
/usr/bin/tar: node_modules/.bin/acorn: Cannot create symlink to '../acorn/bin/acorn': No such file or directory
/usr/bin/tar: node_modules/.bin/pidtree: Cannot create symlink to '../pidtree/bin/pidtree.js': No such file or directory
/usr/bin/tar: Exiting with failure status due to previous errors
Warning: Failed to restore: "C:\Program failed with error: The process 'C:\Program Files\Git\usr\bin\tar.exe' failed with exit code 2
```

Reverting back to version 3.2.0 seems to resolve the issue, allowing the CI to [pass again](https://github.com/Leaflet/Leaflet/pull/8742).

**Comment by Phantsure** [comment]
@jonkoops It looks like you are not using npm cache like suggested here: https://github.com/actions/cache/blob/main/examples.md#node---npm and your keys are not OS specific. You may use any of those to keep using latest v3 for now. 
We are looking into this specific issue. Reason for this issue is, on windows, cache restore step is restoring cache saved on linux/mac runners and symlinks don't work due to path differences in windows and *-unix like systems.

**Comment by danyeaw** [comment]
We ran in to a similar problem here: https://github.com/gaphor/gaphor/pull/1950

```
Run actions/cache/restore@v3.2.1
  with:
    path: C:\gtk-build\gtk\x64\release\**
    key: gvsbuild-2-2022.6.0
Received 107917093 of 107917093 (100.0%), 122.4 MBs/sec
Cache Size: ~103 MB (107917093 B)
"C:\Program Files\Git\usr\bin\tar.exe" -xf D:/a/_temp/c81337b8-6bf0-43b0-a4ff-d4826b0628e0/cache.tzst -P -C D:/a/gaphor/gaphor --force-local --use-compress-program "zstd -d"
/usr/bin/tar: C\:/gtk-build/gtk/x64/release/etc/fonts/conf.d/10-hinting-slight.conf: Cannot create symlink to '/c/gtk-build/gtk/x64/release/share/fontconfig/conf.avail/10-hinting-slight.conf': No such file or directory
```

Is there a way to disable this cross-os caching? This cache step is specific to a library being built on Windows.

**Comment by jonkoops** [comment]
@Phantsure we're not just caching the `node_modules` directory, but also other things like our `dist` directory (actually the entire workspace). However that is beside the point as this is a breaking change either way.

**Comment by jonkoops** [comment]
@Phantsure Yeah, looks like adding the OS to the cache key fixes this issue. This does however still seem like a breaking change that was introduced in a patch version.

**Comment by bishal-pdMSFT** [comment]
Version `3.2.1` has been reverted and this issues should be gone now. We are evaluating options on how to fix issue of symbolic links across OS.

**Comment by jonkoops** [comment]
Thanks, that's very much appreciated!

**Comment by Phantsure** [comment]
New changes have been released with symlink fix. https://github.com/actions/cache/issues/984#issuecomment-1372052193
Closing this issue for now. If you feel it is persistent then you may reopen.
