### ISSUE TITLE
Restoring from cache enters some kind of infinite loop

### ISSUE THREAD

**Issue by vmarkovtsev** [actions/cache#1048]
One of my jobs started to spin forever on `actions/cache@v3`. Example: https://github.com/athenianco/athenian-api/actions/runs/3782604122/jobs/6430475872

It prints the same message every second:
```
Received 2079511432 of 2083705736 (99.8%), 1.8 MBs/sec
```

Canceling the workflow and retrying the job helps.

In case this is a networking issue, how about putting a reasonable socket timeout?

**Comment by kotewar** [comment]
Hey @vmarkovtsev, this is something that we have seen occurring intermittently and we are working on fixing this. 
As of now, we have introduced a timeout (in minutes) that can be manually passed as environment variable `SEGMENT_DOWNLOAD_TIMEOUT_MINS` to `actions/cache@v3`. More info [here](https://github.com/actions/cache#environment-variables).

Do let us know if you have any further questions.

**Comment by vmarkovtsev** [comment]
Thanks a lot, this envvar should alleviate the problem for me.

**Comment by kotewar** [comment]
You are welcome!

Closing this as resolved. Please feel free to reopen/ comment for any help needed.
