### ISSUE TITLE
Missing releases?

### ISSUE THREAD

**Issue by daveisfera** [actions/cache#1050]
`npm-install` [updated to 3.1.1](https://github.com/bahmutov/npm-install/releases/tag/v1.8.27) but I don't see a release for that, so is it missing?

**Comment by kotewar** [comment]
NPM [package](https://www.npmjs.com/package/@actions/cache) for `action/cache` comes from the [toolkit](https://github.com/actions/toolkit/tree/main/packages/cache) repository.
This repository action uses the npm library that's published from the toolkit repository hence the action releases and the library releases will not have same versioning.

**Comment by daveisfera** [comment]
Thanks for the clarification!
