### ISSUE TITLE
Compromised secret

### ISSUE THREAD

**Issue by chaoscommencer** [actions/cache#1063]
GitHub's key scanning security feature raises the following alert for three places in this repository:

Azure Storage Account Access Key
#1
Open
GitHub detected a secret 10 hours ago · Beta [Give us feedback](https://github.com/community/community/discussions/categories/code-security)
This secret is compromised
Anyone with read access can discover secrets exposed in this repository, potentially resulting in unauthorized access to your services.
Suggested action: If this is an active [Azure Storage Account Access Key](https://github.co/microsoft_azure_storageaccount_key), then rotate and revoke the secret to avoid any irreversible damage.

- dist/save/index.js
- dist/restore/index.js
- dist/restore-only/index.js
- dist/save-only/index.js

For security purposes, not writing the key here.  Please contact if you need further assistance resolving this issue, or if you believe it is already resolved or a non-issue.

**Comment by vsvipul** [comment]
This is safe to ignore and might be part of some azure storage package.
I could also find this at https://learn.microsoft.com/en-us/azure/storage/common/storage-configure-connection-string .
