### ISSUE TITLE
`cache/save`: update contents with an existing cache key

### ISSUE THREAD

**Issue by gerlero** [actions/cache#1071]
In cases where a key already exists in the cache, the `save` action reports success but the cache contents are not actually changed. The output reads (cache key and version redacted for clarity):

```
Failed to save: Unable to reserve cache with key [key], another job may be creating this cache. More details: Cache already exists. Scope: refs/heads/main, Key: [key], Version: [version]
Warning: Cache save failed.
```

This was somewhat surprising to me, as I would've expected a successful invocation of the granular `save` action to replace any existing contents mapped to that key.

I'd like to suggest a change to the behavior of `cache/save` so that it updates the contents of the cached entry when given an existing key; or, alternatively, the addition of an option to get that behavior.

**Comment by vsvipul** [comment]
@gerlero This functioning is expected and cache is built on the principle that "each key uniquely identifies a cache". if a cache contents have changed and you need to update it, its key should also reflect that. This is reflected in all of our examples at https://github.com/actions/cache/blob/main/examples.md . 

I'm closing this issue. Feel free to reopen if you have any more questions/suggestions.

**Comment by gerlero** [comment]
That's fair enough; although it does make workflows like mine more difficult than they need to be due to having to rely on
`restore-keys` instead, whereas with the ability to directly update a cache entry that would not be needed.

As for the examples, I was actually going with https://github.com/actions/cache/blob/main/restore/README.md#reusing-primary-key-and-restored-key-in-the-save-action, which mentions how one might use the same key for `cache/restore` and `cache/save`. I took that to imply that `save` can be used—and will work—when passed an existing key, as the suggestion of reusing "the key of the cache that was restored" doesn't really make sense to me otherwise.

**Comment by wagmiwiz** [comment]
I know this is closed but I also had the same assumption after reading the docs (especially the ones @gerlero pointed to above). In my workflow I simply want to update (or overwrite) an existing cache that is keyed the same. This is because generating a unique key for the cache would require me to do the full work as if there was not cache (so its a catch-22).

**Comment by gerlero** [comment]
@wagmiwiz Glad to know I'm not the only one who got that from the docs (while also needing that functionality).

> This is because generating a unique key for the cache would require me to do the full work as if there was not cache (so its a catch-22).

I'm actually working around that by appending a unique value (using `${{ github.run_id }}` in my case) to the key on save, and then relying on `restore-keys`'s prefix matching to avoid needing to know the unique value at restore. Maybe you can do something like this?

Not gonna lie, though: the resulting workflow is needlessly ugly and brittle.

I'd still fully support a change to `cache/save` that allows updating/overwriting and existing entry.
