### ISSUE TITLE
Cannot restore linux cache with on windows with enableCrossOsArchive

### ISSUE THREAD

**Issue by maybeec** [actions/cache#1072]
Related to #984, I am facing an issue with caches created on linux and trying to restore them on windows. Please see the [used workflow definition](https://github.com/devonfw/cobigen/blob/b498c23f13e4b38e6436130337d2bb4254e954f7/.github/workflows/maven-build-test.yml) and as part of that the [devonfw-actions/java-maven-setup@main version used](https://github.com/devonfw-actions/java-maven-setup/tree/c7414aeb97abaefbade95154f9889311df5f52cf) at runtime.

[Saving Log on Linux:](https://github.com/devonfw/cobigen/actions/runs/3906646393/jobs/6679722923#step:11:5)
![image](https://user-images.githubusercontent.com/1427255/212255217-d9393ef4-7a2a-46e5-9685-800dd7bff835.png)

[Restore Log on Windows:](https://github.com/devonfw/cobigen/actions/runs/3906646393/jobs/6679723452#step:5:223)
![image](https://user-images.githubusercontent.com/1427255/212255125-a83684cb-2ab5-4623-828f-26df41cde665.png)

The cache can be found by gh cli:
![image](https://user-images.githubusercontent.com/1427255/212255439-99b2eb74-5175-4157-a770-d4e9638610c7.png)

I would be happy for any helpful ideas forward. For sure the workaround is to rebuild everything on windows as well and cache it separately by putting the OS name into the cache key. Nonetheless, it's not sustainable to run the build all the time twice and even would lead to the fact, that eventually I will not be able to test artifacts built on linux on a different OS.

**Comment by bishal-pdMSFT** [comment]
@maybeec you are using different cache keys for linux and windows. That is causing the cache lookup to not find the right cache. You should remove `${{ matrix.os }}` or similar such things which will create OS specific keys from your workflow - e.g. [here](https://github.com/devonfw/cobigen/blob/033d462bfb3eb22ac1a26c1968b704a034baa8cb/.github/workflows/maven-build-test.yml#L96)

**Comment by maybeec** [comment]
@bishal-pdMSFT you are totally right, seems that I had the wrong build under observation :/
I already fixed that, but seems that night was too late to make a proper issue report :/
I updated the initial post. Sry for the inconveniences.

**Comment by bishal-pdMSFT** [comment]
As mentioned in the logs, cache lookup fails to find a cache with same version. Since we are creating cross-os compatible cache in this case, the other factor is the `paths` being used for creating and restoring cache. See more about the cache matching logic [here](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#matching-a-cache-key).

In this particular case, the save path is [this](https://github.com/devonfw/cobigen/blob/033d462bfb3eb22ac1a26c1968b704a034baa8cb/.github/workflows/maven-build-test.yml#L95) but restore path is [this](https://github.com/devonfw/cobigen/blob/033d462bfb3eb22ac1a26c1968b704a034baa8cb/.github/workflows/maven-build-test.yml#L127). Please try with same path.

**Comment by maybeec** [comment]
@bishal-pdMSFT, the save path vs. restore path you are refering to is not the same cache. It doesn't even have the same key.

The logs show above relate to [build-step-saving-cache](https://github.com/devonfw/cobigen/blob/033d462bfb3eb22ac1a26c1968b704a034baa8cb/.github/workflows/maven-build-test.yml#L78) => [test-step-restoring-cache](https://github.com/devonfw/cobigen/blob/033d462bfb3eb22ac1a26c1968b704a034baa8cb/.github/workflows/maven-build-test.yml#L127), which shows the same cache key as well as the same cache path

**Comment by maybeec** [comment]
Ok eventually got it to work. The summary and findings of my solution and insights gained:

If you want to use `enableCrossOsArchive`, you can just cache anything which is placed within the workspace folder as you cannot use relative paths like `../`. In addition, there is early parameter evaluation for actions. So if you pass something like `${{ github.workspace }}/.m2/repository` as cache path, it will result in an absolute path, which will not match across OS in any case.

I therefore consider cache to work properly. It was basically my issue of getting a proper solution for maven cache and the insight to not cache anything outside of the workspace.

**Comment by bishal-pdMSFT** [comment]
Sorry, this issue flew under my radar. But good to see you able ti unblock yourself.

Yes the `${{ github.*}}` gets evaluated and it may result in different absolute paths. I think it would be a good point to add to the doc [here](https://github.com/actions/cache/blob/main/tips-and-workarounds.md#cross-os-cache).

I am curious about your observation on `../`. This should have worked if the path outside workspace remains same for different OS.
