### ISSUE TITLE
Unable to restore cache not created via container

### ISSUE THREAD

**Issue by Jademalo** [actions/cache#1083]
I have a workflow that builds an application, and caches the tools needed for building.
Due to some complexities, I wanted to run the build in a container. To do this I added `container: my/container:latest` to the job with no other changes on the same branch.
When this workflow ran, it didn't use the existing cache, throwing a no match error. Instead it created a brand new cache with the exact same name and branch ID. There was only one commit different between the two builds only adding that single line, but no matter what I tried in terms of cache maching it would not pick up the old cache.

It seems that for whatever reason, the version of the workflow running in a container couldn't use the cache saved outside of the container. The container was running Debian, so I don't believe this was an incompatible OS issue.
Once the containerised workflow had run and generated a cache, this cache could be used without issue.

Is this intended behaviour to do with scope, or is this an error?

**Comment by Jademalo** [comment]
I'm not entirely sure if this is related, but I also seem to have issues restoring a cache if the `path:` argument isn't the same.

I had attempted to create a cache that caches 4 different versions of a build, but trying to restore just one of those versions with a more restrictive path resulted in the cache not being found. 

It feels like a lot more than simply the cache key is being required for a match, though I'm not sure what the actual requirements are.

**Comment by Phantsure** [comment]
> I'm not entirely sure if this is related, but I also seem to have issues restoring a cache if the path: argument isn't the same.

For restoring the cache, (key, path) should be same.

>  The container was running Debian, so I don't believe this was an incompatible OS issue.

Can you provide exact logs? I feel different compression methods might be at play. Debian container might not have **zstd** by default and it would be relying on **gzip**.

**Comment by Jademalo** [comment]
Ok, here are two log archives, I have added the build-x.yml to the respective archive;

[logs_845.zip](https://github.com/actions/cache/files/10555864/logs_845.zip) - 845 is a successful run of `build-debug.yml` that restores `cache-tools` from a previous run
[logs_846.zip](https://github.com/actions/cache/files/10555867/logs_846.zip) - 846 is an unsuccessful run of `build-modern.yml` (due to an unrelated error) that doesn't restore the existing cache even though the Cache Tools step is the same.

Both runs have the same workflow step relating to the cache, the only difference that should matter as far as I can tell is that one runs on a container, the other doesn't;

```
      # caches the tools necessary for building the ROM, poryscript and agbcc
      - name: Cache Tools
        uses: actions/cache@v3
        id: tools
        with:
          path: |
            tools/agbcc
            tools/poryscript
          key: ${{ runner.os }}-tools
```

The thing I don't understand is why 845 was able to restore, but 846 was not. They were both triggered from the same commit with the same key, so as far as I can tell they should both have recognised the cache.

Hopefully that's enough information, if it's not then when I get a bit of time I can try to force the situation in a new repo.

**Comment by Phantsure** [comment]
@Jademalo Can you provide debug logs for similar workflows? You may have to enable debug step: https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging

I still have a feeling that this is the case :
> I feel different compression methods might be at play. Debian container might not have zstd by default and it would be relying on gzip.

If this is the case then it is expected

**Comment by Jademalo** [comment]
Alright, I don't have time right now but I'll try and get those when I have a minute.

**Comment by Jademalo** [comment]
Ok, had some time to test this. Decided to make a public repo with as simple a setup as I could think of specifically to test the cache - https://github.com/Jademalo/cache-test

https://github.com/Jademalo/cache-test/actions/runs/4094572036
https://github.com/Jademalo/cache-test/actions/runs/4094581095
Here are two runs, one that uses the container and one that does not. As you can see, the second run that uses the container does not successfully load the cache, and creates a second cache.
![image](https://user-images.githubusercontent.com/386846/216798850-db841140-5107-4baa-99f3-437c6c225ed0.png)

I believe your theory was correct - https://github.com/Jademalo/cache-test/actions/runs/4094581095/jobs/7060891423#step:4:35
`##[debug]Unable to locate executable file: zstd. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.`

Interestingly, the debug output seems to give a scope error.

**Comment by Jademalo** [comment]
https://github.com/Jademalo/cache-test/actions/runs/4094614074/jobs/7060956673#step:4:1

Tried again but this time with the action installing zstd, and the original cache was correctly restored. This is definitely the reason for the issue.

**Comment by Phantsure** [comment]
@Jademalo https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#matching-a-cache-key doc provides information about cache version and how it is related to path and compression algorithm:
> Cache version is a way to stamp a cache with metadata of the path and the compression tool used while creating the cache. This ensures that the consuming workflow run uniquely matches a cache it can actually decompress and use.

Yes, This is as simple as installing zstd. Closing this issue as resolved

**Comment by Jademalo** [comment]
If that was always there, then apologies for being extremely blind! I must've read that section 2-3 times before I posted my previous comment.
