### ISSUE TITLE
Refreshing cache solution/hack.

### ISSUE THREAD

**Issue by Lord-Kamina** [actions/cache#1093]
Hi. So, I know this horse has been beaten to undeath already, but...

I made a fork of this action that incorporates an optional hack to refresh existing caches. The way it does this is essentially using octokit to delete it, and then re-uploading it as if there hadn't been a hit in the first place. Is there potential interest in this and/or a chance of it getting merged?

Essentially what I'm asking is, are you interested in a PR?

**Comment by Phantsure** [comment]
Community did have interest in having mutable cache entries. I can't guarantee that it will get merged but you are free to open PR and see if there is still interest for that.
