### ISSUE TITLE
Does it restore with a forward match if specified for `key`? (not `restore-keys`)

### ISSUE THREAD

**Issue by Hiroshiba** [actions/cache#1094]
Hello! I have been using `cache`, very useful.

Is the `key` string forward matching?
For example, if `key=foo`, does it match `key=foobar` or not?

I think `restore-keys` is a forward matching specification.
But since `key` also forward matched, I thought it might be a bug and came here to report it.

Here is the log.

> key: ubuntu-20.04-voicevox-core-voicevox_core-linux-x64-cpu-0.14.0
> Cache restored from key: ubuntu-20.04-voicevox-core-voicevox_core-linux-x64-cpu-0.14.0-preview.4

```bash
Run actions/cache@v3
  with:
    key: ubuntu-20.04-voicevox-core-voicevox_core-linux-x64-cpu-0.14.0
    path: download/core
    enableCrossOsArchive: false
    fail-on-cache-miss: false
  env:
    PYTHON_VERSION: 3.8.10
    VOICEVOX_RESOURCE_VERSION: 0.14.0
    VOICEVOX_CORE_VERSION: 0.14.0
    pythonLocation: /opt/hostedtoolcache/Python/3.8.10/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.8.10/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.8.10/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.8.10/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.8.10/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.10/x64/lib
    MSYS: winsymlinks:nativestrict
Received 0 of 702401041 (0.0%), 0.0 MBs/sec
Received 79691776 of 702401041 (11.3%), 38.0 MBs/sec
Received 188743680 of 702401041 (26.9%), 60.0 MBs/sec
Received 306184192 of 702401041 (43.6%), 72.9 MBs/sec
Received 419430400 of 702401041 (59.7%), 79.9 MBs/sec
Received 528482304 of 702401041 (75.2%), 83.9 MBs/sec
Received 629145600 of 702401041 (89.6%), 85.6 MBs/sec
Received 702401041 of 702401041 (100.0%), 80.6 MBs/sec
Cache Size: ~670 MB (702401041 B)
/usr/bin/tar -xf /home/runner/work/_temp/575f5ea6-2037-472b-9f8f-c3b5bfa684e0/cache.tzst -P -C /home/runner/work/voicevox_engine/voicevox_engine --use-compress-program unzstd
Cache restored successfully
Cache restored from key: ubuntu-20.04-voicevox-core-voicevox_core-linux-x64-cpu-0.14.0-preview.4
```

Github Runs: https://github.com/VOICEVOX/voicevox_engine/actions/runs/4047017525/jobs/6960530619

**Comment by Phantsure** [comment]
@Hiroshiba I can confirm this finding. Same is the case with my testing.

**Comment by Phantsure** [comment]
@Hiroshiba `cache-hit` is set as false in this case so nothing should break if you follow our recommendations of creating primary and restore keys

**Comment by Hiroshiba** [comment]
@Phantsure 
I see!!

I thought it would be easier to understand if the documentation said that `key` is also restored with forward matching!
(In my case, since the documentation says `restore keys` is forward matching, so I mistakenly thought that `primary key` is exact matching.)

**Comment by tanuj077** [comment]
Hi @Hiroshiba, I agree that the documentation should have been more clear. We will take this up and fix it in the documentation. Thanks :)

**Comment by daxpedda** [comment]
Could the behavior not be changed?

Right now it's impossible to only restore cache with a specific key, you have to restore, check the `cache-hit` output, and then delete the cache again if it's not a hit.
