### ISSUE TITLE
Probably inconsistent documentation regarding outputs.key for Restore action

### ISSUE THREAD

**Issue by PsykerUdot** [actions/cache#1098]
[Reusing primary key from restore cache as input to save action](https://github.com/actions/cache/blob/main/caching-strategies.md#reusing-primary-key-from-restore-cache-as-input-to-save-action) article states that `key` output can be used for `restore` action. But [Restore action](https://github.com/actions/cache/blob/main/restore/README.md#restore-action) documentation states there is no such output.

**Comment by kotewar** [comment]
Agree, should have been `cache-primary-key` instead of `key`. Will correct it 👍🏽

**Comment by kotewar** [comment]
Fixed.
