### ISSUE TITLE
Support always saving in cache action

### ISSUE THREAD

**Issue by shooit** [actions/cache#1099]
The save action can be configured to always save by setting `if: always()`. It would be nice to support this for the cache action as well.

For example, when running a PR check we would like the dependencies to be cached. However, if the check itself fails, the dependencies won't be cached because the cache action only saves on `success()`. Since installing dependencies is the majority of the workflow, the check could be much faster if they were cached.

I realize that we could re-create this functionality through a combination of restore and save, but it would be nice for it to exist as an option to cache.

**Comment by pdotl** [comment]
Hi @shooit thank you for creating this. We already support this by using the restore and save actions separately as you mentioned above. So won't be considering this in the main action for now. Feel free to reopen this issue if you have further concerns.
