### ISSUE TITLE
Restoring cache across multiple actions not idempotent - `Cannot open: File exists`

### ISSUE THREAD

**Issue by mbrancato** [actions/cache#1104]
When using `actions/cache@v3` to restore cache, the `tar` command will return an error code and print `Cannot open: File exists` for every file if cache was restored by a previous action. The cache restoration should be idempotent.

The use-case here is various composite actions which call other actions and use conditions. Multiple actions may want the cache, and while efficient to reuse the already-restored cache, that would also require passing that information along or some other check. to allow composite actions to be more flexible and reusable, having them execute certain dependencies like `actions/cache@v3` removes complexity.

Attempting to restore the cache twice results in output like the following:

```
Run actions/cache@v3
  with:
    path: ~/.cache/go-build
  ~/go/pkg/mod
  
    key: Linux-go-7e197800e4dfa8d5dfbb917ac27f36110352a5348bf33ed2988da48e67300d[86](https://github.com/my-org/my-repo/actions/runs/4113797055/jobs/7105151932#step:8:94)
    enableCrossOsArchive: false
    fail-on-cache-miss: false
  env:
    MSYS: winsymlinks:nativestrict
Received 4194304 of 92671637 (4.5%), 4.0 MBs/sec
Received 92671637 of 92671637 (100.0%), 46.1 MBs/sec
Cache Size: ~[88](https://github.com/my-org/my-repo/actions/runs/4113797055/jobs/7105151932#step:8:96) MB ([92](https://github.com/my-org/my-repo/actions/runs/4113797055/jobs/7105151932#step:8:100)671637 B)
/usr/bin/tar -xf /home/runner/work/_temp/0e110550-cccf-41a8-8669-2d41a827f78c/cache.tzst -P -C /home/runner/work/my-repo/my-repo --use-compress-program unzstd
/usr/bin/tar: ../../../go/pkg/mod/go.uber.org/atomic@v1.7.0/.github/PULL_REQUEST_TEMPLATE.md: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/go.uber.org/atomic@v1.7.0/int64_test.go: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/go.uber.org/atomic@v1.7.0/nocmp.go: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/go.uber.org/atomic@v1.7.0/uint32_test.go: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/go.uber.org/atomic@v1.7.0/error.go: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/go.uber.org/atomic@v1.7.0/example_test.go: Cannot open: File exists
...
/usr/bin/tar: Exiting with failure status due to previous errors
Warning: Failed to restore: "/usr/bin/tar" failed with error: The process '/usr/bin/tar' failed with exit code 2
Cache not found for input keys: Linux-go-7e197800e4dfa8d5dfbb917ac27f36110352a5348bf33ed2988da48e67300d86
```

**Comment by mbrancato** [comment]
The simple answer here may seem to be to clear those cache target folders before restoring: 

```
Run rm -rf ~/.cache/go-build
  rm -rf ~/.cache/go-build
  rm -rf ~/go/pkg/mod
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    MSYS: winsymlinks:nativestrict
rm: cannot remove '/home/runner/go/pkg/mod/go.uber.org/atomic@v1.7.0/.github/PULL_REQUEST_TEMPLATE.md': Permission denied
rm: cannot remove '/home/runner/go/pkg/mod/go.uber.org/atomic@v1.7.0/int64_test.go': Permission denied
rm: cannot remove '/home/runner/go/pkg/mod/go.uber.org/atomic@v1.7.0/nocmp.go': Permission denied
```

**Comment by pdotl** [comment]
@mbrancato it would help me understand the issue better if you could share the workflow file or the workflow run. I'll try to reproduce this issue and investigate further.

**Comment by kezhenxu94** [comment]
Hi, @pdotl here we have a workflow run for you https://github.com/seata/seata/pull/5461#issuecomment-1479011276

**Comment by kezhenxu94** [comment]
To be clear, we have [a composite github actions](https://github.com/apache/skywalking-eyes/blob/e1a02359b239bd28de3f6d35fdc870250fa513d5/header/action.yml#L47-L59) where we set up the cache, and in our use case, users can use our github action multiple times (for different aspects of checking licenses), hence issue occurs.

**Comment by Integralist** [comment]
I get this issue in a single workflow file: see my open discussion on the forums here...

https://github.com/orgs/community/discussions/58174

**Comment by Integralist** [comment]
The following suggestion works on Linux and macOS but not Windows...

```
- name: Clear cache directory first before trying to restore from cache
  run: sudo rm -rf $(go env GOMODCACHE) && sudo rm -rf $(go env GOCACHE)
  shell: bash
```

Apparently, Windows doesn't have sudo. So does anyone know how best to work around that?

**Comment by Integralist** [comment]
Nevermind. 

The issue with restoring the cache was never occurring on Windows, only nix systems.

So I don't actually need to remove the directories on that platform.

**Comment by Integralist** [comment]
**UPDATE:** Turns out I can just disable the caching that's coming from the setup-go action, which avoids the later cache restoration error I was seeing. So both approaches work but disabling the caching from the setup-go action requires less code.
