### ISSUE TITLE
"Cache not found" and outputs cache-hit is set to empty string instead of boolean

### ISSUE THREAD

**Issue by petkaantonov** [actions/cache#1116]
Restoring claims that cache has not been found:

<img width="915" alt="kuva" src="https://user-images.githubusercontent.com/829734/220060682-c7f431ea-0caf-4d13-9bd4-9d921611d40f.png">

But it is found:

<img width="740" alt="kuva" src="https://user-images.githubusercontent.com/829734/220060743-71cf9ee3-cc5b-461d-932b-0a52d33e3dfe.png">

Also as you can see from the comparison, `${{ steps.yarn-cache.outputs.cache-hit }}` is being evaluated to empty string instead of `false` or `true`.

<img width="641" alt="kuva" src="https://user-images.githubusercontent.com/829734/220061138-145b65ea-36b6-43d3-b172-eea6de959d04.png">

Runner is ubuntu-22.04 and the cache was created by ubuntu-22.04. It is pure linux-for-linux caching.

**Comment by mikeage** [comment]
This appears to be a duplicate of #1110

**Comment by petkaantonov** [comment]
> This appears to be a duplicate of #1110

No, we dont use osx or cross platform caching.

**Comment by mikeage** [comment]
Was your cache created before Feb 17th? There's an issue with restoring caches now that were created then, because zstd is no longer being used; only gzip. Despite having the same names, they're not compatible.

(if not, sorry for the confusion)

**Comment by petkaantonov** [comment]
Yes, we will try removing the cache and installing from scratch

**Comment by petkaantonov** [comment]
Removing the cache manually and triggering reinstall worked
