### ISSUE TITLE
Restore multiple chaces/files at once

### ISSUE THREAD

**Issue by frenzymadness** [actions/cache#1117]
Hi.

I'd like to use the cache/save and cache/restore actions to collect and analyze files from multiple jobs. Let's say I save 10 files in 10 individual jobs each with a unique filename and a unique cache key. Then I'd like to download all of the files in a single job where I'd combine them and produce results. All of those jobs are run in a single workflow.

Is this possible without invoking cache/restore action for every individual file again and again and without repeating their unique keys?

Something like: restore all the cache entries matching this key (regex, glob, prefix … you name it).

By the way, it seems that this is supported by upload-artifacts/download-artifacts actions, see https://github.com/actions/download-artifact#download-all-artifacts

**Comment by pallavx** [comment]
Hi @frenzymadness,

Restoring all caches by prefixes is not supported by this action. 

Additionally, this might not be the best use-case for `actions/cache`. You can consider using `actions/download-artifact` for your use-case.

**Comment by skjnldsv** [comment]
@pallavx I have the same issue.
While artifacts are good, they are insanely slow compared to caches.
I think being able to restore multiple caches to share data between a matrix of actions would be a nice enhancement :)
