### ISSUE TITLE
Cross-OS cache is non-coherent

### ISSUE THREAD

**Issue by LebedevRI** [actions/cache#1119]
There appears to be some cache consistency issue,
at least when the cache is being restored
on a different OS it was created on.

Example:
* This job created the cache `Cache saved with key: coverage-2ec84780854ccde800df79c4b10e51bf802f1232-macOS
`
https://github.com/darktable-org/rawspeed/actions/runs/4233266783/jobs/7355207131#step:12:13
* This job, which started afterwards (as per `needs`), fails to find it: `Error: Failed to restore cache entry. Exiting as fail-on-cache-miss is set. Input key: coverage-2ec84780854ccde800df79c4b10e51bf802f1232-macOS
`
https://github.com/darktable-org/rawspeed/actions/runs/4233266783/jobs/7355214037#step:31:15

Rerunning the second job does not change the outcome.
But this is working in principle, e.g. https://github.com/darktable-org/rawspeed/actions/runs/4227408578/jobs/7342201975#step:31:19

**Comment by Phantsure** [comment]
- This feels similar to this issue: https://github.com/actions/cache/issues/1083
Can you try to reproduce the steps mentioned there?

**Comment by LebedevRI** [comment]
Yep, that sounds like it. Pretty horrible UX though.
Thanks.
