### ISSUE TITLE
Cache save is too slow in container job

### ISSUE THREAD

**Issue by asvataa** [actions/cache#1126]
Hi There!

Cache save is too slow in container job

There is screenshots 

1. **Save cache without container = 4 sec.**

<img width="1113" alt="Снимок экрана 2023-02-28 в 12 18 23" src="https://user-images.githubusercontent.com/121012947/221778016-c91505f9-c437-44c5-a6f2-8de26d7e379f.png">

2. **Save cache in container without cpu tuning = 16 sec.**

<img width="1110" alt="Снимок экрана 2023-02-28 в 12 20 06" src="https://user-images.githubusercontent.com/121012947/221778069-d913c57b-f009-42d8-9363-0218b04bd9a9.png">

3. **in container with cpu tuning up to 2 core = 11 sec.**

<img width="1110" alt="Снимок экрана 2023-02-28 в 12 20 27" src="https://user-images.githubusercontent.com/121012947/221778106-17ba0a93-afe0-42dc-af51-dae85851d0ab.png">

All files was the same for all tests

I don't understand where is a problem? Why is it become slowly?

**Comment by kotewar** [comment]
Hi @asvataa ,

Can you please share sample workflow runs (in a different repo if its private with minimum code to replicate the issue) with [runner diagnostic and step debug logs](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-runner-diagnostic-logging) enabled so that we can take a closer look? Thanks.

**Comment by asvataa** [comment]
@kotewar Hi,

https://github.com/asvataa/cache-save-issue/actions/runs/4291052955/jobs/7475762430

**Comment by Phantsure** [comment]
@asvataa Can you please provide a workflow run with debug logs? For that you may need to enable a secret. Follow this guide: https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-runner-diagnostic-logging

**Comment by asvataa** [comment]
@Phantsure this is it? https://github.com/asvataa/cache-save-issue/actions/runs/4310600493

**Comment by Phantsure** [comment]
<img src="https://user-images.githubusercontent.com/121012947/221778069-d913c57b-f009-42d8-9363-0218b04bd9a9.png">
Logs in purple here are debug logs. Have to set `ACTIONS_STEP_DEBUG` as true in repository secrets or you can re-run workflow with a check to enable debug logs:
<img width="217" alt="Screenshot 2023-03-02 at 3 50 43 PM" src="https://user-images.githubusercontent.com/25999504/222400897-7054e945-8939-4d2a-858c-83603072f07c.png">

**Comment by asvataa** [comment]
@Phantsure my bad https://github.com/asvataa/cache-save-issue/actions/workflows/build-nodejs.yml
