### ISSUE TITLE
MacOS Pods Cache restore gets stuck indefinitely for the size more than 3gb

### ISSUE THREAD

**Issue by Ananthakr-Jupiter** [actions/cache#1136]
The macos cache restore process gets stuck for a long time(more than 1hr) and gets timed out. We have been facing this problem recently when our pods cache size jumped from 1.8gb to 3gb. 

<img width="1291" alt="Screenshot 2023-03-16 at 1 58 15 PM" src="https://user-images.githubusercontent.com/105293354/225559265-d13ab67d-679e-4c6f-a201-2a9adfd5251b.png">

<img width="1341" alt="Screenshot 2023-03-16 at 2 02 07 PM" src="https://user-images.githubusercontent.com/105293354/225559547-081c406f-c7b1-4269-b606-5a5800ca6913.png">

We couldn't find any possible reason why this happens and also not sure if we are hitting any storage limitations in the runner machines. May be related to this issue(https://github.com/actions/cache/issues/1115), but in our case the job gets cancelled automatically after 1.5hrs.

Let me know if any more information is needed

**Comment by dexpota** [comment]
It's likely the same issue as #1115. Anyway I solved this issue by manually cloning the `Specs` repository and removing the caching mechanism altogether. It's more fast this way. This is the workflow's step.

```
- name: Add CocoaPods Specs
  run: |
    mkdir -p ~/.cocoapods/repos/cocoapods
    git clone --depth 1 -b master https://github.com/CocoaPods/Specs.git ~/.cocoapods/repos/cocoapods
```

**Comment by numandev1** [comment]
@vsvipul is there any update?

**Comment by vsvipul** [comment]
@numandev1 I'm no longer working at GitHub. Please contact people on https://github.com/actions/toolkit to check who is the new owner for cache.
