### ISSUE TITLE
Use kebab-case for `enableCrossOsArchive`

### ISSUE THREAD

**Issue by pavelzw** [actions/cache#1137]
It would be nice for this repository to have a unified naming scheme. Since most other parameters for official GitHub Actions use kebab-case, `enableCrossOsArchive` should too.

**Comment by tiwarishub** [comment]
👋 @pavelzw Thank you for letting us know. Yes, it should be kebeb-case but changing it now will break existing workflows. As this is a breaking change, we will not do it in v3. I will keep a track of it internally, if we will change this in v4 version(which is currently not planned yet). I will close this issue and will keep a track of it for v4.
