### ISSUE TITLE
How to use `actions/cache@v1` inside of another action

### ISSUE THREAD

**Issue by asottile** [actions/cache#114]
Hello!  I'm looking to develop an action for the platform.  In my action, I'd like to be able to call `actions/cache@v1` and set the proper values instead of having my users copy and paste that definition

I tried initially some hacky attempts where I installed this repository from git and then set `process.env.INPUT_KEY` / `process.env.INPUT_PATH` used `require` to attempt to run this action however this didn't seem to work as some of the state was not passed along.

Is there a supported way to reuse actions in this way?  Seems kind of unfortunate to require to copy and paste all that yaml around 😢

**Comment by Ameobea** [comment]
Yeah you can def. call actions from other actions; composing them is a really useful pattern for re-using functionality.

The Cypress (frontend testing framework) action uses the cache action and provides the ability to configure the cache key if desired: 

https://github.com/cypress-io/github-action/blob/master/index.js#L7

https://github.com/cypress-io/github-action/blob/master/package.json#L35

**Comment by asottile** [comment]
@Ameobea that's a little different -- the official `actions/cache` does not have the same structure as what you're importing from (seems to be a fork of the official one)

forking the official action seems very fragile, especially given the implementation details of `actions/cache` 😱

**Comment by Cyberbeni** [comment]
Duplicate of #55

**Comment by asottile** [comment]
indeed
