### ISSUE TITLE
Timeout when downloading cache blob

### ISSUE THREAD

**Issue by arkq** [actions/cache#1141]
In the https://github.com/project-chip/connectedhomeip repo we are facing lots of timeouts when using actions/cache. E.g. see this runs:

- https://github.com/project-chip/connectedhomeip/actions/runs/4508609631/jobs/7937471416?pr=25816
- https://github.com/project-chip/connectedhomeip/actions/runs/4503067055/jobs/7925771317   (this one timed-out due to time constraint in the step, however the question is, why the download was so slow?)
- https://github.com/project-chip/connectedhomeip/actions/runs/4483262754/jobs/7882335754

In most cases it seems that the timeout occurred due to broken connection, e.g.:
```
Received 12582912 of 2194729101 (0.6%), 12.0 MBs/sec
...
Received 947912704 of 2194729101 (43.2%), 81.7 MBs/sec
Received 1065353216 of 2194729101 (48.5%), 84.3 MBs/sec
Received 1161822208 of 2194729101 (52.9%), 84.8 MBs/sec
...
Received 1912602624 of 2194729101 (87.1%), 86.5 MBs/sec
Received 2042626048 of 2194729101 (93.1%), 88.2 MBs/sec
Received 2139095040 of 2194729101 (97.5%), 88.3 MBs/sec
Received 2143289344 of 2194729101 (97.7%), 84.8 MBs/sec
Received 2143289344 of 2194729101 (97.7%), 81.5 MBs/sec
...
Received 2143289344 of 2194729101 (97.7%), 51.0 MBs/sec
...
Received 2143289344 of 2194729101 (97.7%), 16.7 MBs/sec
...
```

If not for the step timeout constrain, the download speed would drop to kBs/sec.

Is there any way to remedy this download issue?

**Comment by bjonnh-work** [comment]
We see the same thing, it will hang for sometimes 10 min then fail, where on other workers running at the same time it took only 20s to pull the cache.

**Comment by pmengelbert** [comment]
We are also seeing the same issue

**Comment by AndrewKahr** [comment]
I've been running into this as well, we have a cache of 4GB and 2/3 runs will timeout. It would be a big help if this got resolved
