### ISSUE TITLE
NuGet cache on macOS is unexpectedly over cache limit

### ISSUE THREAD

**Issue by gitfool** [actions/cache#115]
See [gitfool/Cake.Dungeon](https://github.com/gitfool/Cake.Dungeon) workflow builds for commit [3cc36dc](https://github.com/gitfool/Cake.Dungeon/commit/3cc36dcc81bfcaaf49ebf5fd5ea3275979e642b9):
- [Linux](https://github.com/gitfool/Cake.Dungeon/runs/318467284)
- [Mac](https://github.com/gitfool/Cake.Dungeon/runs/318467288)
- [Windows](https://github.com/gitfool/Cake.Dungeon/runs/318467275)
- [Docker](https://github.com/gitfool/Cake.Dungeon/runs/318470817)

All NuGet caches are ~15 MB, except for the Mac which [warns](https://github.com/gitfool/Cake.Dungeon/runs/318467288#step:10:3) it's ~**4275** MB and so does not save it.

FWIW, the same [build](https://dev.azure.com/gitfool/Cake.Dungeon/_build/results?buildId=346&view=logs&j=a82d9e72-1de4-5bd6-c188-90296135479e&t=6bea8dfa-9275-4f28-821b-965590ba6931&l=31) works as expected on Azure Pipelines.

**Comment by dhadka** [comment]
I saw something similar with node/yarn, where the MacOS runner had a bunch of extra dependencies pre-installed in the cache path.  Could you please add `du -h <path>` somewhere in your workflow to list out the contents and size?

**Comment by gitfool** [comment]
Workflow builds for commit [51ea558](https://github.com/gitfool/Cake.Dungeon/commit/51ea55818d166f5fe79ad0d5efc4251fa2cae278):
- [Linux](https://github.com/gitfool/Cake.Dungeon/runs/319825568) ([cache usage](https://github.com/gitfool/Cake.Dungeon/runs/319825568#step:6:1))
- [Mac](https://github.com/gitfool/Cake.Dungeon/runs/319825614) ([cache usage](https://github.com/gitfool/Cake.Dungeon/runs/319825614#step:6:1))

**Comment by dhadka** [comment]
Thanks!  Yes, this looks to be the same issue I encountered with yarn.  There's a bunch of appcenter and other packages on MacOS.  I think the solution will be to set a different folder for the .nuget packages, such as described here: https://stackoverflow.com/questions/4092759/is-it-possible-to-change-the-location-of-packages-for-nuget.  I'll test things on my end to see if this works.

**Comment by gitfool** [comment]
You can also define [NUGET_PACKAGES](https://docs.microsoft.com/en-us/nuget/Consume-Packages/managing-the-global-packages-and-cache-folders), which is the approach recommended by [Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/?view=azure-devops#netnuget), hence what I use for those builds.

That said, I'd like to know if this is intended behavior since it goes against what is recommended for GH Actions in the [examples](https://github.com/actions/cache/blob/master/examples.md#c---nuget).
