### ISSUE TITLE
Cannot write: Broken pipe

### ISSUE THREAD

**Issue by BotellaA** [actions/cache#1158]
I have a cache not saved on Windows-2019 runner: https://github.com/Geode-solutions/OpenGeode/actions/runs/4755965248/jobs/8450873300#step:13:6

This looks like #1092 but the PATH is not modified in the workflow.

```
Post job cleanup.
"C:\Program Files\Git\usr\bin\tar.exe" --posix -cf cache.tzst --exclude cache.tzst -P -C D:/a/OpenGeode/OpenGeode --files-from manifest.txt --force-local --use-compress-program "zstd -T0"
/usr/bin/tar: cache.tzst: Cannot write: Broken pipe
/usr/bin/tar: Child returned status 70
/usr/bin/tar: Error is not recoverable: exiting now
Warning: Failed to save: "C:\Program failed with error: The process 'C:\Program Files\Git\usr\bin\tar.exe' failed with exit code [2]
```

The cache is probably larger than 1GB, is this an issue?

**Comment by inforithmics** [comment]
Same error here
https://github.com/Mapsui/Mapsui/actions/runs/5756371034/job/15605646549?pr=1820

Post job cleanup.
"C:\Program Files\Git\usr\bin\tar.exe" --posix -cf cache.tzst --exclude cache.tzst -P -C D:/a/Mapsui/Mapsui --files-from manifest.txt --force-local --use-compress-program "zstd -T0"
/usr/bin/tar: cache.tzst: Cannot write: Broken pipe
/usr/bin/tar: Child returned status 70
/usr/bin/tar: Error is not recoverable: exiting now
Warning: Failed to save: "C:\Program failed with error: The process 'C:\Program Files\Git\usr\bin\tar.exe' failed with exit code [2](https://github.com/Mapsui/Mapsui/actions/runs/5756371034/job/15605646549?pr=1820#step:93:2)

**Comment by richbrowne-openfin** [comment]
Same, using `windows-latest` runner.
