### ISSUE TITLE
Allow to retry restoring cache due to 429

### ISSUE THREAD

**Issue by Luc45** [actions/cache#1163]
We have a tool that run hundreds of concurrent tests in GitHub. Some of the jobs fail when restoring cache due to 429 from the cache service:

> Warning: Failed to restore: Cache service responded with 429

Is it possible to set a option to retry X times to restore the cache after 1s if a 429 (Too Many Requests) is encountered?

**Comment by metaclips** [comment]
Also having this issue saving/restoring cache over large tests, integrating a backoff mechanism to retry download/upload after a certain amount of time will be an amazing feature

**Comment by ericbuehl** [comment]
Or is there a way to specify an alternate GITHUB_TOKEN that has a higher rate limit?
