### ISSUE TITLE
Cache with Next.js is nor working!

### ISSUE THREAD

**Issue by ImBIOS** [actions/cache#1172]
![image](https://github.com/actions/cache/assets/41441643/413a7b7a-f393-4778-981b-8a068891814c)

I'm following this https://nextjs.org/docs/pages/building-your-application/deploying/ci-build-caching#github-actions

Can anyone help me?

**Comment by manmen-mi** [comment]
related [docs](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache)

> When a cache is created by a workflow run triggered on a pull request, the cache is created for the merge ref (refs/pull/.../merge). Because of this, the cache will have a limited scope and can only be restored by re-runs of the pull request. It cannot be restored by the base branch or other pull requests targeting that base branch.

maybe you can cache in `main` branch, and use in child `ref/` (pr, tag, ...)

**Comment by ImBIOS** [comment]
> related [docs](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache)
> 
> > When a cache is created by a workflow run triggered on a pull request, the cache is created for the merge ref (refs/pull/.../merge). Because of this, the cache will have a limited scope and can only be restored by re-runs of the pull request. It cannot be restored by the base branch or other pull requests targeting that base branch.
> 
> maybe you can cache in `main` branch, and use in child `ref/` (pr, tag, ...)

Can you help me with some examples?
