### ISSUE TITLE
Incorrect documentation for `restore-keys`

### ISSUE THREAD

**Issue by Zac-HD** [actions/cache#1173]
https://github.com/actions/cache/blob/04f198bf0b2a39f7230a4304bf07747a0bddf146/README.md#L52

This turns out to be slightly but importantly wrong: the format is actually a _multi-line string_ with one key per line; attempting to supply an actual list of keys will fail to validate (c.f. https://github.com/python/cpython/pull/104468#pullrequestreview-1425935982).  I think the just updating the docs is probably better than switching to the currently-documented behavior.

**Comment by Zac-HD** [comment]
https://github.com/actions/cache/tree/main#inputs shows the same problem; the lack of a fix doesn't imply the issue should be closed.

**Comment by Zac-HD** [comment]
.

**Comment by x612skm** [comment]
Hi somebody please mind taking a look at this PR? https://github.com/actions/cache/pull/1434
