### ISSUE TITLE
Cache container deleted when using in workflow with container jobs

### ISSUE THREAD

**Issue by fergusleahytab** [actions/cache#12]
When run within a container job the action fails to run - it looks like the cache action container is deleted in the stop containers phase, before the cache post action is able to run. 

Presumably, this only runs within the context of the VM, not the container context?

**Comment by chrispat** [comment]
Thanks for reporting this issue.  I expect this will be a potential problem with any actions that includes a `post` action.  We will look into it.

**Comment by teohhanhui** [comment]
What about splitting this action into two?

- actions/save-cache
- actions/restore-cache

This will give the user a lot more control too (e.g. I might want to save the cache even before running the test steps).

**Comment by thboop** [comment]
@teohhanhui , would you please file another issue with your feedback, otherwise it may get lost in this issue.

**Comment by reneweteling** [comment]
Would be awesome to see this fixed guys :)

**Comment by gmile** [comment]
This blocks us from migrating from CircleCI

**Comment by joshmgross** [comment]
We've rolled out an updated hosted runner that fixes for post actions in container jobs.

**Comment by reneweteling** [comment]
NICE!!! ill check it out now!
