### ISSUE TITLE
Cache restore failed with symlinks in Windows

### ISSUE THREAD

**Issue by adriangodong** [actions/cache#120]
I'm working with a monorepo containing several npm packages. The root npm package.json references children npm packages using relative path. When `npm ci` / `npm i` is executed, a symlink is created for each child package to the root `node_modules` folder.

I cached the root `node_modules` folder.

The first workflow run is good, here are the steps:
1. Cache restore miss
2. Run npm ci
3. Run npm build
4. Success
5. Cache save

The second run is no good:
1. Cache restore hit
2. Skip run npm ci
3. Run npm build

This is only happening in windows-latest environment. I tried to reproduce the issue locally and found out that tar did not recreate the symlinks.

Any guidance on how to proceed?

**Comment by joshmgross** [comment]
It's likely that we need the `--dereference` flag when we exec tar on Windows. Do you have a sample repro that I can test this issue with?

**Comment by ViceIce** [comment]
Can this be the cause for our failed builds?

https://github.com/renovatebot/renovate/pull/5105/checks?check_run_id=379068534

**Comment by 9prady9** [comment]
I face similar issues with symlinks when caching a folder with soft links.

**Comment by ordian** [comment]
@joshmgross as noted in https://github.com/actions/virtual-environments/issues/572#issuecomment-626624527, this issue is blocking caching working properly for Rust projects on Windows. Is there any known workaround for this? [Here](https://github.com/openethereum/openethereum/pull/11706/checks?check_run_id=670160859#step:4:10) is a repro.

**Comment by joshmgross** [comment]
👋 Could someone confirm which Windows hosted runners they're using?

I'm curious if this issue is specific to GNU or BSD tar

**Comment by 9prady9** [comment]
> I face similar issues with symlinks when caching a folder with soft links - https://github.com/9prady9/arrayfire/runs/401235482

For mine trials, it was 2019 I think

**Comment by mzabaluev** [comment]
@ordian and possibly others with the same symptoms:

> [Here](https://github.com/openethereum/openethereum/pull/11706/checks?check_run_id=670160859#step:4:10) is a repro.

I have no idea about the symlink issues discussed here, but your issue looks like #198 and it has a [solution](https://github.com/actions/cache/issues/198#issuecomment-634123068).

**Comment by Yosger** [comment]
#633

**Comment by Yosger** [comment]
#633
