### ISSUE TITLE
Cache restored but cache-hit is false

### ISSUE THREAD

**Issue by mark-buhagiar-scottlogic** [actions/cache#1201]
We are using caching to cache our node_modules, and then only run npm CI if that cache is not found.

This is intermittently reporting that the cache was found successfully, however the `cache-hit` output variable returns `false` which means that we end up rebuilding our cache. This ends up being quite time consuming.

Is this a known defect, or are we doing something wrong?

![image](https://github.com/actions/cache/assets/60645134/87a2242e-62f2-425d-a01c-27011b6d3101)

**Comment by helloint** [comment]
I think it is because you set restore-keys. The output only be true when it get an exact match.
