### ISSUE TITLE
Caching pulled docker images

### ISSUE THREAD

**Issue by NunesMig** [actions/cache#1224]
From what I've seen this is something that this action is not intended to do but which I think would be a good functionality to have. 
It would be incredible to simply be able to use this image to cache pulled images on GitHub Actions Cache.
I for instance have to pull the same image several times a day making it incredibly toilsome. 

Are there any improvements which would add this possibility coming to us in the future?

**Comment by madeindra** [comment]
Not sure this will help, but have you try this?
https://github.com/marketplace/actions/docker-cache

**Comment by jamesbraza** [comment]
Also see https://github.com/actions/cache/issues/81, https://github.com/actions/cache/issues/31
