### ISSUE TITLE
Cache action broken on master

### ISSUE THREAD

**Issue by logsnitch** [actions/cache#123]
Using `cache@v1` works. Using `cache@master` I get the following:
<img width="846" alt="Screen Shot 2019-11-30 at 12 12 36 PM" src="https://user-images.githubusercontent.com/57203078/69905620-32077780-136b-11ea-8eaf-c9dff361a22a.png">

**Comment by peaceiris** [comment]
This action does not support the master branch.

**Comment by dhadka** [comment]
As peaceiris mentioned, this action will not work from master.  Since this action is written in TypeScript there is an extra step to build the Javascript, hence the .js files are missing from the repo and are only included in the releases.
