### ISSUE TITLE
Node16 Deprecation

### ISSUE THREAD

**Issue by kinano** [actions/cache#1233]
Node16 will be deprecated on 09/11/2023 ([link](https://nodejs.org/en/blog/announcements/nodejs16-eol)). Node 16 is used by the action at the moment according to the source code: https://github.com/actions/cache/blob/f7ebb81a3f195b4fb88dab7c14e2f7aff52045aa/action.yml#L32-L33.

Is there a plan to release a node version update soon?

**Comment by tflori** [comment]
might this cause the error I'm getting:
> Error relocating /__e/node16_alpine/bin/node: getentropy: symbol not found

I searched a bit and didn't find a result in this action issues but in checkout where one states out it works von v2, another saying it is not working on either version.

My 2 cents:
It looks like someone copied a binary on my image and hoped it would work. Is that how github actions work? by copying binaries and hope for the best? It might be better to check for the library versions and copy a binary that fits.
