### ISSUE TITLE
Cache action shouldn't use first `tar` on the path

### ISSUE THREAD

**Issue by wch** [actions/cache#125]
The `save` and `restore` steps use the first `tar` on the path:
https://github.com/actions/cache/blob/4809f4ada49f99628c256b84f23798ced8214a3c/src/save.ts#L64

This can cause problems if another step modifies the path so that a different version of `tar` is found first. For example, in this workflow, I installed R and Rtools, which added C:/Rtools/bin to the path. There is a copy of `tar.exe` in there, as well as `gzip.exe`. However, when `actions/cache` tries to use `tar`, it errors out saying it can't find `gzip`. I'm not sure why exactly that error happens, since `gzip` is in the same directory. But it seems to me that `actions/cache` shouldn't even try to use that copy of `tar` in the first place -- it should always use the same copy of `tar`, no matter what other steps are used in the workflow.

Here's the error:

```
Post job cleanup.
C:\Rtools\bin\tar.exe -cz --force-local -f d:/a/_temp/96241c04-a852-4c66-8b28-aae83ff432c1/cache.tgz -C d:/a/_temp/Library .
tar (child): gzip: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
/Rtools/bin/tar: d\:/a/_temp/96241c04-a852-4c66-8b28-aae83ff432c1/cache.tgz: Cannot write: Broken pipe
/Rtools/bin/tar: Child returned status 2
/Rtools/bin/tar: Error is not recoverable: exiting now
[warning]The process 'C:\Rtools\bin\tar.exe' failed with exit code 2
  ```

https://github.com/wch/gha/commit/b407b89c2865433ae99dc88f39830437cbd01887/checks?check_suite_id=346434710#step:22:8

**Comment by joshmgross** [comment]
Hey @wch, I'm not sure what that `gzip` issue is, but we're making a change to use BSD Tar on Windows from the System path: https://github.com/actions/cache/pull/126

For Linux and macOS, I think it's still correct to use the `tar` that's on the PATH.

**Comment by wch** [comment]
Thanks, great timing! I don't know what the `gzip` issue is either -- it works without a problem when I run `tar` locally -- but I'm glad to hear that it won't matter in the future.

Just curious: why would you want to use `tar` from the PATH on the other platforms? I can imagine that causing problems, but I don't see how it would be beneficial.

**Comment by joshmgross** [comment]
>why would you want to use tar from the PATH on the other platforms?

If we don't get `tar` from the PATH, how do we know where `tar` is?

**Comment by joshmgross** [comment]
>is it possible to store the PATH at the beginning of a workflow

Not possible currently. Actions are essentially a node process (or container) started by the runner, and they're passed the environment in its current state. Using a modified PATH is how the setup actions work (ex. [actions/setup-go](https://github.com/actions/setup-go)) as they're taking a specified version of a tool and pre-pending it to the path so that subsequent actions will use that version.

>Or perhaps use a tar npm package?

We've hit issues in the past with tar npm packages, and we currently don't have a great reason to use a separate package

**Comment by mzabaluev** [comment]
I think using `tar` from `$PATH` (#125) is non-workable in the long run. Not only you get all the problems associated with system-installed tar binaries: https://github.com/actions/virtual-environments/issues/2619, #301, #362, to reference just a few, you invite trouble from any workflow that has overridden the path. 

I think the right course of action is to settle on using GNU tar in every virtual environment, as it has proven to be the least problematic tar flavor on both Windows and Mac, and is already the default on Linux, and invoking the GNU tar binary by the absolute path. GNU tar is already provided in all three virtual environments supported by GitHub Actions.

**Comment by rfay** [comment]
GNU tar seems to be required on all platforms, and zstd has to be added as well on self-hosted machines. See https://github.com/actions/cache/issues/576

**Comment by wch** [comment]
Bump

**Comment by sammcj** [comment]
Any progress with this

**Comment by joshmgross** [comment]
> I think the right course of action is to settle on using GNU tar in every virtual environment,

We've had issues with GNU tar on Windows in the past, which is why we moved towards BSD Tar - #126



> I don't know that much about how actions work internally but is it possible to store the PATH at the beginning of a workflow?

We could pass the tar path from the restore step to the save step so that we're using the same `tar` in both.

**Comment by pdotl** [comment]
Hi @wch @sammcj we are tracking this issue in #984. Please check the current proposal there and provide comments/feedback if any. Closing this as duplicate.
