### ISSUE TITLE
Upgrade action to use node20

### ISSUE THREAD

**Issue by erikburt** [actions/cache#1260]
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

> Node 16 has reached its [end of life](https://github.com/nodejs/Release/#end-of-life-releases), prompting us to initiate its deprecation process for GitHub Actions. Our plan is to transition all actions to run on Node 20 by Spring 2024. We will actively monitor the migration's progress and gather community feedback before finalizing the transition date. Starting October 23rd, workflows containing actions running on Node 16 will display a warning to alert users about the upcoming migration.
> ## What you need to do
> ### For Actions maintainers
> Modify your actions to run on Node 20 instead of Node 16. For guidance, refer to the [Actions configuration settings ](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions).

---

Note: also applies to nested `restore` action.

**Comment by MikeMcC399** [comment]
I'm now seeing GitHub warnings for this, for instance:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: pnpm/action-setup@v2, actions/cache@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by Piedone** [comment]
This is actually done, the action [uses `node20` now](https://github.com/actions/cache/blob/main/action.yml#L37).
