### ISSUE TITLE
Error while downloading action repository

### ISSUE THREAD

**Issue by tmhuysen** [actions/cache#127]
The cache used to work fine, since yesterday I get this error:
> Current runner version: '2.162.0'
Prepare workflow directory
Prepare all required actions
Download action repository 'snickerbockers/cmake-configure@prerel1'
Download action repository 'actions/setup-python@v1'
Download action repository 'actions/checkout@v1'
Download action repository 'actions/cache@v1.0.3.'
**##[warning]Failed to download action 'https://api.github.com/repos/actions/cache/tarball/v1.0.3.'. Error Response status code does not indicate success: 404 (Not Found).**
##[warning]Back off 19.724999999999998 seconds before retry.
##[warning]Failed to download action 'https://api.github.com/repos/actions/cache/tarball/v1.0.3.'. Error Response status code does not indicate success: 404 (Not Found).
##[warning]Back off 18.944 seconds before retry.

I have no idea what changed. It simply fails to download the cache repo.

**Comment by dhadka** [comment]
Hi @tmhuysen are you still seeing this error?  The download link in the log does work (https://api.github.com/repos/actions/cache/tarball/v1.0.3), so it could be a transient issue.

**Comment by dhadka** [comment]
Closing this issue as stale.  Please re-open or create a new issue if you continue to experience this issue.
