### ISSUE TITLE
Cache files created as root

### ISSUE THREAD

**Issue by jyn514** [actions/cache#131]
I would like to cache various files created by the root user during my build. This would allow me to cache Docker steps as well as files downloaded by a different user, see https://github.com/jyn514/docs.rs/runs/349254873#step:18:1 for an example.

Currently this fails with an error from tar:

```
/bin/tar: ./overlay2: Cannot open: Permission denied
/bin/tar: ./builder: Cannot open: Permission denied
...
/bin/tar: Exiting with failure status due to previous errors
```

As a workaround, I could probably make the files world-readable, but I have a feeling that they will not be owned by the right user if the cache is hit.

**Comment by jyn514** [comment]
I _think_ this should be as simple as running `sudo tar [flags]`, since tar preserves users and permissions by default when run as root. Not sure how this should work on Windows, permissions work differently there.

**Comment by joshmgross** [comment]
@jyn514,
Thanks for reporting this issue. It looks like files not created by the current user will fail during restore. I've opened #133 to track this and combine the various reports of this issue. I've also added your proposed solution to that issue, I don't know if there are downsides to that solution but it's definitely worth looking into.
