### ISSUE TITLE
@actions/cache v4.0.0 availability on npm registry

### ISSUE THREAD

**Issue by martibenn** [actions/cache#1313]
Hello

@actions/cache v4.0.0 has been released 2 weeks ago (20240116) and it's great 🥳 
but it's not available on [npm registry](https://www.npmjs.com/package/@actions/cache?activeTab=versions)

Could it be added on the npm registry ? 🙏 
Thanks

**Comment by bernhardkaindl** [comment]
As you seem to be a js dev, maybe you could review #1326: might this fix #1323?

**Comment by Ottapettavan** [comment]
> Hello
> 
> @actions/cache v4.0.0 has been released 2 weeks ago (20240116) and it's great 🥳 but it's not available on [npm registry](https://www.npmjs.com/package/@actions/cache?activeTab=versions)
> 
> Could it be added on the npm registry ? 🙏 Thanks

**Comment by Ottapettavan** [comment]
`` #1233 #1002 #1325 #1233 #1361

**Comment by joshmgross** [comment]
The latest version of the `@action/cache` library is 3.2.4, which is on NPM.

https://github.com/actions/toolkit/blob/7463cf3da6cbcb901f535b342ef48e444fce3b8d/packages/cache/package.json#L3

The version of this action does not necessarily match the version of the library that contains most of the core functionality. For example, `v4` of this action was released to update to Node 20 but that did not require any updates to the library itself.
