### ISSUE TITLE
Document `save-always` input

### ISSUE THREAD

**Issue by bgilbert** [actions/cache#1317]
The "What's New" [README section](https://github.com/actions/cache?tab=readme-ov-file#v4) mentions a `save-always` flag, but it's not documented in the [inputs list](https://github.com/actions/cache?tab=readme-ov-file#inputs) or in the [linked documentation page](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows).

**Comment by GauthierPLM** [comment]
It seems that this feature is not working at the moment anyway (see #1315). Let's hope it get fixed soon and documented.

**Comment by joshmgross** [comment]
This input is not working as expected, so we will be removing it.

See #1315 & #1452 for more context.
