### ISSUE TITLE
`cache-hit` undefined on cache miss?

### ISSUE THREAD

**Issue by aryairani** [actions/cache#1334]
The README says:

> **Note** `cache-hit` will only be set to `true` when a cache hit occurs for the exact `key` match. For a partial key match via `restore-keys` or a cache miss, it will be set to `false`.

but `outputs.cache-hit == 'false'` doesn't seem to be true when I get a cache miss, and I noticed that the examples all use `!= 'true'`, not `== 'false'`.

I think [here](https://github.com/actions/cache/blob/main/src/restoreImpl.ts#L65) we can see `restoreImpl` return early on a miss, without setting any value for `cache-hit` at all. I'm not a TypeScript or Actions expert though.

In the meantime, I'll switch my `== 'false'` to `!= 'true'` but I feel dirty. :)

**Comment by pddg** [comment]
This problem does not seem to occur in v3, only in v4. In fact, the repositories that had been delayed updating to v4 were working fine.
In workflows that saving the cache when `outputs.cache-hit == 'false'`, the cache was no longer being saved. I recognized this too late because it simply skips a step and does not result in an error.
Is this a bug? Or is it a breaking change?

**Comment by RalfJung** [comment]
I'm seeing a potentially related problem, where our steps that have `${{ steps.cache.outputs.cache-hit != 'true' }}` now always get executed since the switch to v4. With v3, they used to be properly skipped on a cache hit, but I have not seen them skipped a single time since then.

**Comment by aryairani** [comment]
@RalfJung: I was going to say don't use `if: ${{ steps.cache.outputs.cache-hit != 'true' }}` because that's a string that will always evaluate to `true`, not a boolean expression, but if it eventually worked for you, then I have no idea how anything works.

**Comment by aryairani** [comment]
@RalfJung: I was going to say don't use `if: ${{ steps.cache.outputs.cache-hit != 'true' }}` because that's a string that will always evaluate to `true`, not a boolean expression, and that you should use `if: steps.cache.outputs.cache-hit != 'true` instead.

But if it eventually worked for you, then I have no idea how anything works.

**Comment by no-yan** [comment]
It looks like there are document revisions in progress related to this issue.
https://github.com/actions/cache/pull/1263

**Comment by joshmgross** [comment]
This is being reverted in #1467 as workflows are already dependent on `cache-hit` being undefined - #1466
