### ISSUE TITLE
workarounds for cache size quotas/limits?

### ISSUE THREAD

**Issue by aryairani** [actions/cache#1376]
Our project unfortunately requires ~45–60 mins worth, i.e. 1–1.5 GB of cacheable output per run, which makes caching very important for us. We have separate runs (with incompatible caches) for { CI, releases } x { Linux, macOS, Windows } x {<each development branch>}, so as you can imagine, we are hitting the limit and invalidating a lot, leading to way more CPU time used during runs due to cache misses.

For a while we were at 40GB of 10GB on the cache quota, and now we are at 9.1GB of 10GB, I guess that the cache eviction was made a little stricter recently.

Are there any workarounds, e.g. borrow space from other repos which hardly use any cache? Or a paid option?

I have seen the runs-on.com suggestion, but it seems challenging to set up, and I also couldn't see that it supported more than Linux, though I'm not sure.

Thanks in advance!!

**Comment by nebuk89** [comment]
Nothing right now, we are currently starting our re-write of the cache backend so that we can offer 'as big a cache as you want' come the start of the new calendar year. :) watch this space and sorry it's a little way out
