### ISSUE TITLE
Cache restore slow compared to Semaphore CI

### ISSUE THREAD

**Issue by davetapley** [actions/cache#139]
[Migrated from here](https://github.community/t5/GitHub-Actions/actions-cache-v1-is-slow-to-restore/m-p/41877#M4782).
 
[Semaphore CI have a cache](https://docs.semaphoreci.com/guided-tour/caching-dependencies/) similar to `actions/cache@v1` but theirs only takes **six seconds** to restore our  760MB `node_modules` Semaphore CI, compared to **twenty eight seconds** on GitHub Actions.

This was on Semaphore's [lowest machine type](https://docs.semaphoreci.com/ci-cd-environment/machine-types/#linux-machine-types) which is comparable to the specifications of the [GitHub-hosted runners](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources).

This behavior was observed on multiple builds across several days.

---

I don't have a repro because this was observed on a private repo, but it's easy enough to replicate. I'll create one if it's deemed necessary?

**Comment by dhadka** [comment]
Hi @dukedave, are your caches actually being created?  There is currently a 400 MB limit on the cache size (we will be increasing this limit very soon).  I suspect the restore action is failing as a result and you're having to fetch the dependencies from their source.  We also released a perf improvement in mid December that should also help cut download times.

**Comment by dhadka** [comment]
The cache limit increase is now released.  Please try again and let us know if you're still seeing slow restore times.

**Comment by imbsky** [comment]
I suspect this is a problem with the compression algorithm used.

**Comment by smeijer** [comment]
This is also my experience. 35 sec for ~ 161 mb.

![image](https://user-images.githubusercontent.com/1196524/75584811-ee5b0180-5a70-11ea-9adc-5bcb7926fd7f.png)

**Comment by imbsky** [comment]
We're already working on making it faster, and in my environment it's about three times faster. The next major version will definitely improve.

**Comment by imbsky** [comment]
See this PR: https://github.com/actions/cache/pull/202

**Comment by imbsky** [comment]
Note that this PR will take some time to merge.

**Comment by joshmgross** [comment]
👋  Cache Version 2 has multiple performance improvements, including using `zstd`for compression instead of `gzip`. See https://github.com/actions/cache#whats-new for more details.

I don't think there's anything that's specifically actionable here, if you have any other performance suggestions please open an issue.

**Comment by mbbernstein** [comment]
Hi,

I've the same issue here:
![image](https://user-images.githubusercontent.com/1004975/85814037-57ab0280-b73b-11ea-8c81-4c36616ee09c.png)

Thanks,
Michael

**Comment by imbsky** [comment]
Could you try to use the v2?

**Comment by mogusbi** [comment]
I'm also seeing the problem of the cache restores being very slow. It's ranging anywhere between a few seconds to 12 minutes as well as it just giving up after a period of time

![image](https://user-images.githubusercontent.com/3741464/86660759-edb81600-bfe2-11ea-9285-ab60c195d441.png)

![image](https://user-images.githubusercontent.com/3741464/86660783-f3adf700-bfe2-11ea-8f41-c0d74416a411.png)

**Comment by joshmgross** [comment]
👋  Hey all, this specific issue has already been resolved. If you are experiencing slow cache restores, please file a new issue with details on your specific use case and expected behavior.
