### ISSUE TITLE
This action is lacking maintenance

### ISSUE THREAD

**Issue by IanButterworth** [actions/cache#1401]
PRs are not being reviewed nor is their CI is being run.

Please add support to https://github.com/orgs/community/discussions/121811 or raise the issue if you know a better way.

**Comment by Gabrielpereira765** [comment]
Ooo

**Comment by Gabrielpereira765** [comment]
0000oo

**Comment by Gabrielpereira765** [comment]
Gostei

**Comment by DilumAluthge** [comment]
The CODEOWNERS file in this repo suggests that maybe we should ping the 

https://github.com/actions/cache/blob/0c45773b623bea8c8e75f6c82b208c3cf94ea4f9/.github/CODEOWNERS#L1-L1

**Comment by DilumAluthge** [comment]
The [CODEOWNERS file in this repo](https://github.com/actions/cache/blob/main/.github/CODEOWNERS) suggests that maybe we should ping the @actions/actions-cache team.

https://github.com/actions/cache/blob/0c45773b623bea8c8e75f6c82b208c3cf94ea4f9/.github/CODEOWNERS#L1-L1

**Comment by DilumAluthge** [comment]
Hmmm. It seems that I'm not able to ping the @actions/actions-cache team.

**Comment by bearfriend** [comment]
What is going on? Any kind of information at all as to why there is no maintainance of any kind in this repo for many months would be helpful. Sorry for the ping and thanks.

@andrejusk
@bryanmacfarlane
@cheshire137
@chrispat
@DanRigby
@dhadka
@GrantBirki
@joshmgross
@marzvrover
@mikhailkoliada
@nikola-jokic
@philip-gai
@pje
@rentziass
@TingluoHuang

**Comment by joshmgross** [comment]
👋 Hey everyone,

Just a quick update - your concerns have been heard and I'm working on getting a proper response.

This action is still being supported by GitHub, but I totally understand the concern around the lack of timely responses on issues and pull requests. If there are any urgent bug fixes or security issues, please let me know and I'll make sure they're prioritized.

**Comment by IanButterworth** [comment]
Thanks @joshmgross 

Part of the pain of not having prompt maintenance attention is that because CI is set to run on approval for new contributors PRs like https://github.com/actions/cache/pull/1325 take a lot longer to actually be tested and contributers get fatigued.

It's a bigger discussion, but I hope that either someone can stay on top of promptly running CI for new contributions, or that setting is disabled.

**Comment by joshmgross** [comment]
That makes sense @IanButterworth, thanks for sharing your perspective.

I'd recommend testing changes locally or within workflows on a fork to validate them - that's going to be a much faster feedback loop than waiting on someone to approve runs on a pull request.

We cannot disable that setting at this time, it's necessary to prevent abusive actors from running arbitrary workflows on our repositories.

**Comment by joshmgross** [comment]
I was made of aware of #1325 on Thursday and reviewed it then asking for another test case. I'm still following up internally to see if there's a better option than the hard-coded output that's mixed in with user-provided outputs from all existing steps.

As for the current status of this action and what we can do to improve here from a community perspective, I'm still working on that internally and don't have anything more to share at this time.

**Comment by IanButterworth** [comment]
I do appreciate your efforts. Thanks

**Comment by nebuk89** [comment]
Sorry for the quietness on this, and our other Actions! We are looking at how we better support our Actions across the board at the moment as we have been quiet on a bunch of them. 

On cache in particular, we are working on the cache itself at the moment so we can get a cache >10gb. We hope to have a beta of that (probably private beta but we will see) by the end of the year :)

**Comment by IanButterworth** [comment]
Please disable stale bot on this repo. The rate of maintenance attention is slower than the stale bot cycle. It's illogical to use it here.

**Comment by joshmgross** [comment]
I've disabled our stale workflow for n ow - https://github.com/actions/cache/actions/workflows/close-inactive-issues.yml

**Comment by IanButterworth** [comment]
@joshmgross with https://github.blog/changelog/2024-09-16-notice-of-upcoming-deprecations-and-changes-in-github-actions-services/ will this action get better attention? Like updating to node20 which has lingered since Februrary https://github.com/actions/cache/pull/1326

**Comment by joshmgross** [comment]
> Like updating to node20 which has lingered since February [#1326](https://github.com/actions/cache/pull/1326)

This action has supported Node 20 since January https://github.com/actions/cache/releases/tag/v4.0.0

#1326 is a development-only change.

**Comment by IanButterworth** [comment]
Thanks @joshmgross I don't think this needs to be open any longer
