### ISSUE TITLE
Cache hit occurred on the primary key, not saving cache

### ISSUE THREAD

**Issue by nuhkoca** [actions/cache#142]
Hello,

As it seems, our workflow is able to restore cache build based on a key we specified.

`Cache restored from key: gradle-macOS-checksum }}`

However, it is giving warning below in **Post actions/cache@v1**. Can you please inform me that what does it mean exactly? Thanks.

`Cache hit occurred on the primary key gradle-macOS-checksum }}, not saving cache.`

**Comment by dhadka** [comment]
Hi, if there is a cache hit on the key, then there is no need to re-upload the cache.  The only exception to this is if you use a restore_key (prefix matching), where we will create a new cache.  The warning is just indicating that it's skipping the cache upload since it already exists.

**Comment by nuhkoca** [comment]
Hi @dhadka thanks for answering! It is now clear. I am closing this issue as it is already working as expected.
