### ISSUE TITLE
Extremely slow Post Setup steps for actions/cache@v3

### ISSUE THREAD

**Issue by arthurhobspice** [actions/cache#1442]
I use actions/cache@v3 in a pre-commit check workflow on self-hosted runners (summerwind/actions-runner image).

Intermittently (e.g. yesterday and today) the Post Setup steps are extremely slow. Each step takes 2 min 12 sec (plusminus 1 sec).

Looking at the logs and a pcap network trace I observe that the packages (several MiB) are transferred in a few seconds max, but then the connection to GitHub hangs until it probably hits a timeout. Remote IP address for each TCP stream is 20.246.192.124 (Microsoft).

Maybe related to https://github.com/actions/cache/issues/720?

Excerpt from workflow log:

![image](https://github.com/user-attachments/assets/965ff196-52f8-4a49-a413-4e48bef7f7a9)

(The five lines in each step are presented quickly, and then the workflow hangs for the two minutes.)

**Comment by wille** [comment]
Seeing the same

**Comment by dmelikhov** [comment]
This is a known bug in Node 20:
https://github.com/nodejs/node/issues/47228

Please see related issues for possible workarounds:
https://github.com/actions/setup-node/issues/878
https://github.com/ruby/setup-ruby/issues/543

**Comment by arthurhobspice** [comment]
Using `actions/checkout@v3` and `actions/cache@v4` this issue goes away. Can be closed.
