### ISSUE TITLE
Do we need to specify an exact version?

### ISSUE THREAD

**Issue by t27duck** [actions/cache#145]
Admittedly, this question is more generic with actions in the market place in general than specific to this action.

The current release of this action is v1.1.0. All examples and documentation say to use `actions/cache@v1` in our configuration file. I have not been able to find any documentation on Github on how version resolution works for actions. 

So my question is, does `actions/cache@v1` mean "Use the latest 1.x" or "Specifically use 1.0.0"?

**Comment by dhadka** [comment]
`actions/cache@v1` points to the latest 1.x version.

There isn't any standard for versioning as far as I know.  For this action, we update the `v1` tag to point to the latest `v1.x.x` version after each release.

**Comment by t27duck** [comment]
Thank you!
