### ISSUE TITLE
Interaction with bors

### ISSUE THREAD

**Issue by MikailBag** [actions/cache#146]
It seems that bors-ng + actions/cache = problems.

# Problem
[Bors-ng](https://github.com/bors-ng/bors-ng) is a merge bot. When pull request is approved, it merges PR head into special `staging` branch and waits for CI status. If build is green, bors fast-forwards `master` up to `staging`. It means that there will be no workflow execution for master branch, because commit is already 'used' (when it was on `staging`). So, no caches for `master` will be created (They will be created on `staging`, but such objects are invisible to other branched).

I will be very glad if I am mistaken and in fact caching works just fine with bors.
Otherwise, I'd like to listen for some advice.

**Comment by joshmgross** [comment]
Hey @MikailBag, you're correct that a cache created for `staging` won't be accessible by PRs (which only read caches from the PR merge branch and the default branch/`master`).

> It means that there will be no workflow execution for master branch, because commit is already 'used`

If you have a `push` trigger in your workflow for changes to `master`, I would hope that you would still get a build on `master` after that `fast-forward`

I haven't used any merge bots, but if you want caching for PR builds, you need a build on your default branch.

**Comment by MikailBag** [comment]
Thanks for clarification.
It turns out that caching works fine!
