### ISSUE TITLE
Cache fails when using actions/cache@v1.1.0 on Windows-2016

### ISSUE THREAD

**Issue by wangsongc** [actions/cache#153]
Cache fails when using actions/cache@v1.1.0 on Windows-2016, and using actions/cache@v1.0.3 is work
https://github.com/wangsongc/Hellow-World/runs/390647603
```
Post job cleanup.
"C:\Program Files\Git\usr\bin\tar.exe" -cz -f D:\a\_temp\3e1a7faf-0d91-4c9d-9dff-dd5cb2f54509\cache.tgz -C D:\a\Hellow-World\Hellow-World .
tar (child): Cannot connect to D: resolve failed
/usr/bin/tar: Child returned status 128
/usr/bin/tar: Error is not recoverable: exiting now
[warning]Tar failed with error: The process 'C:\Program Files\Git\usr\bin\tar.exe' failed with exit code 2. Ensure BSD tar is installed and on the PATH.
```

**Comment by joshmgross** [comment]
@wangsongc Thank's for reporting this, this was caused https://github.com/actions/cache/pull/126

For a workaround, I'd recommend using v1.0.3.

Note: Windows 2016 will be deprecated soon (see https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners#windows-server-2016),

**Comment by qaisjp** [comment]
i get this as well.

**step**

```yaml
      - uses: actions/cache@v1
        id: cache-dxfiles
        with:
          path: utils/DXFiles
          key: dxfiles-0001
```

**full workflow**  
https://github.com/multitheftauto/mtasa-blue/blob/275eae917eb0f39abd69f7e0133ffed02f318335/.github/workflows/build.yaml#L15-L19

**error message in Post actions/cache@v1**  
```
Post job cleanup.
"C:\Program Files\Git\usr\bin\tar.exe" -cz -f d:\a\_temp\8f05a114-911c-4bbb-90e7-367cad3a2601\cache.tgz -C d:\a\mtasa-blue\mtasa-blue\utils\DXFiles .
tar (child): Cannot connect to d: resolve failed
/usr/bin/tar: d\:\\a\\_temp\\8f05a114-911c-4bbb-90e7-367cad3a2601\\cache.tgz: Cannot write: Broken pipe
/usr/bin/tar: Child returned status 128
/usr/bin/tar: Error is not recoverable: exiting now
[warning]Tar failed with error: The process 'C:\Program Files\Git\usr\bin\tar.exe' failed with exit code 2. Ensure BSD tar is installed and on the PATH.
```

**link**  
https://github.com/multitheftauto/mtasa-blue/pull/1266/checks?check_run_id=478205579
