### ISSUE TITLE
SqlException  when restoring cache

### ISSUE THREAD

**Issue by anthonator** [actions/cache#157]
We're seeing the following error when restoring a cache.

```
[warning]﻿{"$id":"1","innerException":null,"message":"TF246021: An error occurred while processing your request.\r\nTechnical information (for administrator):\r\nSQL Server Error: 4011","typeName":"System.Data.SqlClient.SqlException, System.Data.SqlClient","typeKey":"SqlException","errorCode":0,"eventId":0}
```

**Comment by anthonator** [comment]
This caused one workflow run to fail but another workflow run logged this as a warning to the `Run actions/cache@v1` step.

**Comment by dhadka** [comment]
@anthonator This should be fixed now.  Can you please confirm?  Thanks!

**Comment by anthonator** [comment]
I think so? The behavior was inconsistent so I'm not sure. I'll monitor it over the next day or two and report back.

**Comment by dhadka** [comment]
Closing since we're not seeing this error anymore in our telemetry.  Please re-open if this reoccurs.
