### ISSUE TITLE
Store on Push Only Option (only restore with pull requests)

### ISSUE THREAD

**Issue by n1hility** [actions/cache#160]
In order to conserve storage  under the  super small 2GB quote, it would be useful to model a workflow where caches are only stored for the target branch vs every single PR against it. In this way a workflow can store on push, which happens after every merge, and then you avoid pull requests (less useful due to their isolation) from competing for storage with the branch's cache, and the eviction algorithm picking the less efficient target.

I propose adding a parameter to skip pull request events.

**Comment by dhadka** [comment]
While there are certainly usage patterns that would cause problems with the current 2 GB quote, there are some design features that should help:

1. We don't save the cache if there's a cache hit on the exact key.  So ideally the cache (key) gets into the target or master branch, which lets all PRs use that cache and avoid unnecessary duplication.

2. Eviction runs once a day and will evict the least recently used caches first.  We're not evicting as soon as a repo exceeds the 2 GB limit.  Thus, ideally the caches created by pushes are used more frequently and eviction will target the less frequently used PR caches.

**Comment by dhadka** [comment]
@n1hility Also good news - we are increasing the storage limit to 5 GBs.  The limit will be increased on the backend by EOD tomorrow and we can also increase the [individual file limit](https://github.com/actions/cache/blob/e43776276fc1bf0f5f1b462661f341691905b2df/src/save.ts#L59) afterwards.
