### ISSUE TITLE
Enable caching of dependencies even if builds fail with post-if modifier.

### ISSUE THREAD

**Issue by patrickt** [actions/cache#165]
In the process of trying to make `semantic` play nicely with Actions caching, we tried to implement https://github.com/github/semantic/pull/450, as per @joshmgross’s suggestion. Unfortunately, we ran into an issue with the `post-if` modifier; @joshmgross suggested filing an issue. We’d love to see support for this, as we’re missing out on a ton of opportunities to keep the cache warm.

**Comment by pat-s** [comment]
Have you seen #92?
