### ISSUE TITLE
Gzip is slow

### ISSUE THREAD

**Issue by tkaitchuck** [actions/cache#167]
This also relates to: https://github.com/actions/cache/issues/161

The code is currently running:
https://github.com/actions/cache/blob/3854a40aee6b66135b974c5a63118c69b6c0d2d0/src/tar.ts#L45

For jobs as oart of gethub actions this takes 30sec for 500mb of data. If I change this to:
```
["--lzop", "-cf", archivePath, "-C", sourceDirectory, "."];
```
It brings this time down to 3sec. (Obviously with not as good of a compression ratio). For many repos I suspect this would be preferable.

**Comment by imbsky** [comment]
We already have plans to speed up by using zstd.

**Comment by imbsky** [comment]
See https://github.com/actions/cache/issues/184

**Comment by joshmgross** [comment]
Thanks @tkaitchuck and @imbsky 

We're hoping to get zstd added to the hosted images so that we can use it for this action. Until then gzip is the option that provides the most compatibility.

https://github.com/actions/cache/issues/184 will track replacing gzip
