### ISSUE TITLE
Use the cache action in another action

### ISSUE THREAD

**Issue by thisismydesign** [actions/cache#172]
I have a use case where I repeatedly use cache the same way. I want to create an action to wrap this functionality. I'd like an API to be able to call the cache action, such as:

```
const cache = require('cache');

await cache.restore(path, key);
await cache.save(path, key);
```

What I tried so far:

I can require the action, however, the parameters are taken from the parent action, also [the code runs async upon require](https://github.com/actions/cache/blob/23e301d35cb55b348f1f4524e353b1fc29567e5f/src/restore.ts#L112).

`package.json`
```
"dependencies": {
  "cache": "github:actions/cache#v1.1.0"
},
```

`index.js`
```js
const restore = require('cache/dist/restore').default;
// runs restore async, could not await
const save = require('cache/dist/save').default;
// runs save async, could not await (this actually finishes before restore with "Error retrieving key from state."
```

See aslo:
- https://stackoverflow.com/questions/58860769/call-a-github-action-from-another-github-action
- https://stackoverflow.com/questions/58611841/how-can-i-reference-other-actions-from-my-github-actions-action-yml-file

**Comment by Cyberbeni** [comment]
duplicate of #55

**Comment by thisismydesign** [comment]
You're right, my bad
