### ISSUE TITLE
Cache download can hang forever when fetched from multiple concurrent jobs

### ISSUE THREAD

**Issue by jcornaz** [actions/cache#189]
Hi, since a setup of multiple concurrent jobs that might fetch the same cache, we notice that it hangs from time to time (not always, it is a bit random, but definitely recurrent as we observed it 3 times already in only few days)

Here is a screenshot of a successful fetch:

![image](https://user-images.githubusercontent.com/2535178/74539842-042fd900-4f3f-11ea-85ce-2532910e49ce.png)

And here a screenshot of another job that was running concurrently (using strategy matrix) and the fetch hanged forever (reaching our job timeout of 10 minutes)

![image](https://user-images.githubusercontent.com/2535178/74540239-b5cf0a00-4f3f-11ea-88b7-80a182c46e04.png)

Please notice that the cache key is exactly the same. So it looks like it happens when concurrent jobs try to fetch the same cache.

**Comment by jcornaz** [comment]
Any news?

This problem is costly for us.

Eventually, could you allow setup a timeout for the cache step in order to mitigate the damages?

**Comment by dhadka** [comment]
Hi @jcornaz, thanks for reporting this.  What is the org and repo name?  If you do not want to post it publicly here, please e-mail me at dhadka (at) github (dot) com.  Thank you!
