### ISSUE TITLE
Cache seems to be corrupted after a failure in a prior job

### ISSUE THREAD

**Issue by liamnichols** [actions/cache#191]
Hey, sorry if the description isn't clear however I ran into quite an obscure issue where the post job caching step was actually failing (as a warning):

> /usr/bin/tar -cz -f /Users/runner/runners/2.164.0/work/_temp/1f21752b-9b58-4912-b451-1d9e1147440f/cache.tgz -C /Users/runner/runners/2.164.0/work/project-name/project-name/vendor/bundle .
> tar: could not chdir to '/Users/runner/runners/2.164.0/work/project-name/project-name/vendor/bundle'

Now it turns out, the failure was simply because I was accidentally trying to cache the wrong directory (bunder/bundle) however I then started facing issues with the subsequent runs of this workflow. 

As expected, in the next job when reading from the cache I was getting the following:

> Cache not found for input keys: macOS-bundler-4b38de18f67a80fd8ada910f87efd1bb48eabe26d71b83015517861f48c3cccc, macOS-bundler-.

I'm assuming this is the case because the last run did not actually write anything. However, in the post job step, I then get the following: 

> [warning]Cache already exists. Scope: refs/pull/8838/merge, Key: macOS-bundler-4b38de18f67a80fd8ada910f87efd1bb48eabe26d71b83015517861f48c3cccc, Version: (null)

This seems to contradict the initial check in the run, since apparently (as expected) there was nothing cached however there seems that _something_ was written when I got the initial failure as it's preventing the cache from being correctly written once the issue was corrected.

If the above wasn't clear enough, here are some screenshots that might help:

### Run 1 (I was trying to cache but the directory didn't exist):

<img width="1064" alt="Screenshot 2020-02-17 at 09 15 59" src="https://user-images.githubusercontent.com/482871/74639624-1f306200-5166-11ea-9261-54a621450f1a.png">

### Run 2 (I fixed the steps to ensure the directory existed):

<img width="1070" alt="Screenshot 2020-02-17 at 09 15 06" src="https://user-images.githubusercontent.com/482871/74639550-ff00a300-5165-11ea-944c-03a0d33df953.png">

---

To resolve the issue, I had to be 100% sure that my workflow was setup correctly and that the directory existed before I then added the caching step back in using a different key to identify it however I have a feeling that if the original error was handled correctly, it would have just started working once I corrected the fault without me having to change the key.

Thanks!

**Comment by kadler** [comment]
I just ran in to this as well. I didn't RTFM well enough and tried to cache a single file and instead of a directory. Regardless, tar failed to cache anything but the corrupt cache keeps getting re-used.

**Comment by GPSnoopy** [comment]
Same problem here. This is really flakey. If the cache upload fails (e.g. tar fails due to the many network issue, see #267) then the cache is left in an inconsistent state where:
- Get-cache fails (key not found)
- Put-cache fails (key already present).

IMHO this is a rather critical invariant being violated here. Put-cache should be a no-op in case of failure. I'm surprised such an important issue is still open after 2 months.
