### ISSUE TITLE
Cache for tags should be stored in default branch's scope

### ISSUE THREAD

**Issue by shivammathur** [actions/cache#194]
Cache does not work for tag workflows as each tags is a different ref.

A workaround for this is creating a similar workflow on default branch which saves the cache, which then is available for tag workflows.

But this workaround is contrived and cache should work on tags. If cache in tags workflows is stored in default branch's scope it would solve the issue.

I'm not sure but this might also be solved if #183 is resolved.

**Comment by joshmgross** [comment]
What's your workflow? Are you only building on tags so there's no cache for other branches?

**Comment by shivammathur** [comment]
Yes, right now I would have to build on both master and tag releases to cache the requirements, it would be nice to test on master and build on tag releases.

**Comment by sjackman** [comment]
Somewhat related, once a pull request is merged, it'd be nice if that cache was promoted up from the pull request branch to the base branch. Right now I'm rebuilding that same cache on `master` once the PR is merged.
