### ISSUE TITLE
Caching Pipenv dependencies - pipenv command not recognised

### ISSUE THREAD

**Issue by ChristianBell1995** [actions/cache#197]
`jobs:
  steps:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v1
        with:
          path: ~/.cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/Pipfile.lock') }}
      - name: Cache virtualenv
        id: cache-virtualenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-venv-${{ hashFiles('**/Pipfile.lock') }}
      - uses: actions/setup-python@v1
        if: steps.cache-dependencies.outputs.cache-hit != 'true' || steps.cache-virtualenv.outputs.cache-hit != 'true'
        with:
          python-version: '3.7'
      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true' || steps.cache-virtualenv.outputs.cache-hit != 'true'
        run: |
          pip install pipenv
          pipenv install --dev
      - name: Lint
        run: |
          pipenv --help
          pipenv run fab check`

I have been having some issues trying to cache pipenv dependencies. Tried to follow [https://github.com/actions/cache/issues/152](this) strategy but with no luck.

Even when running the `pipenv --help` I get a: 
pipenv: command not found...

**Comment by dhadka** [comment]
I'm not familiar with how `pipenv` installations work, but is your intention that it is included in the cache?  If so, there's likely some configuration being done by `pip install pipenv` or `setup-python`, such as updating the `PATH` env var, that isn't being done by the cache.

**Comment by ChristianBell1995** [comment]
@dhadka You were right! Needed to install python and pipenv outside of the caching steps and then it worked! Final code is:

`
runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'

      - name: Install Pipenv
        run: sudo pip install pipenv
      # This one caches both pip and pipenv downloads
      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v1
        with:
          path: ~/.cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/Pipfile.lock') }}

      # This will cache the whole virtualenv with built dependencies (and a lot more, though)
      - name: Cache virtualenv
        id: cache-virtualenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-venv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true' || steps.cache-virtualenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --dev
      - name: Lint
        run: |
          pipenv --help
          pipenv run fab check
`

**Comment by dhadka** [comment]
Awesome!  Closing this issue.
