### ISSUE TITLE
Publication of API documentation

### ISSUE THREAD

**Issue by ad-m** [actions/cache#22]
According comment by @joshmgross ```actions/cache``` use undocumented API ( https://github.com/actions/cache/commit/37c45447e4220b80ffd0f1b418c35f1a1808d204#r35753492 ). I create that issue to track success in that area.

**Comment by chrispat** [comment]
That API surface is not part of GitHub it is part of the actions runtime and we reserve the right to change it if necessary.  We do not plan to document it for general consumption.

**Comment by ad-m** [comment]
So how user can effectively implement own cache mechanism, which will be more effective, e.g. as part of the dependency installation step for specific language? Some users have already proposed that "npm build" and cache could be one action, which - in my opinion - can be quite effective.

How are changes planned in this API planned when users specify the exact release of the actions they intend to use? Unless versioning is planned and the behavior of the action may change at any time?
