### ISSUE TITLE
Post cache can hang forever.

### ISSUE THREAD

**Issue by Kesanov** [actions/cache#227]
Our post cache action takes between 2 - 4 minutes (the cached resource has around 1GB), but sometimes doesn't finish at all.

This completely defeats the purpose of caching, because the CI job isn't marked as completed until **all** steps are completed **(including post cache step)**. 

What I would expect to see:
- If all steps but post cache step successfully completed, the whole CI is marked as completed. At that point, even if the caching mechanism fails, the CI test should be treated as successful anyway, and you should not be forced to wait for it to finish (in case when successful CI is required for merging PR).
- Some reasonable time limit on post cache action. There is something wrong with the cache mechanism, if it takes more than 10 minutes, so there is no point waiting.

**Comment by D4nte** [comment]
I think I am encountering a ]similar issue](https://github.com/comit-network/comit-rs/runs/603537340) (please let me know if you prefer a new issue) where the post cache fails after 34 minutes run.

**Comment by wilsonhipolito** [comment]
I'm facing the same problem. We have a cache of around 1GB and the post cache is hanging and failing the job. There are no logs and we can't even cancel the workflow when it hangs, we need to wait for the time-out.
