### ISSUE TITLE
Confusing docs on cache GitHub Actions and requirement on path locations

### ISSUE THREAD

**Issue by traversaro** [actions/cache#229]
According to https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows, the directory pointed by the `path` argument of this GitHub Action **must** be located inside of the GITHUB_WORKSPACE directory.

However, in the examples ( https://github.com/actions/cache/blob/master/examples.md#go---modules ) there are a lot of cases in which the `path` points to directories that are not in the GITHUB_WORKSPACE directory, for example for go the path argument is `~/go/pkg/mod`, so this two pieces of information seems to be conflicting .

**Comment by joshmgross** [comment]
👋 Thanks for bringing this up @traversaro, those docs are incorrect. There is no requirement for the path to be in the GitHub Workspace. I'll get those docs fixed.

**Comment by joshmgross** [comment]
The docs have been updated, thanks for reporting this!

**Comment by traversaro** [comment]
Thanks a lot @joshmgross for the quick feedback.
