### ISSUE TITLE
The event type repository_dispatch is not supported

### ISSUE THREAD

**Issue by riprasad** [actions/cache#230]
Caching doesn't work when my workflow gets triggered by 'repository_dispatch' event. It gives the below warning:-
[warning]Event Validation Error: The event type repository_dispatch is not supported. Only push, pull_request events are supported at this time.

**Comment by clxmstaab** [comment]
I am running into the same problem when using https://github.com/peter-evans/slash-command-dispatch

**Comment by joshmgross** [comment]
Currently only `push` and `pull_request` events are supported for caching, see https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache

We're tracking supporting more events with https://github.com/actions/cache/issues/63
