### ISSUE TITLE
Interaction with Self-Hosted Runners

### ISSUE THREAD

**Issue by stevenpall** [actions/cache#232]
Hello,

I've been trying to determine how this action works when run on a self-hosted runner. From what I can see in my testing, it appears to just save the cached files locally (on that runner), e.g.
```
Run actions/cache@v1
Cache Size: ~0 MB (120990 B)
/usr/bin/tar -xz -f /_work/_temp/2196d46d-64ba-40b0-96d2-12805e2d0c14/cache.tgz -C /_work/test/.test
Cache restored from key: Linux-test
```
If this is the case it's somewhat problematic if you have multiple runners set up as you'll only get a cache hit every `1/<number of runners>` times. Maybe I'm not fully understanding how this works though? Any clarification would be appreciated!

**Comment by joshmgross** [comment]
👋 Hey @stevenpall, I would expect caching to work fine on self-hosted runners. 

>From what I can see in my testing, it appears to just save the cached files locally

The cached files are pulled from the backend caching service as a tar archive and then extracted from that temp location to your specified path.
So in your example:
`/usr/bin/tar -xz -f /_work/_temp/2196d46d-64ba-40b0-96d2-12805e2d0c14/cache.tgz -C /_work/test/.test`

The file `/_work/_temp/2196d46d-64ba-40b0-96d2-12805e2d0c14/cache.tgz` was downloaded from the cache service based on the given key (`Linux-test`).

When creating a new cache, a new tar archive is created and uploaded to the cache service.

If you [Enable Step Debug Logging](https://help.github.com/en/actions/configuring-and-managing-workflows/managing-a-workflow-run#enabling-step-debug-logging) you can see more info about what the cache action is doing.

**Comment by jonathanong** [comment]
> From what I can see in my testing, it appears to just save the cached files locally

is this true? I'm experiencing https://github.com/actions/cache/issues/259 from only self-hosted runners.

**Comment by stevenpall** [comment]
@jonathanong No, my initial assumption was incorrect; see @joshmgross's explanation above.
