### ISSUE TITLE
Post job cleanup: Permission Denied

### ISSUE THREAD

**Issue by Zeyuzhao** [actions/cache#238]
I am currently trying to setup `actions/cache` with a bundle installer for gh-pages I forked (`jekyll-deploy-gh-pages`). It seems that when actions/cache is trying to clean up, there is a permissions denied error. Is it possible to elevate the cleanup process so it has the permissions? Thanks!

![image](https://user-images.githubusercontent.com/6325738/78073189-68cbb980-736e-11ea-83aa-2976a636fe89.png)

`Post job cleanup.
/bin/tar -cz -f /home/runner/work/_temp/b418cf62-a262-45a3-b8d1-14d2a056b95f/cache.tgz -C /home/runner/work/personal/personal/vendor/bundle .
/bin/tar: ./ruby/2.7.0/gems/nokogumbo-2.0.2/ext/nokogumbo/ports/archives/libxml2-2.9.10.tar.gz: Cannot open: Permission denied
/bin/tar: Exiting with failure status due to previous errors
[warning]Tar failed with error: The process '/bin/tar' failed with exit code 2`

**Comment by joshmgross** [comment]
👋 Hey @Zeyuzhao, we're tracking this issue with https://github.com/actions/cache/issues/133

It's likely that one of the files that you're caching isn't readable by `tar`. The above issue might have some workarounds, and we're working on elevating the `tar` process to allow caching files not readable by the current user.
