### ISSUE TITLE
Cache fails for re-run jobs

### ISSUE THREAD

**Issue by KhaledSakr** [actions/cache#240]
Whenever a job is re-run the cache fails with the following warnings:
```
Run actions/cache@v1.0.3
[warning]No scopes with read permission were found on the request.
```
That also happens with post cache cleanups:
```
Post job cleanup.
/bin/tar -cz -f /home/runner/work/_temp/***/cache.tgz -C /home/runner/work/*** .
[warning]No scopes with write permission were found on the request.
```

**Comment by joshmgross** [comment]
@KhaledSakr Are these re-runs of pull requests?

**Comment by KhaledSakr** [comment]
Yes. I haven't tried with other events so I'm not sure if it also happens for other re-runs.

**Comment by joshmgross** [comment]
We're tracking this issue with https://github.com/actions/cache/issues/208. It's caused by the GitHub ref on the re-run changing, see https://github.community/t5/GitHub-Actions/GITHUB-REF-is-inconsistent/td-p/48129
