### ISSUE TITLE
Fix release tag v1 to point to the latest v1.x release

### ISSUE THREAD

**Issue by koppor** [actions/cache#241]
I thought, that `v1` always points to the latest `v1` release. This is not the case:

![grafik](https://user-images.githubusercontent.com/1366654/78245092-1e217d00-74e7-11ea-8462-692763372411.png)

Would it be possible to fix that? Otherwise, it would be good to have an explanantion to which release the `v1` points. When a user should use `v1` (as indicated in `README.md`) and then to use the "latest" v1.x tag.

**Comment by joshmgross** [comment]
Thanks for reporting this @koppor, this was a mistake on my part. The intention is that `v1` is always the latest release.

**Comment by joshmgross** [comment]
This is now fixed: 
![image](https://user-images.githubusercontent.com/16631042/78264049-b2ccb080-74d0-11ea-8b48-7e7089ab614d.png)

Note the only difference between `v1.1.1` and `v1.1.2` was a rename to the `action.yml` file to fix a marketplace link. The action itself had no differences. 
See https://github.com/actions/cache/releases/tag/v1.1.2
