### ISSUE TITLE
Sbt / coursier example

### ISSUE THREAD

**Issue by giarc3** [actions/cache#243]
As #134 mentions, the current Scala example only works for 
> SBT < 1.3 (with Ivy), or SBT 1.3+ with Coursier disabled (which will fallback to Ivy)

The reason for this was because the cache size was too small for Coursier. Now that the size has increased, it would be good to include an example that uses Coursier.

**Comment by francisdb** [comment]
the relevant docs are here:
https://get-coursier.io/docs/cache.html#location
