### ISSUE TITLE
cache doesn't fail when it fails

### ISSUE THREAD

**Issue by boredland** [actions/cache#247]
This cache module is giving me a very hard time and I am honestly thinking, mostly because of the sub par cache support and speed in GH Actions, that we wont stay here for much longer.
That being said: we lost a lot of built-minutes (and therefore money) in the past month because of mainly two already recognized problems:

1. sth like `[warning]connect ETIMEDOUT 13.107.42.16:443` https://github.com/actions/cache/issues/141

2. `[warning]No scopes with read permission were found on the request.` https://github.com/actions/cache/issues/208

Both do not let the steps fail, therefore our jobs continued and failed much later. While this is super annoying and expensive, I'm really wondering if you couldn't at least implement a quick fix for this to fail, so we don't pay so much money for errors that were thrown as warnings.

**Comment by dhadka** [comment]
@boredland I think a quick fix is to change [line 107 in restore.ts](https://github.com/actions/cache/blob/f60097cd16988b176c31ed5e2db51d50a8d19a4e/src/restore.ts#L107) from

```
utils.logWarning(error.message);
```

to

```
core.setFailed(error.message);
```

Would you be able to share your workflow file?  If the cache is failing to restore, you should be able to [conditionally run a step](https://github.com/actions/cache#skipping-steps-based-on-cache-hit) to recreate whatever was put into the cache:

```
  - name: Restore content after cache miss
    if: steps.cache.outputs.cache-hit != 'true'
    run: ...
```

Depending on what you're storing, you could also consider using [workflow artifacts](https://help.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts).  Workflow artifacts are designed for data you want persisted longer and must be retained, whereas the cache is best effort and caches can be evicted at any time.

**Comment by boredland** [comment]
Hi! Thanks for looking into this. The workaround with a subsequent step that fails when there is no cache hit, I already added. 
Regarding workflow artifacts:
In fact I am using the cache as an artifact, mainly because of its ability to save across multiple paths. We are inside a lerna monorepo. Some packages need to be built as dependency for others. Caching them saves me some precious build-minutes.
