### ISSUE TITLE
Cache read and writes failing because of permissions issues

### ISSUE THREAD

**Issue by kevinrobinson** [actions/cache#251]
hello!  I'm splitting this out from https://github.com/actions/cache/issues/207#issuecomment-609876788 and https://github.com/actions/cache/issues/207#issuecomment-611195237, since it seems this might be a separate issue.

For the last few minutes, I'm seeing all cache reads fail with ([example](https://github.com/studentinsights/studentinsights/pull/2806/checks?check_run_id=572078074#step:6:87)):
> [warning]No scopes with read permission were found on the request.

And all cache writes fail with ([example](https://github.com/studentinsights/studentinsights/pull/2806/checks?check_run_id=572078074#step:24:81)):
> [warning]No scopes with write permission were found on the request.

I can't see more about why this would be happening, and have debug logs enabled.

**Comment by dhadka** [comment]
Hey @kevinrobinson, any chance you re-ran those tests?  There's a known issue where re-runs don't have the scopes.  See this issue for more details: https://github.com/actions/cache/issues/208#issuecomment-607877125

**Comment by kevinrobinson** [comment]
@dhadka probably!  I don't remember exactly, and don't know of a way to tell from the UI.  I'll close this then and follow along over there, thanks :)

FWIW, the onboarding developer experience with GitHub Actions was awesome, but week #2 has been pretty tough :\  I ran into severe latency problems in cache reads (https://github.com/actions/cache/issues/207#issuecomment-611195237), and so tried to work around by retrying jobs but ran into the permissions problems in this issue.  If I follow, it turns out caching doesn't work when retrying jobs at all (https://github.com/actions/cache/issues/208), and has been an issue for over a month, but there's no timeline for a fix because it's dependent on changing other internal systems first.

If there's ways to help from the outside, or provide more info for debugging or validating fixes, please let me know!
