### ISSUE TITLE
Lerna caching not working

### ISSUE THREAD

**Issue by Sytten** [actions/cache#261]
We use the new multipath caching but I realized that it is always skipped. I have seen two behaviours:
1. Same caching key, but says that it does not exist
2. Warning with `No scopes with read permission were found on the request`

We are using master.
No sure what is the issue, but let me know if I can help debug.

**Comment by Sytten** [comment]
Number 2 seems to be related to https://github.com/actions/cache/issues/208#issuecomment-596664572

**Comment by joshmgross** [comment]
👋  Hey @Sytten are you still having issues?

If so, could you provide your workflow file?

**Comment by Sytten** [comment]
I think its fine now, will reopen if I have other issues
