### ISSUE TITLE
Upload fails with no space left on the device

### ISSUE THREAD

**Issue by wokalski** [actions/cache#264]
I have been using actions/cache in my repo to cache build artifacts. It worked flawlessly but yesterday I wanted to optimize one small part of the installation process and start caching a bit more data. Unfortunately, introducing the cache for another folder caused the whole cache to break down. I reverted the cache setup to exactly the same one that used to work before and I get this output (with GitHub action debugging secret set to true):

```
##[debug]Find 1 files to hash.
##[debug]STDOUT/STDERR stream read finished.
##[debug]Finished process 78553 with exit code 0, and elapsed time 00:00:00.8541828.
##[debug]..=> '8419bbbf735c4f41074f7b474603f2ca9cd5e7308529c82de9b43fb354d15a58'
##[debug]=> 'esy-install-8419bbbf735c4f41074f7b474603f2ca9cd5e7308529c82de9b43fb354d15a58'
##[debug]Result: 'esy-install-8419bbbf735c4f41074f7b474603f2ca9cd5e7308529c82de9b43fb354d15a58'
##[debug]Loading env
Post job cleanup.
##[debug]State: 
##[debug]Reserving Cache
##[debug]Resource Url: https://artifactcache.actions.githubusercontent.com/fVlj4KbsdmOXDqXz16CUrFVF2wTMeijmXBnMLBd0tuKXq8t4Ft/_apis/artifactcache/caches
##[debug]Cache ID: 22
##[debug]Cache Path: /home/runner/.esy/3___________________________________________________________________/i
##[debug]Archive Path: /home/runner/work/_temp/6f7b2941-7853-4bf4-ade7-e0a5c2d1a21f/cache.tgz
/bin/tar -cz -f /home/runner/work/_temp/6f7b2941-7853-4bf4-ade7-e0a5c2d1a21f/cache.tgz -C /home/runner/.esy/3___________________________________________________________________/i .
gzip: stdout: No space left on device
/bin/tar: /home/runner/work/_temp/6f7b2941-7853-4bf4-ade7-e0a5c2d1a21f/cache.tgz: Wrote only 4096 of 10240 bytes
/bin/tar: Child returned status 1
/bin/tar: Error is not recoverable: exiting now
[warning]Tar failed with error: The process '/bin/tar' failed with exit code 2
##[debug]Node Action run completed with exit code 0
##[debug]Finishing: Post ~/.esy/3_/i cache
```

As I said, exactly the same cache used to work. I haven't changed any code or dependencies in my project in between.

On the next action run when the computed cache `key` is the same, post outputs this:

```
[warning]Cache already exists. Scope: refs/pull/9/merge, Key: esy-install-8419bbbf735c4f41074f7b474603f2ca9cd5e7308529c82de9b43fb354d15a58, Version: (null)
```

There's something majorly broken now and I don't know how to workaround it. I'll try to collect some info about the folder and run some more experiments but it's clearly an issue with this action. 

Thanks for reading up to this point and working on this subtle but extreme productivity enhancer 💪

**Comment by wokalski** [comment]
Here's the size of the directory I want to cache:

```
Run du -sh $ESY_I_FOLDER
1.9G	/home/runner/.esy/3___________________________________________________________________/I
```

**Comment by wokalski** [comment]
Running the tar command manually works. Here's the size of the tared dir size:

```
$ du -sh $ESY_I_FOLDER
1.9G	/home/runner/.esy/3___________________________________________________________________/I
$ tar -czf ~/cache.tgz -C $ESY_I_FOLDER .
$ du -sh ~/cache.tgz
591M	/home/runner/cache.tgz
```

The `tar` command is the one that fails in the action itself. Something's strange going on.

```
/bin/tar -cz -f /home/runner/work/_temp/6f7b2941-7853-4bf4-ade7-e0a5c2d1a21f/cache.tgz -C /home/runner/.esy/3___________________________________________________________________/i .
gzip: stdout: No space left on device
```

**Comment by wokalski** [comment]
I digged deeper and running the tar command manually *at the end* of my CI script fails. It seems like my runner is indeed running out of space.  Here's the size of the directories:

```
##[debug]Evaluating condition for step: 'Inspect .esy and project dir'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Inspect .esy and project dir
##[debug]Loading inputs
##[debug]Loading env
Run du -sh ~/.esy
##[debug]/bin/bash -e /home/runner/work/_temp/b66430cc-ce27-4f4f-8dc1-e72efde38315.sh
6.9G	/home/runner/.esy
33M	.
8.0G	/home/runner/
##[debug]Finishing: Inspect .esy and project dir
```

The log for the tar command cannot be viewed (GitHub Actions bug it seems).

**Comment by wokalski** [comment]
Maybe my runner is out of space? Here's `df -H` input if I run it right before the `Post` cache step:

```
df -H
Filesystem      Size  Used Avail Use% Mounted on
udev            3.7G     0  3.7G   0% /dev
tmpfs           729M  984k  728M   1% /run
/dev/sda1        90G   89G  300M 100% /
tmpfs           3.7G  8.2k  3.7G   1% /dev/shm
tmpfs           5.3M     0  5.3M   0% /run/lock
tmpfs           3.7G     0  3.7G   0% /sys/fs/cgroup
/dev/loop0       99M   99M     0 100% /snap/core/8935
/dev/loop1       42M   42M     0 100% /snap/hub/43
/dev/sda15      110M  3.8M  106M   4% /boot/efi
/dev/sdb1        15G   42M   14G   1% /mnt
```

**Comment by wokalski** [comment]
Closing. I have **NO IDEA** how it worked before but now the host is running out of space.

**Comment by dhadka** [comment]
@wokalski Thanks for reporting this.  Are you using restore keys?  If so, I would recommend deleting the cache.tgz file after restoring the cache to free up some space.  The following will work on ubuntu runners.  This assumes your cache step uses the id `cache`.

```
    - name: Delete cache tarball
      if: steps.cache.outputs.cache-hit == 'true'
      run: |
        find ~/work/_temp -name "cache.tgz" -exec rm -f {} \;
```

There is a [fix to always delete the cache file after restore](https://github.com/actions/cache/pull/209), but it's not part of any release yet.

The `cache does not exist` and `cache already exists` is a known issue that occurs when an error happens when saving the cache.  The cache action reserved that key for you (`##[debug]Reserving Cache`) but since creating the tar failed, the cache was never saved.  Hence, it's in a bad state.  We clean these bad states up once a day, but if you want to fix it faster, change the cache key (e.g., add `-v2-`).

**Comment by dhadka** [comment]
If deleting the cache file does not free up enough space, you can also try removing other unused files at the end of your workflow to free up additional space.  Hope this helps!

**Comment by wokalski** [comment]
@dhadka I have managed to work around my issue but it’s puzzling to me why the host runs out of space. It has only ~9 gigs of free space when I start the build. The documentation claims there should be 14. I confirm it’s not an issue with actions/cache. Only error handling could be improved but maybe it’s because of some bugs in gh actions themselves.

**Comment by wokalski** [comment]
I forgot to include this:

```
Filesystem      Size  Used Avail Use% Mounted on
udev            3.7G     0  3.7G   0% /dev
tmpfs           729M  984k  728M   1% /run
/dev/sda1        90G   81G  8.8G  91% /
tmpfs           3.7G  8.2k  3.7G   1% /dev/shm
tmpfs           5.3M     0  5.3M   0% /run/lock
tmpfs           3.7G     0  3.7G   0% /sys/fs/cgroup
/dev/loop0       42M   42M     0 100% /snap/hub/43
/dev/loop1       99M   99M     0 100% /snap/core/8935
/dev/sda15      110M  3.8M  106M   4% /boot/efi
/dev/sdb1        15G   42M   14G   1% /mnt
```

**Comment by wokalski** [comment]
In case anyone ends up here:
https://github.com/actions/virtual-environments/issues/709
