### ISSUE TITLE
Any way to force overwrite cache?

### ISSUE THREAD

**Issue by sfertman** [actions/cache#274]
In the process of developing one might create the wrong cache with the right key. I want to keep my right key but delete the wrong cache so that the next time the action runs, I get the correct files in my path. Problem is, whenever the cache key is hit, post-cache step just skips saving cache.

- Is there a way to do this? How?
- If not then perhaps there should be an option to force save on exist?

**Comment by dhadka** [comment]
@sfertman Currently, no, there is no way to overwrite a cache.  You could, for example, add a version number to the key, such as `${{ runner.os }}-v2-cache-${{ hashFiles(...) }}`.

**Comment by sfertman** [comment]
There are many tricks to "fixing" the hash of course (I add some semicolons in a comment for example) but this should preferably done in some sort of a formal way. Like an actual option in the cache or perhaps via autodetection of changes on the specified `path`. Wouldn't you agree?

**Comment by dhadka** [comment]
Yes, and autodetection of changes to the path will be included in `@v2` of this action.  This was introduced in the PR adding support for caching multiple paths (PR https://github.com/actions/cache/pull/212).

**Comment by sfertman** [comment]
I suppose I'll just wait for v2.
