### ISSUE TITLE
UX: send error when `path` points to a file

### ISSUE THREAD

**Issue by staabm** [actions/cache#277]
the docs mention that caching a single file with the `path` parameter is not supported.

https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows#input-parameters-for-the-cache-action

Should'nt the action send a error when `path` points to a file, to make the developer aware of this limitation?

I spend some time to find it out :)

**Comment by joshmgross** [comment]
Single file paths are now supported in `v2` of the Action, so this is no longer necessary.
