### ISSUE TITLE
Add some guidelines when to use caching

### ISSUE THREAD

**Issue by AlCalzone** [actions/cache#278]
I just tried out the cache action on a Node.js project of mine with this monster of a dependency list:
![grafik](https://user-images.githubusercontent.com/17641229/80383993-9a1fa280-88a4-11ea-9b73-e363f1f74e20.png)
I expected some gains in build time from caching, but to my surprise the build time went up, not down. The post cache step alone adds about 15s while there weren't actually any savings in the `npm ci` step.

This leads me to wonder why and under which circumstances one should cache the `~/.npm` dir at all.

**Comment by joshmgross** [comment]
👋 Hey @AlCalzone, the question of "When to use caching" is best answered by trying out caching to see if it works well for your specific use cases as it all depends on your workflows, repository, and environment.

Depending on your use-case with `npm`, you may see more improvements using `npm install` and caching `node_modules`.

**Comment by AlCalzone** [comment]
I tried out node_modules caching and found it is about as slow as .npm dir caching. Thanks anyways, but it looks like I'm not caching builds for now.
