### ISSUE TITLE
Gradle cache time macOS

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [actions/cache#280]
The time to generate / restore the Gradle cache on macos-latest is too high compared to ubuntu-latest.

It takes even less time without using cache.

**Comment by JavierSegoviaCordoba** [comment]
2000mb macOS, 220mb ubuntu

**Comment by joshmgross** [comment]
Thanks @JavierSegoviaCordoba!

The macOS images have some pre-cached packages that cause the cache folders to be extremely large. https://github.com/actions/virtual-environments/issues/427 is tracking getting those cleaned up.

For a workaround, you could look into changing your default cache directory or clear the cache before starting your build.
