### ISSUE TITLE
How to delete all caches?

### ISSUE THREAD

**Issue by philipperemy** [actions/cache#294]
I have a pretty big cache and I'm hitting the space limit on the device with Github Actions. Is there an easy way to delete all of them? Except `rm -rf .cache/pip`?

```
Cache Size: ~1466 MB (1536991552 B)
/bin/tar -xz -f /home/runner/work/_temp/76fce392-2ed6-491e-8d93-adb7bf4bc585/cache.tgz -C /home/runner/.cache/pip
Cache restored from key: Linux-pip-2d4e52fa2323a6793ee31880d97894a671038a8fe251d604992e4f55b253ef20
```

**Comment by joshmgross** [comment]
👋 Hey @philipbremer, right now there is no way to explicitly delete a cache. If you modify your key, you can start pulling from a new cache instead of the large existing cache.

**Comment by philipperemy** [comment]
@joshmgross got it thank you!
