### ISSUE TITLE
No scopes with read permission were found on the request

### ISSUE THREAD

**Issue by wagenet** [actions/cache#297]
I've just started seeing:

```
[warning]No scopes with read permission were found on the request.
```

This prevents the cache from restoring.

**Comment by dhadka** [comment]
@wagenet Did you see this when re-running a failed workflow? If so, this is a known issue - https://github.com/actions/cache/issues/208#issuecomment-607877125.

**Comment by wagenet** [comment]
No, these were new runs. It appears to have been a remote issue that resolved itself.

**Comment by dhadka** [comment]
Interesting.  Was the repo public?  Could you share the link?  @joshmgross FYI ☝️

**Comment by wagenet** [comment]
It was not public.

**Comment by wagenet** [comment]
@joshmgross it was yesterday morning and seemed to self-resolve. They were pull_request events. Repo is tildeio/direwolf-agent.

**Comment by singingwolfboy** [comment]
I'm occasionally seeing this as well with my company's private repository.

**Comment by hectorpizarro** [comment]
It seems to be related, I get the following error message when my workflow attempts to restore cache:

`[warning]getCacheEntry failed: No scopes with read permission were found on the request.`

The workflow is executed when a PR was merged, that is:

```
on:
  pull_request:
    branches: [ master ]
    types: [closed]
```
