### ISSUE TITLE
Confusing example for npm

### ISSUE THREAD

**Issue by Mordred** [actions/cache#309]
Hi, I was trying to implement caching for `npm` based on example in docs https://github.com/actions/cache/blob/master/examples.md#node---npm but my cache was never hit.

There is `${{ hashFiles('**/package-lock.json') }}` in the example which will generate different hash for runner step and post runner step because it will match `package-lock.json` files in node_modules.

![image](https://user-images.githubusercontent.com/29232/81800454-28d22780-9513-11ea-8e9f-d99dc0260df8.png)

It took me some time to find out why it is not working so I think that example should be more clear or the cache key should be reused in post run.

**Comment by joshmgross** [comment]
👋 Hey @Mordred, we actually do re-use the cache key in the post step because of this issue, see https://github.com/actions/cache/blob/46fead7f5e04ecfcf8e2f83aa0a908b284e14c04/src/save.ts#L24


`Hashfiles` is evaluated twice, but that post step ignores the input.

**Comment by Mordred** [comment]
That is strange, because I have always got a cache-miss:
```
Cache not found for input keys: Linux-node-0e87dc25b24f828004a17f6d5b274ebe29ae9dcfee92cdf9ec0cf39cf1935c7a, Linux-node-.
```

until I have changed pattern only to one `package-lock.json`

**Comment by joshmgross** [comment]
>That is strange, because I have always got a cache-miss:

Did you figure this out?

It would at least expect a cache hit from a restore key, assuming there's a cache on your default branch to restore from.
