### ISSUE TITLE
Long key gets truncated in the UI

### ISSUE THREAD

**Issue by mzabaluev** [actions/cache#311]
My workflow tries to improve cache coherence by using hierarchical keys, consisting of a fixed prefix followed by two hashes from differently variable file sources. This results in a long primary key, but then the key appears to be effectively truncated accordingly to a log message, like in this [run](https://github.com/input-output-hk/chain-libs/runs/678355136?check_suite_focus=true):

```
  with:
    path: ~/.cargo/registry
    key: Linux-cargo-registry-v1-2ac2a43cb7f80b945a11345b0eb9f4ff41596ba78129ad7cb130f7023f302239-91eba4bcc27b55c7ecf9bef264ba33101e7c0f7a4eb56f1f676a8e4f4da54f45
    restore-keys: Linux-cargo-registry-v1-2ac2a43cb7f80b945a11345b0eb9f4ff41596ba78129ad7cb130f7023f302239-
  Linux-cargo-registry-v1-
  
  env:
    GIT_AUTHOR_NAME: GitHub CI
    GIT_AUTHOR_EMAIL: [redacted]@users.noreply.github.com
    GIT_COMMITTER_NAME: GitHub CI
    GIT_COMMITTER_EMAIL: [redacted]@users.noreply.github.com
Cache Size: ~122 MB (128144670 B)
/bin/tar -xz -f /home/runner/work/_temp/49b4284a-c2a3-42ae-8448-a3a1e9cc9ed2/cache.tgz -C /home/runner/.cargo/registry
Cache restored from key: Linux-cargo-registry-
```

Perhaps some script unwittingly applies pretty printing with word wrapping to a YAML file somewhere?

**Comment by dhadka** [comment]
Hi @mzabaluev, something is being formatted strangely in the UI.  If you look at the raw logs (click the ... in the upper-right hand corner), it shows the full key:

```
2020-05-15T14:14:26.0047019Z Cache restored from key: Linux-cargo-registry-v1-2ac2a43cb7f80b945a11345b0eb9f4ff41596ba78129ad7cb130f7023f302239-91eba4bcc27b55c7ecf9bef264ba33101e7c0f7a4eb56f1f676a8e4f4da54f45
```

I'll need to track down which team develops the actions UI and pass this on to them.

**Comment by dhadka** [comment]
Alright, I filed an issue against the team.  I'll try to keep an eye on it and update here when the issue is resolved.  Thanks for bringing this to our attention!

**Comment by gimenete** [comment]
Hi 👋 

I'm an engineer behind the logs functionality. We've recently made a couple of changes but I'm not being able to replicate the problem.

With this URL https://github.com/input-output-hk/chain-libs/runs/678355136?check_suite_focus=true#step:4:4 I see this:

![Screen Shot 2020-05-15 at 17 59 11](https://user-images.githubusercontent.com/50486/82071066-d8ef8e00-96d5-11ea-8c44-e3a038fbf833.png)

Works on Firefox and Chrome. Could you try with a hard refresh and see if it still happens? If it does, could you share the exact log line (click on the line number on the left) and the browser you are using? A screenshot would be helpful.

Thanks!

**Comment by gimenete** [comment]
Ok, found the issue. A fix is done, pending of being deployed.

**Comment by mzabaluev** [comment]
Ah, thanks for clarifying that it is an UI problem.

@gimenete I can still see the truncation in the page of that run, after loading it in a new tab and a hard refresh; it seems dependent on the length of the key, as I see an adequately displayed key in the runs where the cache was missed and a shorter key was chosen.

The line link: https://github.com/input-output-hk/chain-libs/runs/678355136?check_suite_focus=true#step:4:15
The browser is Firefox (firefox-76.0.1-1.fc32.x86_64), running on Fedora Linux with `MOZ_ENABLE_WAYLAND=1`.

**Comment by mzabaluev** [comment]
![The screenshot](https://user-images.githubusercontent.com/1198919/82074018-c62f8600-96e2-11ea-82d6-07f436f5cb44.png)

**Comment by mzabaluev** [comment]
Perhaps it's not an `actions/cache` issue after all. Feel free to clone it where appropriate.

**Comment by gimenete** [comment]
Should be fixed now!

**Comment by mzabaluev** [comment]
Long keys are displayed correctly now, thank you!
