### ISSUE TITLE
Tar fails on Windows after 15min due to symlink cycle

### ISSUE THREAD

**Issue by cjolowicz** [actions/cache#315]
On Windows, the cache action hangs for 15+min in the post step before failing with `Cannot stat: Invalid argument`. It appears to be caught in a symlink cycle, see details below. I have seen this issue consistently for a few weeks on Windows runners, on every run.

The cache action is used for the `~/.cache/pre-commit` directory, which contains environments for linter tools managed by [pre-commit], in this particular case a node environment for [Prettier]. The job output suggests that tar.exe runs into a symlink cycle:

[pre-commit]: https://pre-commit.com/
[Prettier]: http://prettier.io/

```
Post job cleanup.
C:\windows\System32\tar.exe -cz -f d:/a/_temp/bcdd723a-8b44-4f20-a0cd-40818adf8d6e/cache.tgz -C C:/Users/runneradmin/.cache/pre-commit .
tar.exe: ./repobcgy0yhx/node_env-default/Scripts/node_modules/prettier/node_env-default/Scripts/node_modules/prettier/node_env-default/Scripts/node_modules/prettier/node_env-default/Scripts/node_modules/prettier/node_env-default/Scripts/node_modules/prettier/node_env-default/Scripts/node_modules/prettier/node_env-default/Scripts/node_modules/prettier/node_env-default/Scripts/node_modules/prettier/node_env-default/Scripts/node_modules/prettier/node_env-default/Scripts/node_modules/prettier/node_env-default/Scripts/node_modules/prettier/node_env-default/Scripts/node_modules/prettier/node_env-default/Scripts/node_modules/prettier/node_env-default/Scripts/node_modules/prettier/node_env-default/Scripts/node_modules/prettier/node_env-default/Scripts/node_modules/prettier/node_env-default/Scripts/node_modules/prettier/node_env-default/Scripts/node_modules/prettier/node_env-default/Scripts/node_modules/prettier/node_env-default/Scripts/node_modules/prettier/node_env-default/Scripts/node_modules/prettier/node_env-default/Scripts/node_modules/prettier/node_env-default/Scripts/node_modules/prettier/node_env-default/Scripts/node_modules/prettier/node_env-default/Scripts/node_modules/prettier/node_env-default/Scripts/node_modules/prettier/node_env-default/Scripts/node_modules/prettier/node_env-default/Scripts/node_modules/prettier/node_env-default/Scripts/node_modules/prettier/node_env-default/Scripts/node_modules/prettier/node_env-default/Scripts/node_modules/prettier/node_env-default/Scripts/node_modules/prettier: Cannot stat: Invalid argument
tar.exe: Error exit delayed from previous errors.
[warning]Tar failed with error: The process 'C:\windows\System32\tar.exe' failed with exit code 1
```

- [Workflow definition](https://github.com/cjolowicz/cookiecutter-hypermodern-python-instance/blob/951366cc512c517fbd05d3b74eb52ab28cf23dc0/.github/workflows/tests.yml)
- [Workflow output](https://github.com/cjolowicz/cookiecutter-hypermodern-python-instance/pull/183/checks?check_run_id=680815085)

Inspecting the cache layout locally reveals that `prettier` is a symlink to the directory three levels up:

```console
$ readlink ~/.cache/pre-commit/repo2c0jl6uh/node_env-default/lib/node_modules/prettier
../../../

$ realpath ~/.cache/pre-commit/repo2c0jl6uh/node_env-default/lib/node_modules/prettier
~/.cache/pre-commit/repo2c0jl6uh
```

(Note that this is on a macOS machine. The directory layout should be similar on Windows, with a `Scripts` directory instead of `lib`.)

Could be related to #120

**Comment by Yajo** [comment]
Same here. Just in case it helps, [here is the fail log](https://github.com/copier-org/copier/pull/224/checks?check_run_id=958255112#step:25:3) and [here is the workflow code](https://github.com/copier-org/copier/blob/8614a44e22cda6e9435804d026fde65f088385cc/.github/workflows/ci.yml#L48-L55).

**Comment by dhadka** [comment]
@Yajo I tested with symbolic links and junction points.  Symbolic links are handled fine, but junction points create problems for `bsdtar`.  It looks like the Windows 2019 runners have GNU tar installed as part of `msys`, which can be enabled with:

```
    - name: Use GNU Tar from Msys
      if: ${{ runner.os == 'Windows' }}
      run: |
        echo "::add-path::C:\msys64\usr\bin"
```

See for example: https://github.com/dhadka/test-tar-symlink/blob/master/.github/workflows/blank.yml

**Comment by Yajo** [comment]
My workaround in https://github.com/copier-org/copier/pull/251 had to be:


      - name: Enable msys binaries
        if: ${{ runner.os == 'Windows' }}
        run: |
          echo "::add-path::C:\msys64\usr\bin"
          rm C:\msys64\usr\bin\bash.exe

Otherwise all further steps executed with `shell: bash` failed due to using `C:\msys64\usr\bin\bash.exe` instead of `C:\Program Files\Git\bin\bash.EXE`.

**Comment by Yajo** [comment]
That one is deprecated now. Gotta use [this syntax](https://github.community/t/deprecated-add-path/136621/4?u=yajo):


      - name: Enable msys binaries
        if: ${{ runner.os == 'Windows' }}
        run: |
          echo "C:\msys64\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          rm C:\msys64\usr\bin\bash.exe
