### ISSUE TITLE
Incorrect parameters passed to zstd

### ISSUE THREAD

**Issue by richardxia** [actions/cache#316]
In https://github.com/actions/cache/issues/141, I had reported some reliability issues with using an unreleased version of the cache action, and I was recommended to try out the latest unreleased version, which included some reliability improvements.

I tried out the latest commit at the time (16a133d9a70d12a51f9a8e3a3b6261b91d589d79) in https://github.com/chipsalliance/rocket-chip/pull/2472, but if you take a look at some of the [pre-cache job results](https://github.com/chipsalliance/rocket-chip/pull/2472/checks?check_run_id=681314564), they silently failed on the "Post Run actions/cache" step with the following error message:

```
Post job cleanup.
/bin/tar --use-compress-program zstd -T0 --long=30 -cf cache.tzst -P -C /home/runner/work/rocket-chip/rocket-chip --files-from manifest.txt
Incorrect parameters
Usage : 
      zstd [args] [FILE(s)] [-o file] 

FILE    : a filename 
          with no FILE, or when FILE is - , read standard input
Arguments : 
 -#     : # compression level (1-19, default:3) 
 -d     : decompression 
 -D file: use `file` as Dictionary 
 -o file: result stored into `file` (only if 1 input file) 
 -f     : overwrite output without prompting and (de)compress links 
--rm    : remove source file(s) after successful de/compression 
 -k     : preserve source file(s) (default) 
 -h/-H  : display help/long help and exit 
[warning]Tar failed with error: The process '/bin/tar' failed with exit code null
```

Looking at the recent commit history, I found https://github.com/actions/cache/pull/270, which changed the compression tool from gzip to zstd. I am not personally familiar with the zstd command line program, but I am wondering if the command line interface changed between Ubuntu 16.04 and newer versions, since my job currently uses the ubuntu-16.04 runner.

**Comment by aiqiaoy** [comment]
On Ubuntu 16.04:
```
zstd --version
*** zstd command line interface 64-bits v1.3.1, by Yann Collet ***
```

On Ubuntu 18.04:
```
zstd --version
*** zstd command line interface 64-bits v1.3.3, by Yann Collet ***
```


Long range mode is added to zstd in v1.3.2 according to this [release log](https://github.com/facebook/zstd/releases?after=v1.3.3).

**Comment by aiqiaoy** [comment]
Fixed in https://github.com/actions/cache/pull/313

**Comment by richardxia** [comment]
Thanks for fixing this so quickly!
