### ISSUE TITLE
Adding cache steps makes two skipped checks wait indefinitely.

### ISSUE THREAD

**Issue by blane1988** [actions/cache#320]
Hello,

As the image shows, I am skipping two PR checks when they are not needed. Without cache actions in my steps, the two checks are skipped and I can merge (even if they are required). When I add cache actions and job runs again, it shows the two skipped steps, but then two duplicates of those skipped steps get added and PR waits forever for them.

<img width="792" alt="Screen Shot 2020-05-19 at 9 46 28 AM" src="https://user-images.githubusercontent.com/42759546/82491878-e8425300-9aaa-11ea-8127-02c53f2b0a73.png">

**Comment by joshmgross** [comment]
👋 Hey @blane1988, could you share your workflow file?

I would not expect the cache action to change the checks reported for a workflow.

**Comment by blane1988** [comment]
Hi @joshmgross , thanks for response. 

[Here is the flow.](https://gist.github.com/blane1988/e1b54c8707d47f8552515d3aba933602) The same PR has been stuck waiting for results for a couple days (just wanted to see if anything would eventually happen). And then when I open a PR with a workflow that doesn't have caching steps included, the checks pass (or are skipped) and then I can merge.

**Comment by blane1988** [comment]
And just FYI, here is what a PR looks like if I remove caching:

<img width="834" alt="Screen Shot 2020-05-21 at 2 03 39 PM" src="https://user-images.githubusercontent.com/42759546/82595942-189df600-9b6c-11ea-8cb1-221a74b3bcc1.png">

**Comment by joshmgross** [comment]
Thanks for the extra info.

In the first screenshot, you can see that the jobs still run with caching, but they don't match the expected names of the required checks. 

Since the required check names are capitalized ("iOS Unit Tests"), could you update your caching workflow to make sure those names match the correct casing?

```diff
ios-unit-tests:
-     name: iOS unit tests
+     name: iOS Unit Tests
      needs: native-files-check
      if: needs.native-files-check.outputs.run_ios_job == 'true'
      runs-on: macos-latest
```

```diff
 android-build-test:
-     name: Android debug build
+     name: Android Debug Build
      needs: native-files-check
      if: needs.native-files-check.outputs.run_android_job == 'true'
      runs-on: ubuntu-latest
```

**Comment by blane1988** [comment]
Thanks @joshmgross, that was the ticket!
