### ISSUE TITLE
Document and Release V2 of actions/cache

### ISSUE THREAD

**Issue by joshmgross** [actions/cache#323]
With the recent improvements made to the cache action, we'll be releasing a V2 version of this action.

### What's New

* Added support for multiple paths (https://github.com/actions/cache/issues/16), glob patterns, and single file caches (https://github.com/actions/cache/issues/33)
* Increased performance and improved cache sizes using `zstd` for compression (https://github.com/actions/cache/issues/184). (Off for windows-latest hosted runner)
* Allowed caching for all events with a ref (https://github.com/actions/cache/issues/63)
    * See [Events that trigger workflows](https://help.github.com/en/actions/reference/events-that-trigger-workflows) for info on which events do not have a `GITHUB_REF`
* Created the [`@actions/cache`](https://github.com/actions/toolkit/tree/master/packages/cache) npm package to allow other actions to utilize caching (https://github.com/actions/cache/issues/55)
* Added a best-effort step to delete the archive after extraction to reduces storage space (https://github.com/actions/cache/pull/209). 

### To Do

- [x] Update README to include a "What's New" section and info about upgrading to `v2`
- [x] Update [examples](https://github.com/actions/cache/blob/master/examples.md) to reference `v2` and use multiple paths if possible
- [x] Update the help docs ([Caching dependencies to speed up workflows](https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows) to reference `v2` (Tracked via an internal issue
- [x] Update the action.yml description for `path` to mention glob, multipath, and single file support. This should link to [`@actions/glob`](https://github.com/actions/toolkit/tree/master/packages/glob) for glob pattern documentation
- [x] Update the toolkit cache package README to include a link to the cache action as example usage. 
- [x] Change log https://github.com/github/releases/issues/835

**Comment by aiqiaoy** [comment]
[v2.0.0](https://github.com/actions/cache/releases/tag/v2.0.0) is now released!
