### ISSUE TITLE
Detect Key used for cache hit

### ISSUE THREAD

**Issue by senden9** [actions/cache#331]
Hi!

Is there a way to detect the key that created a cache hit? Or if it was hit by `key` or `restore-keys`?

Background:
I use `cache` in combination with Python/pip. My `key` contains python interpreter, OS and the hash of my dependencies. Currently i do not use `restore-keys` for partial matches.

If I need to install my dependencies without a exact cache hit (=`key`) then I must install some build deps via `apt`.  But the most time this is not needed. So I only install the deps if `cache-hit` is false.
Now it is the case that a build of a updated dependency is faster with the cache from the old build.
But I can not detect if I need to install build deps because even a partial key hit (=`restore-keys`) sets `cache-hit` to true.

Rebuilding my dependencies without a cache takes about 27 minutes. Install my build dependencies each time adds ~50 seconds to each build.

**Comment by senden9** [comment]
OK, i just read the source code and the documentation. I think they diverge.

From reading the source code I think `cache-hit` is only `true` if there was a exact match with the primary key (`key`). https://github.com/actions/cache/blob/b8204782bbb5f872091ecc5eb9cb7d004e35b1fa/src/restore.ts#L51-L52

Reading the [documentation](https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows#output-parameters-for-the-cache-action) lets me think that `cache-hit` is set to `true` no mater how the cache was hit.
> `cache-hit`: Set to `true` for a cache hit, and set to `false` for a cache miss.

**Comment by joshmgross** [comment]
👋  Hey @senden9, looks like those docs are incorrect. `cache-hit` is only true when there's an exact match, this is correctly documented in the README: https://github.com/actions/cache#outputs

**Comment by senden9** [comment]
Thanks for letting me know. It seems that somebody adapted also the help.github.com documentation over night :D. If you click now on the given link from my [comment above](https://github.com/actions/cache/issues/331#issuecomment-634507265) you will find a description that matches the README (and not my old quotation).

Anyway, my problem is solved. I close this issue.
