### ISSUE TITLE
Manually delete cache

### ISSUE THREAD

**Issue by leezu** [actions/cache#340]
If a cache with same key already exists, it never get's overwritten. Consider a situation where during development a wrong cache was created. How to delete it?

We may have cache `key` and `key-COMMITSHA`. If `key` was wrongly created earlier, Actions will always fallback to `key` in case the current `key-COMMITSHA` does not exist yet. How to delete the cache with key `key`?

**Comment by timbze** [comment]
Dupe of #2?

**Comment by leezu** [comment]
Close in favor of #2
