### ISSUE TITLE
Normalize path in version hash

### ISSUE THREAD

**Issue by dhadka** [actions/cache#345]
As suggested by @mzabaluev in https://github.com/actions/cache/pull/343#pullrequestreview-423013155, the logic to calculate the version hash could consider other normalizations to the path, including:

1. Sorting the paths so the version hash is independent of the ordering
2. Removing additional whitespace in glob patterns, such as any space between ! and the path.

**Comment by mzabaluev** [comment]
Any progress on this or #473?
