### ISSUE TITLE
Cache upload failed because file read failed with undefined

### ISSUE THREAD

**Issue by Ridermansb** [actions/cache#356]
Self-hosting (ubuntu) error (private project)

![image](https://user-images.githubusercontent.com/725337/85634794-a892fc00-b652-11ea-896c-5d34853e7821.png)

>  Post Cache node modules12m 21s
    at FSReqCallback.wrapper [as oncomplete] (fs.js:470:5)
Post job cleanup.
/bin/tar -z -cf cache.tgz -P -C /home/pi/actions-runner/_work/pwa/pwa --files-from manifest.txt
[warning]uploadChunk (start: 0, end: 33554431) failed: Cache service responded with 503
/home/pi/actions-runner/_work/_actions/actions/cache/v2.0.0/dist/save/index.js:2440
                        throw new Error(`Cache upload failed because file read failed with ${error.Message}`);
                        ^

> Error: Cache upload failed because file read failed with undefined
    at ReadStream.<anonymous> (/home/pi/actions-runner/_work/_actions/actions/cache/v2.0.0/dist/save/index.js:2440:31)
    at ReadStream.emit (events.js:210:5)
    at internal/fs/streams.js:167:12
    at FSReqCallback.wrapper [as oncomplete] (fs.js:470:5)

**Comment by kengz** [comment]
facing the same issue. For me the cache step runs for a few minutes before failing with that error. For ref my err log is:
```
Post job cleanup.
/bin/tar -cz -f /home/ga/actions-runner/_work/_temp/c8bdac35-ee3e-4495-8879-fbfe3fee7910/cache.tgz -C /home/ga/miniconda3/envs/privateproject .
[warning]uploadChunk (start: 33554432, end: 67108863) failed: Cache service responded with 503
/home/ga/actions-runner/_work/_actions/actions/cache/v1/dist/save/index.js:1481
                        throw new Error(`Cache upload failed because file read failed with ${error.Message}`);
                        ^

Error: Cache upload failed because file read failed with undefined
    at ReadStream.<anonymous> (/home/ga/actions-runner/_work/_actions/actions/cache/v1/dist/save/index.js:1481:31)
    at ReadStream.emit (events.js:210:5)
    at internal/fs/streams.js:167:12
    at FSReqCallback.wrapper [as oncomplete] (fs.js:470:5)
```

**Comment by kengz** [comment]
linking to issue #259

**Comment by dhadka** [comment]
Should be fixed by https://github.com/actions/cache/pull/596.  Please let me know if you continue to see this error.
