### ISSUE TITLE
Getting "cache not found for input keys" while running the windows job but able to retrive the same cache while running linux job

### ISSUE THREAD

**Issue by darwhs** [actions/cache#379]
I am using the github actions for packaging the rpm and msi files, to do that I am kin gusing use of caches, while retriving the cache while creating windows (msi) file I am getting error like "Cache not found for input keys: cached_binaries_174388414" while while creating rpm for linux it is able to retrive the same cache Cache restored from key: cached_binaries_174388414

you can take a look at both at the below work flow
https://github.com/mxiamxia/aws-opentelemetry-collector/runs/886396864?check_suite_focus=true

This seems to be a bug to me.

**Comment by dhadka** [comment]
@darwhs There's a known issue with tar + zstd, the compression used on Ubuntu and Mac, that causes the Windows process to hang on large files (see https://github.com/actions/cache/issues/301).  Until that is fixed, caches created on Ubuntu and Mac can't be used on Windows (and vice versa).  I would recommend using `upload-artifact` and `download-artifact` to workaround this issue.  Also, `upload-artifact` and `download-artifact` should work better for your workflow, where one job is using the output from another job.  While it's unlikely for a cache to be evicted between two jobs, it could happen.

**Comment by darwhs** [comment]
Thanks @dhadka  for the reply.

**Comment by dhadka** [comment]
Closing since the underlying issue is being tracked by #301.
