### ISSUE TITLE
Trigger post cache

### ISSUE THREAD

**Issue by JeroenDeDauw** [actions/cache#393]
Is it possible to trigger post cache so it runs before certain commands?

My use case is that I want to cache things installed by a package manager. And then install extra stuff with said package managed that should not be cached. In my script I cannot know what extra things get installed, so I cannot manually exclude them in the cache config. Having the cache make its copy before the second run of the package manager would solve this.

**Comment by MonsieurNicolas** [comment]
I have a similar situation. I am building a c++ project (very slow) and would like to sync the cache before running tests. This would allow iterating on changes much quicker as re-building would be fast when fixing tests or whatever.

**Comment by kindaro** [comment]
This is a very desirable feature for me as well, for the same reason as it is for @MonsieurNicolas.

**Comment by kindaro** [comment]
I still want it.

**Comment by robinp** [comment]
Drive-by comment: from https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows 

> Multiple workflows within a repository share cache entries. A cache created for a branch within a workflow can be accessed and restored from another workflow for the same repository and branch.

So maybe it is possible to have one workflow create the base cache with the key, and the other workflow just specify the same key to use it?

**Comment by kindaro** [comment]
Thanks @robinp!

**Comment by Phantsure** [comment]
@JeroenDeDauw @kindaro You can create different workflows as stated above or create sequential jobs, like job A will create a cache and job B can use that cache.
