### ISSUE TITLE
Cache not found for properly stored cache key

### ISSUE THREAD

**Issue by medikoo** [actions/cache#406]
I'm observing unexpected cache behavior when using `actions/cache@2`.

For properly stored cache at key X, following job successfully retrieves _cache_ key _X_, but following build does not, and exposes `Cache not found for input keys: X` error

For reference: jobs, which expose the error:

1. Job with which cache key `npm-v14-Linux-refs/heads/v3-1247a64fb06e89a88d05604692a1b55025a2a32665cecbaf24e996056e960f93` is successfully stored: https://github.com/serverless/enterprise-plugin/runs/1056442975?check_suite_focus=true
2. Following job where given cache key is successfully retrieved: https://github.com/serverless/enterprise-plugin/runs/1056469327?check_suite_focus=true
3. Following workflow (triggered at the end of above job), with which same cache key is reported as not found: https://github.com/serverless/enterprise-plugin/runs/1056507479?check_suite_focus=true

Is there any explanation for such behavior?

**Comment by medikoo** [comment]
I think I found the reason, it's documented in below line:

> The cache is scoped to the key and branch. The default branch cache is available to other branches.

I'm trying to retrieve cache stored at non-default branch, in context of a _tag_, and that won't work. It appears that _tag_ build is not guaranteed to have access to caches stored in context of branches which have tagged commit in its history

**Comment by cAstraea** [comment]
How can I modify the workflow then ? Using tagged for releases.  Like so  
```
name: Deploy development

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-release*dev'
```
