### ISSUE TITLE
Add C++ example

### ISSUE THREAD

**Issue by WSLUser** [actions/cache#408]
https://github.com/actions/cache/blob/main/examples.md provides examples for many languages but not C++. Please create one.

**Comment by KTibow** [comment]
What kind of packages would you have?

**Comment by WSLUser** [comment]
I'm looking to add this to Windows Terminal but my C++ experience is rather low and hoping stuff like this might help me learn it better while also improving a project I have alot of interest in. They have CLI11, FMT and plenty of other deps, some of which are Nuget packages such as MUX. The C# example seems to be close but not quite what's needed.

**Comment by KTibow** [comment]
Which package manager do you use? You need different ones based on where the cache is stored.

**Comment by WSLUser** [comment]
So they have wil and gsl as git submodules, the others are brought into the project. Nuget is the only package manager I'm aware of when building the project in Visual Studio. The non Nuget deps are simply copied into the repo.. Not sure if they can be cached or if they even need to.

**Comment by KTibow** [comment]
What are you planning to do with GitHub Actions?

**Comment by WSLUser** [comment]
Fixed my last statement. I want to cache the Nuget packages and git-submodules as part of the CI.

**Comment by KTibow** [comment]
`%localappdata%\NuGet\Cache` for nuget, submodules aren't cached.

**Comment by KTibow** [comment]
The C# example should work

**Comment by WSLUser** [comment]
Ok I'll give it a try and see how it goes.

**Comment by WSLUser** [comment]
So I got it working to a certain extent. What I'm not sure about about is if I should be adding the path where `packages.json` exists or just leave it with `~/.nuget/packages`.
