### ISSUE TITLE
Option to set the cache lifetime

### ISSUE THREAD

**Issue by AlexAegis** [actions/cache#413]
> Caches that are not accessed within the last week will also be evicted.

Along with the usual usage of this package I also use it to only conditionally release my library. For this I cache a version file (Which is automatically bumped on release and contains only the version number) so this action can tell me when it's changed, because of the hashed keys.

This solution has been really useful and easy to set up, but now a week has passed and I now understand why this job fails.

If for this cache only I could set the lifetime to infinite my problem would be solved.

(Another option would be useful to not litter the cache with these little version files is a `maxCaches` option, I don't know if there is an option for that)

**Comment by dhadka** [comment]
Hi @AlexAegis, thanks for the suggestion!  Out of curiosity, where do you publish your library?  If publishing to a package management service, such as `npm` or GitHub Packages, I would think reading the latest version from there would be a better "source of truth" for the last published version.

We currently don't have any options to control the lifetime or a `maxCaches` option.  Caches will also be evicted if exceeding the 5 GB storage quota.  That being said, as a workaround you could consider using a [schedule trigger](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule) to keep the last access time updated.

**Comment by AlexAegis** [comment]
Thanks, yes thats a good idea and I could use something like `[ ! -z "$(npm view packagename@version)" ]`

A workaround I used before is just letting it fail, but I don't like it because what if the real release fails

```sh
set +e
npm publish || return 0
set -e
```

And the schedule trigger is also a nice workaround for the cache lifetime problem

Regardless of my problem, I think options like this would be a nice addition!

**Comment by dhadka** [comment]
> Regardless of my problem, I think options like this would be a nice addition!

Yeah, I actually started a side project during a company hackathon last week that gives users more freedom in how they store and manage files.  It has a "time to live" field that would do exactly what you are asking for.  It still needs some work, especially on the AWS S3 side, so I wouldn't recommend it just yet.  But it's open for contributions - https://github.com/dhadka/stockpile

**Comment by pbrezina** [comment]
Still stands.

**Comment by Phantsure** [comment]
@pbrezina We don't yet support to set cache lifetime. You can still use the workaround given by dhadka. 
> That being said, as a workaround you could consider using a [schedule trigger](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule) to keep the last access time updated.

**Comment by Phantsure** [comment]
@AlexAegis @pbrezina Closing this. This seems like a feature request which currently is not in near scope.
