### ISSUE TITLE
Cache action uses `tar` but it is not provided on Windows

### ISSUE THREAD

**Issue by Warchant** [actions/cache#418]
![image](https://user-images.githubusercontent.com/1867551/94237972-52b34600-ff18-11ea-8b34-faf766d44d10.png)

```
Warning: Tar failed with error: The process 'C:\windows\System32\tar.exe' failed with exit code 1. Ensure BSD tar is installed and on the PATH.
```

Maybe `cache` action should provide its own `tar` or use OS-specific program to create archives?

**Comment by AraHaan** [comment]
Oh no why not use rar5?

**Comment by ChrisMichl** [comment]
Any news on this? I have the same problem.

**Comment by Warchant** [comment]
Bump

**Comment by AraHaan** [comment]
I think the best option for cache is to use 7z on Windows.

**Comment by tiwarishub** [comment]
Github hosted runner do have a tar installed on windows. And i think on self hosted we expect to have tar installed(now i think latest version of windows have tar installed natively).

**Comment by AraHaan** [comment]
I think this issue is no longer needed if you use the ``windows-latest`` runners as I think those are essentially on par with Windows 11 which has tar preinstalled on it and in the path.
