### ISSUE TITLE
Getting /bin/tar: unrecognized option: posix in post-job

### ISSUE THREAD

**Issue by peresbruno** [actions/cache#425]
Currently, I'm trying to use actions/cache@v2 to cache `yarn cache dir` to improve the pipeline time. Unfortunately, always that the actions/cache@v2 runs I'm getting an error in the post-job saying: `/bin/tar: unrecognized option: posix`. The complete log is:

```
Post job cleanup.
/usr/bin/docker exec  4decc52e7744d9ab2e81bb24c99a830acc848912515ef1e86fbb9b8d5049c9cf sh -c "cat /etc/*release | grep ^ID"
/bin/tar --posix -z -cf cache.tgz -P -C /__w/open-tuna-api/open-tuna-api --files-from manifest.txt
/bin/tar: unrecognized option: posix
BusyBox v1.31.1 () multi-call binary.

Usage: tar c|x|t [-ZzJjahmvokO] [-f TARFILE] [-C DIR] [-T FILE] [-X FILE] [--exclude PATTERN]... [FILE]...

Create, extract, or list files from a tar file

	c	Create
	x	Extract
	t	List
	-f FILE	Name of TARFILE ('-' for stdin/out)
	-C DIR	Change to DIR before operation
	-v	Verbose
	-O	Extract to stdout
	-m	Don't restore mtime
	-o	Don't restore user:group
	-k	Don't replace existing files
	-Z	(De)compress using compress
	-z	(De)compress using gzip
	-J	(De)compress using xz
	-j	(De)compress using bzip2
	-a	(De)compress using lzma
	-h	Follow symlinks
	-T FILE	File with names to include
	-X FILE	File with glob patterns to exclude
	--exclude PATTERN	Glob pattern to exclude
Warning: Tar failed with error: The process '/bin/tar' failed with exit code 1
```

I'm following the example of the official [action cache repository][1]. Here a snippet of my CI.yml

      # Configure cache
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

Because of the above error, the cache is not created and the pipeline time is not improved. I've tried changing the `hasFiles` expression and the entire key, but no success.

My question is: Am I making some mistake in the use of Action Cache? Can anyone help me with this issue? Thanks.

  [1]: https://github.com/actions/cache/blob/main/examples.md#node---yarn

**Comment by dhadka** [comment]
Hi, sorry you are hitting this issue.  You are using the action correctly, it looks like the `--posix` flag isn't supported on your version of `tar` (BusyBox).  This option was added in https://github.com/actions/toolkit/pull/533.  We will need to skip this option to support the BusyBox tar implementation.

As a temporary workaround, you should be able to update the workflow to use `v2.1.0` of the action, which does not include the `--posix` flag:

```
- uses: actions/cache@v2.1.0
```

**Comment by peresbruno** [comment]
Hi @dhadka 

Thanks for your help. After updating to v2.1.0, I'm getting a new error:

`unrecognized option: P`

![Screenshot from 2020-10-03 16-03-20](https://user-images.githubusercontent.com/1018182/94999789-217aeb80-0592-11eb-8edf-2b485c743624.png)

**Comment by peresbruno** [comment]
Solved. The error occurs because I'm using actions/cache inside a Linux Alpine container. The issue is related to the version of tar available with Linux Alpine. I've solved my issue by changing the container to `ubuntu:latest`. You can see more details in [this StackOverflow answer](https://stackoverflow.com/a/64187955/6835358). Thanks!
