### ISSUE TITLE
Question: Can someone explain me how it (sharing cache files across instances) works, so I can do cache for self hosted runner?

### ISSUE THREAD

**Issue by pekhota** [actions/cache#429]
I'm working on implementing cache for self hosted runner. Can someone share any ideas on how can I share cache data across self hosted instances?

**Comment by KTibow** [comment]
IMO this is hosted on GitHub, and the only way to self-host a cache is to buy GitHub Enterprise.

**Comment by pekhota** [comment]
Thanks
