### ISSUE TITLE
actions/cache@v1 jumps from ~24s to ~20m

### ISSUE THREAD

**Issue by schlosser** [actions/cache#436]
My last few deploys, starting yesterday, have seen `actions/cache@v1` take an extremely long time, jumping from ~20-30s to over 20m. 

My most recent deploy saw 21m 33s with `Cache Size: ~361 MB (378178930 B)`.

Might this be related to code in my repository? Or an Actions outage?

**Comment by dhadka** [comment]
Hi @schlosser, I would first recommend updating the workflow to use `actions/cache@v2` to see if that helps.  We released several changes in `@v2` to help with download speed and reliability.  Additionally, it will display the download progress so we can see if it gets stuck during the download or elsewhere.  After updating the version, please report back if you still see significant slowdowns.  Thanks!

**Comment by schlosser** [comment]
So far so good after upgrading! Closing this for now.
