### ISSUE TITLE
Why use multi-line string for restore-keys intead of array?

### ISSUE THREAD

**Issue by bendavies** [actions/cache#44]
Hey,

Just wondering why `restore-keys` is defined as a multi line string, while yaml obviously supports sequences?

https://github.com/actions/cache/blob/25e0c8faac42f323280d4d39373a00d402bd5e11/src/restore.ts#L23

Thanks!

**Comment by bendavies** [comment]
ok, @teohhanhui found that `core.getInput` doesn't support lists.
https://github.com/actions/toolkit/blob/4f11810a003820fd131eefc436ee0e31db1db382/packages/core/src/core.ts#L69

**Comment by joshmgross** [comment]
Yep, it's just a workaround until we support list inputs.

Tracking that here: https://github.com/actions/toolkit/issues/184
