### ISSUE TITLE
Getting a warning for `getCacheEntry` and `reserveCache`

### ISSUE THREAD

**Issue by javs-perez** [actions/cache#444]
Hey All, 

We are running into a new issue that seemed to start today with the caching action. We are getting the following errors when using the action:

```
Run actions/cache@v2
/usr/bin/docker exec  555b7c657bc5a13a07b0b7b85f74edb58118f96a5bccb8b1ccb99a3c83a88b42 sh -c "cat /etc/*release | grep ^ID"
Warning: getCacheEntry failed: ﻿{"$id":"1","innerException":null,"message":"The user 'System:ServiceIdentity;DDDDDDDD-DDDD-DDDD-DDDD-DDDDDDDDDDDD' is not authorized to access this resource.","typeName":"Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server","typeKey":"UnauthorizedRequestException","errorCode":0,"eventId":3000}
```

and 

```
Post job cleanup.
/usr/bin/docker exec  555b7c657bc5a13a07b0b7b85f74edb58118f96a5bccb8b1ccb99a3c83a88b42 sh -c "cat /etc/*release | grep ^ID"
Warning: reserveCache failed: ﻿{"$id":"1","innerException":null,"message":"The user 'System:ServiceIdentity;DDDDDDDD-DDDD-DDDD-DDDD-DDDDDDDDDDDD' is not authorized to access this resource.","typeName":"Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server","typeKey":"UnauthorizedRequestException","errorCode":0,"eventId":3000}
```

This causes an issue in the steps that follow, as the expected cache is not there.

We started seeing the issue today but have not changed anything in the code. 

Did something change within the filesystem or the permissions the container has?

**Comment by davidcalhoun** [comment]
Thank you!  I just started seeing this and thought it was something I did wrong.  Also getting this exact same issue over here, even on projects that were working fine before, where I haven't touched the workflow config.

**Comment by dhadka** [comment]
@javs-perez @davidcalhoun Thanks for reporting.  We are aware of the issue and are working on applying a fix. I'll provide periodic updates in this issue.

**Comment by javs-perez** [comment]
@dhadka thank you!

**Comment by dhadka** [comment]
We verified the fix and are rolling it out to the external AC servers.  Expect to see the issue resolved in the next few minutes.

**Comment by dhadka** [comment]
Should be resolved for everyone now.

**Comment by davidcalhoun** [comment]
@dhadka Thank you for the fast work!  Confirmed that it's working great from here now.

**Comment by jamierumbelow** [comment]
Seeing a separate but I presume related issue:

```
{"$id":"1","innerException":null,"message":"The user 'System:ServiceIdentity;DDDDDDDD-DDDD-DDDD-DDDD-DDDDDDDDDDDD' is not authorized to access this resource.","typeName":"Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server","typeKey":"UnauthorizedRequestException","errorCode":0,"eventId":3000}
```

**Comment by dhadka** [comment]
@jamierumbelow When did that workflow run?  We haven't seen this error in our telemetry since about 17:09 UTC (about an hour and a half ago).

**Comment by jamierumbelow** [comment]
@dhadka About two hours ago. Let me rerun...

**Comment by jamierumbelow** [comment]
Yep, that fixed it. Thanks!

**Comment by tovbinm** [comment]
Works for us as well! Thank you.

**Comment by javs-perez** [comment]
This worked for us, closing the issue. Thank you @dhadka!
