### ISSUE TITLE
support subdirectories

### ISSUE THREAD

**Issue by sam2de** [actions/cache#450]
Hello, 

I'm trying to use the Yarn cache example provided in the v2 [example](https://github.com/actions/cache/blob/main/examples.md#node---yarn), however, seems not working with seeing 0MB in cached files. we are not using Yarn in the root directory but in a subdirectory, I tried to use the working_directory flag, but that is not supported with the cache actions, Any advice on how this be handled?

**Comment by dhadka** [comment]
Hi @sam2de, the action should work fine with subdirectories by setting `path: ./path/to/subdir`.  See [this workflow](https://github.com/dhadka/test-cache-multi-path/blob/master/.github/workflows/blank.yml) for an example.

I would also recommend [enabling debug logging](https://docs.github.com/en/actions/configuring-and-managing-workflows/managing-a-workflow-run#enabling-step-debug-logging) to see if that provides more information.  Please also post a link to the workflow / logs (if in a public repo) or copy the logs here and we can help investigate.

**Comment by sam2de** [comment]
Thanks
