### ISSUE TITLE
How to cache NDK build directories? 

### ISSUE THREAD

**Issue by omkarnathsingh** [actions/cache#452]
Workflow link: https://github.com/RoyalWizard/Telegram/blob/master/.github/workflows/build.yml

This project (https://github.com/RoyalWizard/Telegram/) has a huge NDK build step when we do gradle build (approx 1 hour it takes). Is there any way to cache the NDK build output folder? (TMessagesProj/.cxx and TMessagesProj/build )

Also one doubt, Is there any image which had gradle and NDK installed by default?

**Comment by omkarnathsingh** [comment]
Update even the caching of gradle and ndk is not working in this workflow. Is the code wrong for it?

**Comment by dhadka** [comment]
Hi @omkarnathsingh,

Looking at https://github.com/RoyalWizard/Telegram/actions I only see the Action was triggered once and the logs show the caches being created.  The creation of the cache shows up in the "Post Cache Step" which appears separately in the logs.  See the screenshot below:

![image](https://user-images.githubusercontent.com/2496211/98378103-36242680-200b-11eb-9a27-3989a42342df.png)

The next time you run the action, you should see the cache restore.  There's a "re-run jobs" button in the top-right corner that will let you do this without creating another commit.

**Comment by omkarnathsingh** [comment]
Hi @dhadka ,
Thanks for looking into it. I retried it again and yes it worked. Gradle and NDK it took from cache. Thanks.

Can you provide solution for main issue as well? caching the build directory? It will save me 1 hour

**Comment by dhadka** [comment]
I think to cache the build outputs you would need to use a key that was either based on a hash of the source files, or perhaps more simply, use the run_id.

```
  uses: actions/cache@v2
  with:
    path: TMessagesProj/build
    key: ${{ runner.os }}-build-${{ github.run_id }}
    restore-keys: ${{ runner.os }}-build-
```

This should restore the build artifacts from the previous run while always creating a new cache with the generated build artifacts.

**Comment by omkarnathsingh** [comment]
Thanks, I will try this approach
