### ISSUE TITLE
Deprecation Warning DEP0005

### ISSUE THREAD

**Issue by malkam03** [actions/cache#461]
Using this action with the Java - Maven example code snippet, behind a proxy on a self-hosted runner. A security issue warning is logged:

```log
(node:69) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

Maybe related with?:
```bash
$ grep -r " Buffer(" -n
dist/restore/index.js:3583:        new Buffer(connectOptions.proxyAuth).toString('base64');
dist/save/index.js:3583:        new Buffer(connectOptions.proxyAuth).toString('base64');
```

See [node deprecation page](https://nodejs.org/api/deprecations.html#DEP0005) for more info.

**Comment by dhadka** [comment]
@malkam03 Thanks for reporting this.  Looks like this usage of the `Buffer` is coming from the NPM [tunnel](https://www.npmjs.com/package/tunnel) module, specifically https://github.com/koichik/node-tunnel/blob/5fb2fb424788597146b7be6729006cad1cf9e9a8/lib/tunnel.js#L122.  This dependency is pulled in by the [http-client](https://github.com/actions/http-client/blob/main/package.json#L37), I'm going to transfer over to that repo to investigate / mitigate.

**Comment by malkam03** [comment]
Perfect, thank you @dhadka 😄

**Comment by dhadka** [comment]
I apparently don't have permissions to transfer to `http-client`, so I filed a new issue over there - https://github.com/actions/http-client/issues/36.
