### ISSUE TITLE
some files can't  restore

### ISSUE THREAD

**Issue by mingxiaoyu** [actions/cache#464]
you can check this :
https://github.com/mingxiaoyu/N1imagebuilder/runs/1410230877

there are 4 files in /opt/dl. but only restore the 2 file from cache

all files:
Armbian_20.02.0_Aml-s9xxx_buster_5.4.50-flippy-38+o.img.xz    size:280M
confirm.txt
cookies.txt
openwrt-armvirt-64-default-rootfs.tar.gz  size:160M
------------------------------
restore files:
confirm.txt
cookies.txt

**Comment by mingxiaoyu** [comment]
- uses: actions/cache@v2
      id: opwenwrtcache
      with:
        path: |
          /opt/dl
        key: ${{ runner.os }}-opwenwrt-${{ env.FLIPPY_NAME }}-${{ env.version }}-${{ hashFiles('**/openwrt-armvirt-64-default-rootfs.tar.gz') }}
        restore-keys: |
          ${{ runner.os }}-opwenwrt-${{ env.FLIPPY_NAME }}-${{ env.version }}-

**Comment by mingxiaoyu** [comment]
Run actions/cache@v2
  with:
    path: /opt/dl/openwrt-armvirt-64-default-rootfs.tar.gz
  /opt/dl/Armbian_20.02.0_Aml-s9xxx_buster_5.4.50-flippy-38+o.img.xz
  
    key: Linux-opwenwrt-38-20201117-
    restore-keys: Linux-opwenwrt-38-20201117-
    
  
  env:
    UPLOAD_COWTRANSFER: true
    RELEASE: true
    FLIPPY_NAME: 38
    FLIPPY_FILENAME: Armbian_20.02.0_Aml-s9xxx_buster_5.4.50-flippy-38+o.img.xz
    RELEASE_NAME: N1_38_Openwrt.img
    FLIPPY_FILEID: ***
    version: 20201117
    DATE: 2020-11-19 13:33:38
Received 22 of 22 (100.0%), 0.0 MBs/sec
Cache Size: ~0 MB (22 B)
/usr/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/4d9a6ca4-cf4d-4453-9474-4637ee555e44/cache.tzst -P -C /home/runner/work/N1imagebuilder/N1imagebuilder
Cache restored from key: Linux-opwenwrt-38-20201117-

Check Files
0s
Run cd /opt/dl
  cd /opt/dl
  ls


cache restored but , can't find the files.
whart 's happen?

https://github.com/mingxiaoyu/N1imagebuilder/runs/1424422490

any body can help me ?

**Comment by dhadka** [comment]
Hi, I tried to fork your repo but it's [failing on the "build img" step](https://github.com/dhadka/N1imagebuilder/runs/1424706472?check_suite_focus=true#step:9:33).  Since I can't investigate it that way, could you please [enable step debug logging](https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/enabling-debug-logging#enabling-step-debug-logging) and re-run the workflow with a new cache key.  That'll provide some more information on what files it's finding and including in the cache.

**Comment by dhadka** [comment]
Oh, I think I see the issue.  One of the steps is moving the files to a different folder:

```

    - name: Copy files
      run: |
        mv /opt/dl/openwrt-armvirt-64-default-rootfs.tar.gz /opt/openwrt/openwrt-armvirt-64-default-rootfs.tar.gz
        mv /opt/dl/$FLIPPY_FILENAME /opt/imgs/$FLIPPY_FILENAME
```

So those files are no longer in `/opt/dl` when it goes to create the cache in the "Post Cache" step.

**Comment by mingxiaoyu** [comment]
@dhadka thank you
