### ISSUE TITLE
Decoding error (36) : Corrupted block detected 

### ISSUE THREAD

**Issue by moltar** [actions/cache#472]
Getting the following errors, which are, I think, corrupting the data, and then further NPM installs aren't working correctly.

```
Run actions/cache@v2
Received 202938074 of 202938074 (100.0%), 183.8 MBs/sec
Cache Size: ~194 MB (202938074 B)
/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/75411e58-6c0c-462c-b791-61912c03ea6f/cache.tzst -P -C /home/runner/work/foo/foo
/*stdin*\ : Decoding error (36) : Corrupted block detected 
/bin/tar: Unexpected EOF in archive
/bin/tar: Unexpected EOF in archive
/bin/tar: Error is not recoverable: exiting now
Warning: Tar failed with error: The process '/bin/tar' failed with exit code 2
```

**Comment by dhadka** [comment]
@moltar We have seen the EOF error before when the download is interrupted.   Is this error happening consistently or just intermittently?  If consistently, the data stored in the cache might be corrupt...in which case I would recommend changing the key to force it to create a new cache.

**Comment by moltar** [comment]
> Is this error happening consistently

yeah, it was happening on each run

> I would recommend changing the key to force it to create a new cache

I did try that already. Did not help 🤷🏼‍♂️
