### ISSUE TITLE
Post cache hook runs after containers shut down

### ISSUE THREAD

**Issue by ly-cultureiq** [actions/cache#48]
Hi,

I use a container for job running (see [here](https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idcontainer))

And being that the container shuts down _before_ the post cache action - the data for the cache is unavailable. it just gives an error `Error: No such container: CONTAINER_ID`

it seems the (undocumented?) `post` parameter for the actions `runs` should be configurable as to be post container shutdown or pre shutdown

**Comment by aissarmurad** [comment]
I have the same problem.

It's seems duplicated in https://github.com/actions/cache/issues/12

I hope It's solved soon

**Comment by ly-cultureiq** [comment]
totally a dupe - i looked at the issues and somehow missed it. closing this in favor of #12
