### ISSUE TITLE
Using v2 vs v2.1.3

### ISSUE THREAD

**Issue by AleksIvanovSinglet** [actions/cache#499]
An action I am using, uses by default actions/cache@v1.

When I configured Dependabot, it created a PR with an update to actions/cache@v2.1.3.

I saw on the page of actions/cache, the version in the example code is v2 and not the latest release v2.1.3.

Should I update to v2.1.3 or is there a specific reason to use v2 instead, as showed in the example code ?

**Comment by dhadka** [comment]
We update the `v2` tag to point to the latest release, so currently `v2` is the same as `v2.1.3`.  We recommend using `v2` so you are always using the latest version.

**Comment by AleksIvanovSinglet** [comment]
> We update the `v2` tag to point to the latest release, so currently `v2` is the same as `v2.1.3`. We recommend using `v2` so you are always using the latest version.

Does that apply automatically to all actions or do you do it for yourself manually ?

**Comment by dhadka** [comment]
Yes, if you have `uses: actions/cache@v2` in your workflow, it will automatically start using the latest `2.x.x` version when we update the tag.

**Comment by dhadka** [comment]
(I realized there's a second possible interpretation of your last question.  This way of versioning, where we have a "major version" tag such as `@v2` that points to the latest patch version, is something we do manually for the official GitHub actions.  This is not automatically done for all actions.)

**Comment by AleksIvanovSinglet** [comment]
Thank you!
