### ISSUE TITLE
DOC: Security considerations for OSS

### ISSUE THREAD

**Issue by pllim** [actions/cache#500]
Hello. I contacted GitHub Help Desk to inquire about this but was told to open an issue here instead. In the OSS world, a repository running GitHub Actions may receive a lot of pull requests from forks. GitHub Actions offers both [pull_request](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#pull_request) and [pull_request_target](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#pull_request_target). In the latter's documentation, there is a very exciting warning about "cache poisoning." In addition, there is also a [GitHub article about preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests), which unfortunately did not address cache poisoning.

Is it correct to say that `actions/cache` should only be used with `pull_request` and never `pull_request_target`? If not, what other considerations should be taken into account?

If you could document this in your README, that would be awesome. Thank you for your support for OSS!

**Comment by mvanalphen** [comment]
From the looks of it, the `pull_request_target` event is not supported at all by the cache action: `Warning: Event Validation Error: The event type pull_request_target is not supported. Only push, pull_request events are supported at this time.`.

**Comment by christhekeele** [comment]
As far as I can tell, `actions/cache` [refuses](https://github.com/christhekeele/matcha/runs/4601224696?check_suite_focus=true#step:8:14) to [run](https://github.com/christhekeele/matcha/runs/4601224696?check_suite_focus=true#step:17:2) when `pull_request_target` is used, so this shouldn't be an issue.

**Comment by renbou** [comment]
> As far as I can tell, `actions/cache` [refuses](https://github.com/christhekeele/matcha/runs/4601224696?check_suite_focus=true#step:8:14) to [run](https://github.com/christhekeele/matcha/runs/4601224696?check_suite_focus=true#step:17:2) when `pull_request_target` is used, so this shouldn't be an issue.

Not exactly, this is only true for v1 as stated in the [github docs](https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows):
> With v2 of the cache action, you can access the cache in workflows triggered by any event that has a GITHUB_REF. If you are using v1 of the cache action, you can only access the cache in workflows triggered by push and pull_request events, except for the pull_request closed event.

**Comment by christhekeele** [comment]
Ah, you're absolutely right, I just have a few actions running the old version I'd based this opinion on. Thanks for the correction!

**Comment by aparna-ravindra** [comment]
> Is it correct to say that actions/cache should only be used with pull_request and never pull_request_target?

The action does not restrict you from using `pull_request_target` event. However, as explained in the doc for `pull_request_target`, the creator of the workflow should be aware that the caches created (if any) will be associated with the base branch (in most cases this is the default branch and hence can be reused by other workflows). 

Since this information is already documented, I do not see the necessity to document it again here.
