### ISSUE TITLE
Windows server 2019 showing "cant create" issue with version V2

### ISSUE THREAD

**Issue by inbangsa** [actions/cache#508]
I am trying using ```action/cache@v2``` on windows server 2019 but its showing the following issue. from logs it seems, cache is found but not able to extract it 

```
Run actions/cache@v2
  with:
    path: c:\deps2019\install
    key: ifm3d-2019-deps-3
Received 51160607 of 51160607 (100.0%), 52.0 MBs/sec
Cache Size: ~49 MB (51160607 B)
C:\windows\System32\tar.exe -z -xf D:/a/_temp/b1a1167c-1fae-4bb8-b0c0-c55230d24cd4/cache.tgz -P -C D:/a/ifm3d/ifm3d
c:/deps2019/install/: Can't create '\\\\?\\c:\\deps2019\\install'
c:/deps2019/install/bin/: Can't create '\\\\?\\c:\\deps2019\\install\\bin'
c:/deps2019/install/cmake/: Can't create '\\\\?\\c:\\deps2019\\install\\cmake'
c:/deps2019/install/etc/: Can't create '\\\\?\\c:\\deps2019\\install\\etc'
c:/deps2019/install/googletest/: Can't create '\\\\?\\c:\\deps2019\\install\\googletest'
```
The path for populating is ```D:/a/ifm3d/ifm3d``` where as path provided is ```c:\deps2019\install``` 

is it a issue of creating folder or file on C drive 

with action/cache@v1.0.3  and Windows server 2016, above is able to find the cache populate in C: drive, step is also shows success.

I also notice that on windows server 2016 the tar is usedfrom ```c:\Program Files\git\bin```, where as on windows server 2019  it is in ```c:\windows\system32\```

**Comment by Makaiza** [comment]
Very good

**Comment by pdotl** [comment]
Hi @inbangsa @Makaiza can you try using `cache@v3` and see if it works for you? If not, kindly share workflow logs so we may look into this.
