### ISSUE TITLE
"Post" step should print the key if upload was successful

### ISSUE THREAD

**Issue by jimis** [actions/cache#523]
In order to debug issues of not finding cache, it would help to know the exact key that the cache was previously uploaded with. 

Currently the only info printed in the "post" step is:
```
Post job cleanup.
/usr/bin/tar --posix --use-compress-program zstd -T0 -cf cache.tzst -P -C /home/runner/work/repo/repo --files-from manifest.txt
Cache saved successfully
```

**Comment by jimis** [comment]
It seems a logging line is missing in file `save.ts`, in case upload was successful

https://github.com/actions/cache/blob/354332455a7a9ae5492723ca9d4d082484e173bc/src/save.ts#L43-L46

**Comment by konradpabjan** [comment]
This should now be logged with changes here: https://github.com/actions/cache/pull/509

**Comment by jimis** [comment]
Thanks, it works!
