### ISSUE TITLE
Major version tag v2 not updated after v2.1.4 release

### ISSUE THREAD

**Issue by s-weigand** [actions/cache#528]
We just got an update PR from `dependabot` which wanted to update `v2` to `v2.1.4`, which is why I saw that `v2` still points at `v2.1.3`. Just wanted to inform you that this might have slipped after the release.

**Comment by aviau** [comment]
See https://github.com/actions/cache/issues/527#issuecomment-774152927

**Comment by konradpabjan** [comment]
That is correct! Pinning this also for visibility. Not sure how long it will take to get a fix out for the `gstar` issue

**Comment by s-weigand** [comment]
Thanks for the info 😄

**Comment by konradpabjan** [comment]
Still not pointing to `v2`, but small update regarding possible resolution: https://github.com/actions/cache/issues/527#issuecomment-815905807

**Comment by dhadka** [comment]
Issue with https://github.com/actions/cache/issues/527 is resolved and `@v2` is updated to the latest release `@v2.1.5`.  Closing.
