### ISSUE TITLE
decompression too slow on Windows

### ISSUE THREAD

**Issue by arvinxx** [actions/cache#529]
I run the same job on Linux, macOS & Windows.

 And while macOS & Linux take less than 1 minutes when in cache step, Windows takes almost 4~5 minutes.

Here it is my workflow https://github.com/arvinxx/umi-electron-template/runs/1843911964?check_suite_focus=true#step:4:10

I notice there is another issue #442  mentioned same problem, but no one answer this official.

So is there anyone to deal with it?

**Comment by abhi1693** [comment]
Same for me too. Downloading the cache is way slower than actually installing node packages.

Download Cache: 35 mins

Without cache step, the entire workflow takes 6 mins

At this point, I'm not even sure why I would need caching

**Comment by ilyamt-tandemg** [comment]
Same here. We are using a Windows-based self-hosted runner and the download speed from the cache may be as low as 0.2 MBs/sec
