### ISSUE TITLE
Pull-Requests evicting cache from master

### ISSUE THREAD

**Issue by mayeut** [actions/cache#534]
It seems that PR can evict cache created on master (or other repo branches for that matter).
I don't know whereas to call this a feature or a bug, and, without any UI feature to check how cache storage is used, I really don't know wether what seems to happen is indeed happening or not.

Affected repo: https://github.com/pypa/manylinux, caching docker buildx

Other opened issues which seem they could help in that situation:
- #105 Inspecting the cache
- #2 Clear cache
- #432 / #342 Overriding cache

**Comment by s25g5d4** [comment]
Hi there, I would like to know if there's any update on this. Is it still valid? Is there any way to protect the cache generated from the default branch from being evicted by builds from other branches?

**Comment by lhotari** [comment]
I have a similar question. 

The question is about the quota that caches for pull requests consume. When a pull request build uses GitHub Actions Cache, is the quota consumed from the upstream repository where the Pull Request was created, or does the pull request build consume the quota of the forked repository?

I have posted the question in GitHub Community forum for GitHub Actions: https://github.community/t/how-does-the-github-actions-cache-size-limit-work-for-pull-requests/240546/3 . 

Could someone from GitHub answer this question? 
It would be great to have this explained in the documentation at https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy .

Thank you

**Comment by dhadka** [comment]
@lhotari Left a reply to your GitHub Community question - https://github.community/t/how-does-the-github-actions-cache-size-limit-work-for-pull-requests/240546/6

**Comment by dhadka** [comment]
To answer the original question in this issue, there is no priority given to certain branches (`e.g., `main`) nor is there a way to set such a policy.  It's based entirely on usage.  Caches that are used more frequently will tend to survive eviction.

As for being able to inspect the cache, there are plans to support this.  The public roadmap issue - https://github.com/github/roadmap/issues/472 - can be used to track progress and the timetable.  It looks like a few days ago we shipped the API for this capability - https://github.blog/changelog/2022-03-17-view-cache-usage-in-your-action-workflows/.

I'm going to close this issue as the questions are answered, but please feel free to re-open or file a new issue if you have any other questions or concerns.

**Comment by bishal-pdMSFT** [comment]
@lhotari Not only that, now you can use API to get the list of caches, their sizes and which refs(branches) are they for. https://github.blog/changelog/2022-06-27-list-and-delete-caches-in-your-actions-workflows/.
Hope this helps to create more transparency. Feedback welcome.
