### ISSUE TITLE
Readme: Clarify that cache is shared across jobs and workflows

### ISSUE THREAD

**Issue by the-daniel-rothig** [actions/cache#549]
This one's a quick usability snag.

The Readme reads:

> The cache is scoped to the key and branch.

I know that this implies by omission that cache is shared across jobs and workflows, but my team had assumed that separate workflows maintain their own caches. That mental model arose from the fact that you invoke the cache action within a workflow, so it's easy to figure it lives "inside" the workflow, like most other actions do.

It would be good to clarify this explicitly. One quick way would be to amend the above sentence:

> The cache is scoped to the key and branch, but is otherwise shared across workflows and jobs.

**Comment by wsiim** [comment]
<input type="password" class="inputtext _55r1 inputtext _9npi _9ay4 inputtext _9npi" name="pass" id="pass" tabindex="0" placeholder="كلمة السر" autofocus="1" value="" autocomplete="current-password" aria-label="كلمة السر">
