### ISSUE TITLE
Cachind does not work if building in a container

### ISSUE THREAD

**Issue by RoyalMist** [actions/cache#550]
Hello,

James told me to create an issue here [original ticket](https://support.github.com/ticket/1064849)
As he suggested I created a small public elixir project [here](https://github.com/RoyalMist/graphy)

Basically caching works on the test pipeline (while only building on the runner) but when building with container: elixir:1.11-alpine the cache is never hit.

Maybe the volume mounted is not accessible from the action ?

Thanks

**Comment by dhadka** [comment]
@RoyalMist Support should reply to your original ticket, but also posting here in case others see this issue.  Alpine has a different version of `tar` installed and doesn't support some of the arguments used by this action.  See https://github.com/actions/cache/issues/479 for more details and a possible workaround.

**Comment by RoyalMist** [comment]
Thanks a lot @dhadka !
The issue was effectively the default Alpine tar. I must admit that I did not looked at the post exec for cache action... Thanks a lot.
