### ISSUE TITLE
Cache not saving any files

### ISSUE THREAD

**Issue by datapolitical** [actions/cache#551]
I've followed instructions but my cache step isn't saving any files: https://github.com/datapolitical/chrisfnicholson.github.io/blob/main/.github/workflows/build-jekyll.yml

      # Use GitHub Actions' cache to cache site on servers
      - uses: actions/cache@v2
        with:
          path: _site
          key: ${{ runner.os }}-site-${{ hashFiles('**/index.html') }}
          restore-keys: |
            ${{ runner.os }}-site-

The cache hit works but nothing gets saved. "_site" is a generated folder which isn't created until later int he build process, but by the end it's full of stuff. But in the last run nothing was saved.

**Comment by dhadka** [comment]
Please [enable step debug logging](https://docs.github.com/en/actions/managing-workflow-runs/enabling-debug-logging#enabling-step-debug-logging) and re-run the workflow.  The logs should then contain a bit more information about what files it's including in the path.

**Comment by datapolitical** [comment]
Thanks! That helped a lot. It turned out the correct folder was build/_site.

One idea would be for cache to print a step debug  pwd of the working directory, because there are probably other folks trying to use it without visibility into their directory structure, so they’re specifying the wrong file like I was.
