### ISSUE TITLE
Print information on when cache was rebuilt

### ISSUE THREAD

**Issue by solodon4** [actions/cache#552]
When a cache gets finally rebuilt, a lot of things could have changed under the hood, like the recent update of ubuntu-latest to 20.04 etc. When this does happen and cache rebuild fails, I would like to be able to compare logs of the failed run and the last successful one when the cache was built. The problem is that I have no idea when the cache was rebuilt and clicking on every workflow run is very tedious.

I was wondering if on cache hit you guys can print the workflow ID or at least the date when that particular cache was built? Also please let me know if there is an easier way to figure this out in the mean time.

Thank you!

**Comment by dhadka** [comment]
:wave: The creation time can be seen after [enabling step debug logging](https://docs.github.com/en/actions/managing-workflow-runs/enabling-debug-logging#enabling-step-debug-logging), for example:

```
##[debug]Cache Result:
##[debug]{"scope":"refs/heads/master","cacheKey":"test-Linux-686805495","cacheVersion":"244d0bd9247068acc48c2c06388b128d9254051f65bbefcb41691a0b57996cdf","creationTime":"2021-03-25T14:19:14.5366667Z","archiveLocation":"***"}
```

**Comment by solodon4** [comment]
Thanks for the tip @dhadka! After enabling step debug logging I was indeed able to find a date, but I believe I was lucky that my cache wasn't gone yet, so I could just return to that cache name and see that info on next run. Should that cache been gone by then, as I was experimenting under a new cache name where I was trying to build everything on 20.04, I wouldn't have been able to retrieve it. This is why I would like the information about cache creation date and/or workflow ID be printed always, so that I can retrieve it when needed even if the cache is long gone. The date of creating wouldn't change with time, so this should not affect any determinism GitHub runner might care about.
