### ISSUE TITLE
Allow to store cache even if the job DOES NOT complete successfully

### ISSUE THREAD

**Issue by fulldecent** [actions/cache#574]
In the documentation it states:

> If the job completes successfully, the action creates a new cache with the contents of the path directory.
>
> https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows

Please consider to loosen this restriction so it is possible to save cache results even of a failing job.

In my case, I am using CI to test a website. Hyperlinks are checked using HTMLProofer and cached to avoid checking a known-existing page too frequently.

Broken links cause the job to fail (happy about this). But then that also causes the checked links not to be saved into cache (want to change this).

And so I would like this to not be skipped.

<img width="1143" alt="Screen Shot 2021-04-27 at 13 22 43" src="https://user-images.githubusercontent.com/382183/116285013-b8400d00-a75b-11eb-88cb-159fc859a2e2.png">

---

More information:

https://github.com/gjtorikian/html-proofer#caching-with-travis

On Travis we used to use to achieve these: 

```yaml
cache:
  directories:
  - $TRAVIS_BUILD_DIR/tmp/.htmlproofer
```

**Comment by fulldecent** [comment]
Workaround:

On your testing step use like `rake test || true`

**Comment by jkflying** [comment]
I also want this feature, but instead for caching of expensive, infrequently changing build artifacts in C++ builds. This means that if something early in the build breaks something late in the build, the entire thing doesn't get cached even though the fix might only affect later items.

**Comment by konradpabjan** [comment]
Closing as a duplicate https://github.com/actions/cache/issues/272
