### ISSUE TITLE
zstd is required for cache restore (cache miss on Windows and on self-hosted runners)

### ISSUE THREAD

**Issue by rfay** [actions/cache#580]
In v2, zstd is required for a cache restore. 

That means that all self-hosted runners that don't have zstd installed will simply give a cache miss on trying to restore. No explanation.

There are a number of issues here:

1. Since zstd is required, fail on cache restore if zstd is not found.
2. Since gnu tar is required (apparently) to use zstd, fail if gnu tar is not found.
3. Add the requirement of zstd to the README
4. Don't output that it's a cache miss when it's not at all a cache miss but rather an inability to untar it.

**Comment by Phantsure** [comment]
Requirement of posix compliant tar is in README. Would that not include zstd automatically? If not, then let me add that.

**Comment by sammcj** [comment]
Posix compliant tar doesn't mean that you've installed the zstd libraries - this is a separate package usually called `zstd` on Ubuntu and CentOS based distros.

**Comment by rfay** [comment]
Since I had to go through this entire process again with a new runner, I added these notes to the GitHub Workflow:

> This Windows self-hosted runner has to be set up with gnu tar and zstd.exe, or
this step will fail to properly create the cache.
> Make sure gnu tar is the tar used here. System PATH should have C:\program files\gnu\usr\bin near top
> Get zstd.exe from https://github.com/facebook/zstd/releases - I put it into C:\program files\gnu\usr\bin
> so it would be in PATH
> See https://github.com/actions/cache/issues/580
> Run the Windows action with debug enabled to be able to see which tar is in use, etc.

**Comment by pdotl** [comment]
👋 @rfay, We have added the `zstd` requirement to documentation when using self-hosted runners [here](https://github.com/actions/cache/blob/main/workarounds.md#improving-cache-restore-performance-on-windowsusing-cross-os-caching). Closing this issue. Feel free to reopen if you have followup questions.
