### ISSUE TITLE
Status of the project and open PRs

### ISSUE THREAD

**Issue by matu3ba** [actions/cache#583]
Dear github maintainer,
there are PRs open since March 2020: https://github.com/actions/cache/pulls?page=2&q=is%3Apr+is%3Aopen

Please either remove the examples completely, if you dont plan to support them or merge/close the open PRs.
Ideally write a warning that the examples are not maintained and one should conduct the build system (of the language) as authoritative.

Its quite annoying to use wrong examples, in my case from Rust.

The current status makes me wonder how big the reliability standards of github are, when github does not manage to supervise (minimal) examples.

Best regards, Jan

**Comment by vsvipul** [comment]
Hi, we are looking into the issues/PRs actively and have a plan to bring down the number of issues/PRs in the coming months. Closing this for now. Thank you for opening.
