### ISSUE TITLE
Can't cache yarn properly

### ISSUE THREAD

**Issue by mleszcz** [actions/cache#589]
At the 2nd build it only restores the cache partially (which takes 30 seconds):

![Screenshot from 2021-05-18 11-47-48](https://user-images.githubusercontent.com/72438/118631491-d683b080-b7cf-11eb-8a06-55a15cd16688.png)

![Screenshot from 2021-05-18 11-48-03](https://user-images.githubusercontent.com/72438/118631497-d8e60a80-b7cf-11eb-9e32-7063a3d75b7e.png)

Any ideas?

**Comment by mleszcz** [comment]
This solution resolved our problem https://docs.cypress.io/guides/continuous-integration/github-actions#Caching-Dependencies-and-Build-Artifacts

**Comment by dhadka** [comment]
@mleszcz Great to hear you found a solution.  Could you please provide a before and after of your cache step configuration?  Curious to see what needed to be changed.  Thank you!
