### ISSUE TITLE
 Cross-OS caching: Cache in Ubuntu + OS matrix = no hit in Windows

### ISSUE THREAD

**Issue by eirikb** [actions/cache#591]
Hi. This issue is manually copied from https://github.com/actions/virtual-environments/issues/3424 .
Could be related to https://github.com/actions/cache/issues/144 .
[This comment](https://github.com/actions/virtual-environments/issues/3424#issuecomment-844809242) by @maxim-lobanov is very interesting, and might explain why I'm having problems.  

----
### Original issue text

**Description**  
Trying to pass data between jobs using cache.  

I'm currently using artifacts, but I don't need these files to be available for download, and it seems artifacts are slower (more upload/download), so I would like to use cache instead.  
I use multiple OSes, but Windows does not seem to be able to see caches from Ubuntu.  
The other way around is also true, Ubuntu can't see caches from Windows.  
MacOS can see both.

**Area for Triage**:  
Scripting and command line

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Image version**
2.278.0

**Expected behavior**  
Cache hit in Windows

**Actual behavior**  
No cache hit in Windows

**Repro steps**  
Cache from Ubuntu, can not be read by Windows:
https://github.com/eirikb/gradlex-test/runs/2623752327?check_suite_focus=true  
![image](https://user-images.githubusercontent.com/241706/118875600-88180400-b8ec-11eb-96a5-5dd41b2c2291.png)

Cache from Windows can not be read by Ubuntu:
https://github.com/eirikb/gradlex-test/runs/2623807942?check_suite_focus=true
![image](https://user-images.githubusercontent.com/241706/118875652-9b2ad400-b8ec-11eb-992a-924f07c63f37.png)

I could understand if this had something to do with runners in different environments or something, but isn't caches stored elsewhere, and why can MacOS see both?

**Comment by dhadka** [comment]
@eirikb @j-boivie Yes, this is due to a bug using `zstd` and BSD `tar` on Windows.  You can fix this by adding GNU tar to the system path before running the cache step - see https://github.com/actions/cache/issues/576#issuecomment-830796954 for an example.

We plan to make GNU tar the default on Windows, but in the meantime I would recommend the workaround above.  This fix is being tracked by https://github.com/actions/toolkit/issues/552.

**Comment by eirikb** [comment]
@dhadka Thank you. I've verified the workaround works. I'll close this issue since this is already being tracked.

For anyone stumbling over this issue, the workaround including OS matrix. looks like this:
```yml
    steps:
      - name: "Use GNU tar instead BSD tar"
        if: matrix.os == 'windows-latest'
        shell: cmd
        run: echo C:\Program Files\Git\usr\bin>>"%GITHUB_PATH%"
      - uses: actions/cache@v2
        with:
          path: hello
          key: hello
```
