### ISSUE TITLE
Caching between jobs on different operating systems

### ISSUE THREAD

**Issue by ja-nick** [actions/cache#592]
Should it be possible to reuse a cache between two jobs in the same workflow?

I have a simple repro [here](https://github.com/nickcox/CacheTest/actions/runs/862434951) where it doesn't work as I expected.

Job one runs on Windows, writes something to disk and caches it by git SHA with the following output:

```
Post job cleanup.
C:\Windows\System32\tar.exe --posix -z -cf cache.tgz -P -C D:/a/CacheTest/CacheTest --files-from manifest.txt
Cache Size: ~0 MB (204 B)
Cache saved successfully
Cache saved with key: cacheBySha-a39034b9e016cac5958a16d50caab0b2789bb117
```

Job two runs on Linux, is dependent on job one and attempts to use the cached file but fails because the cache hasn't been restored, even though the key is the same.

```
Cache not found for input keys: cacheBySha-a39034b9e016cac5958a16d50caab0b2789bb117
```

If I run both jobs on the same OS then everything works as expected. But, as I understand it, the cache isn't supposed to care about the current OS?

**Comment by dhadka** [comment]
@ja-nick Please see this comment for an explanation and workaround: https://github.com/actions/cache/issues/591#issuecomment-845121153

**Comment by ja-nick** [comment]
Oh man. I could've have saved myself a bunch of time if I'd read through the closed issues properly. 🤦 

Perhaps we should consider adding a note to the docs to save anyone else the embarrassment?
