### ISSUE TITLE
Job hangs and fails while downloading segment

### ISSUE THREAD

**Issue by selimok** [actions/cache#593]
Hi,
We are experiencing an interesting problem while building our maven packages. The problem occurs at the actions/cache@v2 step. It hangs at ~90% of downloading progress and the job fails afterwards.

```
Received 1388314624 of 1560334310 (89.0%), 50.9 MBs/sec
Received 1447034880 of 1560334310 (92.7%), 51.1 MBs/sec
```
This is what I see as last and no trace of any error or warning messages in sight. 

I set then ACTIONS_STEP_DEBUG true and saw that the cache file is tried to be downloaded at this stage.
We have a runner instance with 2GB of ram and the cache file is about 1.4GB. I monitored live the memory usage while the job downloading the cache file and the free memory is reached to the bottom at ~35Mb. This means the downloaded file remain in memory until it completely downloaded and doesn't written into the hard drive. After increasing the instances memory size to 4GB, the problem is gone.

I think the download logic should use a smaller buffer and then write downloaded file part into the disk to avoid this issue. 

Kind Regards
Selim

**Comment by selimok** [comment]
After some research I found the download logic originates from the toolkit project. 

https://github.com/actions/toolkit/blob/d972090333aaa079cb291d48f8556e8dc051d996/packages/cache/src/cache.ts
https://github.com/actions/toolkit/blob/566ea66979eda65c2ca3661f251a7f1edbda5bda/packages/cache/src/internal/downloadUtils.ts

Should I create the issue on that project?

**Comment by fl250144** [comment]
i have the same problem happening randomly every single day
