### ISSUE TITLE
How long does the cache expire

### ISSUE THREAD

**Issue by cordova2009** [actions/cache#613]
How long is the cache ?
how to set

**Comment by affonso-rafael** [comment]
Docs says:
> A repository can have up to 5GB of caches. Once the 5GB limit is reached, older caches will be evicted based on when the cache was last accessed. Caches that are not accessed within the last week will also be evicted.

**Comment by hurrycaner** [comment]
Can someone close this?

**Comment by Phantsure** [comment]
> Docs says:
> 
> > A repository can have up to 5GB of caches. Once the 5GB limit is reached, older caches will be evicted based on when the cache was last accessed. Caches that are not accessed within the last week will also be evicted.

@cordova2009 Size is increased to 10GB. Rest remains same. Closing this issue, you may reopen if you seek more clarity
