### ISSUE TITLE
docs: caching node_modules vs cache directory

### ISSUE THREAD

**Issue by jjangga0214** [actions/cache#620]
The docs guides to cache `.npm` or `$(yarn cache dir)` for nodejs. 

[Node - npm](https://github.com/actions/cache/blob/main/examples.md#node---npm)
[Node - Yarn](https://github.com/actions/cache/blob/main/examples.md#node---yarn)

This lets people _feel_ it the "RIGHT" way to cache node dependencies, without clearly explaining whether caching `node_modules` directly is not recommended. 

I want to know 1) if this is a wrong impression or not and 2) why. 

Thanks!

**Comment by Arxcis** [comment]
Yes. I would like to know the answer here as well. From experience caching `node_modules/` saves a lot more time, than just caching `$(yarn cache dir)` :thinking:

**Comment by benjimin** [comment]
There are some answers on [stackoverflow](https://stackoverflow.com/questions/42521884/should-i-have-travis-cache-node-modules-or-home-npm). Agree docs could explain slightly more.

Presumably raw caching the actual installation may be fragile to changes occurring elsewhere in the environment, whereas npm provides some version management over its own supported cache (it can decide to invalidate some of those contents)?

**Comment by benjimin** [comment]
Docs should include a brief explanation, that caching the downloaded packages (the cache dir) facilitates the package manager (npm) overriding parts of the cache in a granular manner as necessary. Caching the actual installation dir would be much more performant (skipping some steps) but unreliable as the install could spontaneously break (e.g. if a dependency among the system libraries gets upgraded to an incompatible version, while still hitting the old cache).

**Comment by vsvipul** [comment]
@benjimin Would you be willing to open a PR for that?

**Comment by vsvipul** [comment]
This has already been added to Node example at https://github.com/actions/cache/blob/main/examples.md#node---npm . Hence, going ahead and closing this. Thank you for opening this issue.
