### ISSUE TITLE
Caching fails on IPv6 runner with ENETUNREACH

### ISSUE THREAD

**Issue by ohsayan** [actions/cache#623]
Caching fails on a self-hosted runner that is on a host with IPv6. You can find the relevant logs here: https://github.com/skytable/skytable/runs/3291168297?check_suite_focus=true#step:4:10

**Comment by vsvipul** [comment]
@ohsayan This appears to be a network issue instead of cache issue. Did it happen only once and or are you still facing this. If you are, please feel free to reopen this issue with more details.
