### ISSUE TITLE
Allow using the cache for other than push and pull_request events

### ISSUE THREAD

**Issue by Xilonz** [actions/cache#63]
When triggering my action with `on: ['deployment']`.  It throws a warning about having no read permissions. 

It doesn't happen with `on: push`.

```
##[debug]Resolved Keys:
##[debug]["Linux-yarn-...hash...","Linux-yarn-"]
##[debug]Cache Url: https://artifactcache.actions.githubusercontent.com/...hash.../
##[warning]No scopes with read permission were found on the request.
::set-output name=cache-hit,::false
```

**Comment by jahed** [comment]
Saw a similar warning for [one of my **scheduled** workflows](https://github.com/jahed/node-terraform/commit/df5413194663618e77730ec8f55f7dc913985629/checks?check_suite_id=298460992). The same workflow ran fine 2 days ago (November 4). It failed yesterday too (November 5) so may be an issue on GitHub's end. Possibly the way permissions are granted to use the cache.

**Comment by joshmgross** [comment]
The cache is currently limited to `push` and `pull_request` events. We're looking into opening it up to more event types in the future.

I've filed an issue internally to get the [docs](https://help.github.com/actions/automating-your-workflow-with-github-actions/caching-dependencies-to-speed-up-workflows) updated with this information.

**Comment by jahed** [comment]
That makes sense. The runs that did work for me were triggered on `push`.

Instead of updating documentation, may I suggest improving the error message? To say that the action is not supported on the event that triggered it. Saves people having to dig through documentation for special cases.

**Comment by Ignigena** [comment]
Definitely would love to see this open up to other event types, particularly `deployment` and `deployment_status`. Our workflow is running smoke tests after a deployment happens. Since we can't use the caching action it takes a few minutes to download and install the necessary dependencies every time it's run.

Being able to cache this like we do with our `push` and `pull_request` events would save a ton of time.

**Comment by joshmgross** [comment]
Since this issue has all the context, I've changed it to focus on us opening the cache up for more events. Thanks for the feedback!

I'm tracking the confusing error message here: https://github.com/actions/cache/issues/64

**Comment by nikolaeu** [comment]
`repository_dispatch` would be really nice to have covered as well :)

**Comment by chemitaxis** [comment]
Hi @joshmgross yes please, open to other events likes `on: ["deployment"]`

We are using this workaround in this moment, but caching is not working...

https://github.community/t5/GitHub-Actions/GitHub-Actions-Manual-Trigger-Approvals/td-p/31504

Thanks!!

**Comment by jasonkarns** [comment]
Would it be possible to revert to the previous behavior where this was only a warning instead of an error? All my usages of the cache are an optimization to make the job run faster. A cache miss (or in this case, skipping the cache lookup entirely due to unsupported event type) can be safely ignored and continue without the cache optimization.

**Comment by joshmgross** [comment]
@jasonkarns Yep, we're fixing that. Apologies for the break.

Fixing it here: https://github.com/actions/cache/pull/108

For a temporary workaround, you can use the previous version of the action with
```yaml
uses: actions/cache@v1.0.1
``` 
or use an `if` statement like so:
```yaml
    - name: My Cache
      if: github.event_name == 'push' || github.event_name == 'pull_request'
      uses: actions/cache@v1
      with:
        path: .github
        key: ${{ runner.os }}-github
```

**Comment by lightswitch05** [comment]
I have a cron-based action that could benefit greatly from caching: [auto-updates.yml](https://github.com/lightswitch05/php-version-audit/blob/master/.github/workflows/auto-updates.yml#L4-L6)

**Comment by chemitaxis** [comment]
@lightswitch05 can you please explain the workflow? Thanks

**Comment by lightswitch05** [comment]
Sure. [PHP Version Audit](https://github.com/lightswitch05/php-version-audit) self-updates twice a day using an [auto-updates.yml](https://github.com/lightswitch05/php-version-audit/blob/master/.github/workflows/auto-updates.yml#L4-L6) action. The update function requires a lot of file downloads, and so was designed to make use of heavy caching. Along with the dependency install before the self-update can run, the action would benefit from cache support.

**Comment by bluelovers** [comment]
ope can support schedule

**Comment by Hvass-Labs** [comment]
I would also like to use cached pip install for cron scheduled daily testing of Jupyter Notebooks : https://github.com/SimFin/simfin-tutorials/blob/master/.github/workflows/test.yml

I currently get this message in GitHub Actions: `[warning]Event Validation Error: The event type schedule is not supported. Only push, pull_request events are supported at this time.`

Thanks!

**Comment by mikkelbd** [comment]
Would love to see caching support for `deployment` events. Any update on this issue and maybe a rough ETA? 🙏 😄

**Comment by steel** [comment]
Yes. Please have this support a `repository_dispatch` event. We're using this as a mechanism to trigger a build on master.

**Comment by Yikun** [comment]
The cache support bring 80%+ improvement in my workflow, I'd like to see the `schedule` can be supported.🙏

**Comment by localheinz** [comment]
Any news on getting support for other events as well?

This would significantly speed up deployments decoupled from actual pushes by configuring workflows that listen to `deployment` events!

🤓 

Let us know if there is anything we can do to help!

**Comment by craig-day** [comment]
I'm curious why only push and pull_request events are cached? Is there a system limitation, or just not implemented yet? I would be happy to take a stab at implementing caching for more event types if bandwidth is the problem.

**Comment by simonw** [comment]
I wrote about my desire for this feature on my blog: https://simonwillison.net/2020/Apr/14/datasette-clone/

I use scheduled actions to update SQLite databases: step 1 is to download the existting DB file, step 2 updates it, step 3 publishes it again if it has changed. I'd like to be able to use caching to skip that initial download!

**Comment by aiqiaoy** [comment]
The PR to allow all events to access cache is merged into `master`. It will be released as part of cache v2. We are targeting releasing v2 later this month. 

You can ping to `actions/cache@master` to preview this feature.
