### ISSUE TITLE
Yarn cache restore not working in private repository

### ISSUE THREAD

**Issue by tbhaxor** [actions/cache#630]
I have a private repo and using yarn cache from actions. The post-action always shows it has uploaded the cache but the restore action doesn't find any. 

I haven't changed my yarn.lock, so it should restore the cache either way

![image](https://user-images.githubusercontent.com/28386721/131273639-3fef19f6-be09-4cd7-afb3-a73bf08d014f.png)

**Comment by slavafomin** [comment]
I'm experiencing the same behavior. The cache is created and uploaded in one job, but can't be found in another.

**Comment by slavafomin** [comment]
I would suggest to check your `path` argument, please see [this issue](https://github.com/actions/cache/issues/572) for more details. Maybe it relates to your case.
