### ISSUE TITLE
GitHub Actions: Cache Mangement

### ISSUE THREAD

**Issue by ahdbilal** [actions/cache#632]
The GitHub Actions team is considering adding cache management capability, which will enable viewing and deleting cache entries.  We’d greatly appreciate it if you can complete a [2-min survey](https://docs.google.com/forms/d/e/1FAIpQLSf00jDi0KszW5NFGLe7gfjfO1Pik1BAURsdciC2S5ULAFUtfw/viewform) to provide us your feedback! 

Thank you

**Comment by N-Usha** [comment]
## Actions Cache Usage API is now LIVE

You can now monitor the storage usage of your existing caches and get greater control over cache availability for your action workflows.

Actions users who use [actions/cache](https://github.com/actions/cache) to speed up their workflow execution times can now use our [cache usage APIs](https://docs.github.com/en/rest/reference/actions#cache) to:

- query the cache usage within each repository and monitor if the total size of all caches is reaching the upper limit of 10 GB,
- monitor aggregate cache usage at organization level or even at enterprise level, if your GitHub organization is owned by an enterprise account.

Learn more about [Managing caching dependencies to speed up workflows](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#managing-caches).

There’s more in store for Cache Management as we plan to also support view and delete cache functionalities.

**Comment by N-Usha** [comment]
## List and delete cache APIs are now available for managing your Actions Cache

You can now get more transparency and control over dependency caching in your actions workflows using our [cache list and delete APIs](https://docs.github.com/en/rest/reference/actions#cache) to:

- list all the Actions caches within a repository and sort by specific metadata like cache size, creation time or last accessed time.
- delete a corrupt or a stale cache entry by providing the cache key or ID.

We believe with the cache usage APIs that we shipped earlier and these new List & delete APIs, Cache management within GitHub workflows would be super seamless. 

And thats not it... we are also plan to enrich these experiences further by adding support for these in both GitHub CLI as well as UI.

Learn more about [Managing caching dependencies to speed up workflows](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#managing-caches).

**Comment by N-Usha** [comment]
### Now manage Actions cache from your terminal with the new [GitHub CLI extension for cache](https://github.com/actions/gh-actions-cache#readme):  📢 📢 

    gh extension install actions/gh-actions-cache 
This extension is built on top of [GitHub APIs for cache management](https://docs.github.com/en/rest/actions/cache)

**Comment by bishal-pdMSFT** [comment]
📢 Cache management is not much simpler with ability to list cache metadata and delete cache for a repo. Additionally, Org admins can view usage across repos.
[Managing caches](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#managing-caches)
[Managing caches for organizations](https://docs.github.com/en/organizations/managing-organization-settings/disabling-or-limiting-github-actions-for-your-organization#managing-github-actions-cache-storage-for-your-organization)
