### ISSUE TITLE
Unsupported event types should be blocked as verification errors

### ISSUE THREAD

**Issue by joshmgross** [actions/cache#64]
Currently, only `push` and `pull_request` events work with the cache service, other events will fail server authorization with an error like "No scopes with read permission were found on the request."

We should check the event (from env variable `GITHUB_EVENT_NAME`) and provide a more helpful error message when the event is not supported.

**Comment by dmyers** [comment]
Did this recently change? It wasn't causing my builds to fail or `release` event types until just now and even had workflow jobs successfully finish this morning and it just recently stopped.
