### ISSUE TITLE
Restoring from a GitHub cache locally

### ISSUE THREAD

**Issue by boardfish** [actions/cache#648]
Is it possible to download the contents of a cache by key in your local environment?

My use case is with [Crystalball](https://github.com/toptal/crystalball), we're generating maps for the `main` branch in CI, then caching and using them on PR branches. But they'd also be useful to have to hand locally so that you're always using up-to-date maps regardless of when you switch between branches.

**Comment by Phantsure** [comment]
Currently cache can't be downloaded locally.

**Comment by Phantsure** [comment]
Hope that resolves your query
