### ISSUE TITLE
An output for exact cache hit

### ISSUE THREAD

**Issue by laughedelic** [actions/cache#661]
I think it would be useful to indicate somehow whether cache was restored using the exact `key` or one of the fallback `restore-keys`. 

A use case for this is being able to skip some subsequent steps only in the case of an exact cache hit. For example, if a build tool uses incremental compilation, a partial cache hit is good, it saves _some_ time, but if the cache hit was exact, we can skip the compilation step altogether which might save us much more time (e.g. build tool loading the project). A concrete case of such build tool it [sbt](https://www.scala-sbt.org/): in a medium-sized project with several modules it might spend up to a minute loading the project.

So I'm suggesting to add another output value to the action which will indicate whether hit was exact or not.

**Comment by OndrejSpanel** [comment]
I think @laughedelic would like to check if the hit was on a primary key, or on a restore key. The primary key hit is "exact cache hit", while the restore key hit is "partial hit".

I think this often makes sense - when a restore key is hit, it means a not up-to-date version of the files is obtained, which is usefull, but is likely to need at least some updating (like calling `sbt update`)´, while on primary key you know everything is already up to date and you can skip any such steps.

**Comment by OndrejSpanel** [comment]
After reading the documentation again I think `cache-hit` is set to true only on the exact hit, not on the restore key hit. You are therefore not notified about a partial hit at all - it might speed up something or it might not, you are expected to proceed as if there is no hit.

> A boolean value to indicate an exact match was found for the key

This is confirmed by looking at sources:

```ts
            const isExactKeyMatch = utils.isExactKeyMatch(primaryKey, cacheKey);
            utils.setCacheHitOutput(isExactKeyMatch);
```

The documentation could perhaps be changed to explicitly state this, like:

_A boolean value to indicate an exact match was found for the key (not set when only a restore key matches)_

**Comment by jsoref** [comment]
`cache-hit` indeed is only true if you're hitting the primary key.

Unfortunately, you can't distinguish between a `cache-miss` and a hit of a `restore-key`.

I would love for `cache-hit` to tell me the key it hit instead of just a boolean for the primary key.

**Comment by bishal-pdMSFT** [comment]
Agree, two changes make sense:
1. Log the restore key for which the partial match happened.
2. Update doc to explicitly call out about `cache-hit`

Would love to see some PR contribution as it looks like a good first issue.

**Comment by jsoref** [comment]
Would you want it to use a different output, or can I reuse the current one?

Offhand, it feels like changing the existing output is probably an API break.

If you don't want the output reused, do you have an particular preference for an output name?

(Quite happy to make a PR, if it's likely to be accepted.)

**Comment by Kurt-von-Laven** [comment]
In the meantime, you should be able to detect a partial hit in many cases by virtue of the fact that the directory being restored isn't empty.

**Comment by jsoref** [comment]
Hostile 🤖, there is a PR for this

**Comment by andreasabel** [comment]
I think this issue should be closed, as you can do everything with `outputs.cache-matched-key`.
- if it is null, no cache was restored
- if it is not null, some cache was restored, either from the primary or a fallback key
- if it is equal to `output.cache-primary-key` we had an exact cache hit.

Please, no breaking API changes for a redundant feature!

**Comment by Kurt-von-Laven** [comment]
Not sure if I'm missing something, but adding a new output isn't a breaking change.

**Comment by jsoref** [comment]
I think they're saying that `${{ outputs.cache-matched-key == output.cache-primary-key }}` is conceptually equivalent to the requested feature.

(Fwiw, I don't think checking to see if the restored directory is empty is workable, as I think the directory doesn't need to start out empty, and iterating over a directory can be expensive, plus any operation that requires a step is problematic as the goal is to be able to do a `step` w/ an `if:`...)

**Comment by matthewhughes-uw** [comment]
> I think this issue should be closed, as you can do everything with outputs.cache-matched-key.

This output is only available for `actions/cache/restore` and not `actions/cache`. My use case is:

* I have a general 'build' step that downloads+builds all dependencies. There are several other steps that can read from this cache without needing to write anything extra. This is keyed on language version + hash of dependency file
* I have a 'test' step that wants to read from this cache but also write some extra bits (test build artifacts, test results etc.). I want to write these to a separate cache. This is keyed on same as above, but + github ref so each PR gets its own copy of this cache with restore keys that can match about anything

So in my test job I want to:

* Try and fetch (and later save) any test cache that exists and, if that fails
* Try and fetch the general build cache

In the first step I might hit a non-primary key, but still download the cache, but then I have no way to know I shouldn't run the second step and hence download another cache into the same directories (which leads to a whole bunch of ugly errors about existing files)

I _could_ do this with separate invocations of `/save` and `/restore` but it would be convenient if it were available in the top-level action

**Comment by Kurt-von-Laven** [comment]
Could you branch on whether there are files in the path passed to `actions/cache`?
