### ISSUE TITLE
Recommend caching ~/.npm rather than node_modules

### ISSUE THREAD

**Issue by billyjanitsch** [actions/cache#67]
The readme currently provides [an example workflow](https://github.com/actions/cache/tree/4b0709a0d5bb7cd20f2ca9b9eb3dd620875faec9#example-workflow) that suggests caching a project's `node_modules` folder.

This is generally not recommended: see [here](https://docs.npmjs.com/cli/ci.html#example), [here](https://stackoverflow.com/questions/42521884/should-i-have-travis-cache-node-modules-or-home-npm), [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/?view=azure-devops#nodejsnpm), etc. It also doesn't integrate well with npm's suggested CI workflow -- which is to cache `~/.npm` and use `npm ci` -- because `npm ci` always removes node_modules if it exists so caching it strictly slows down the build.

For reference, Azure and Travis both cache `~/.npm` rather than `node_modules` by default.

Was this a conscious design decision? If not, would you consider revising the readme to suggest using the shared cache?

**Comment by joshmgross** [comment]
We'll update the example, thanks for the tip!

**Comment by FND** [comment]
I'm not sure whether this belong here, but GitHub's help pages still use `node_modules` as an example: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/caching-dependencies-to-speed-up-workflows#using-the-cache-action

Starting out, that's what I wanted to use as a reference until I - pretty much by accident - stumbled across this change. So it might be worth updating that article as well.

**Comment by joshmgross** [comment]
@FND Thanks! We're working on getting that doc example fixed, cc: @chrispat
