### ISSUE TITLE
Can I have a global cache option? Bundle cache not restored on different PRs, but working within the same PR

### ISSUE THREAD

**Issue by dinushkaherath** [actions/cache#692]
Issue:
If I create a new PR, the bundle cache is not restored from another branch, but if I push a new commit to the PR, the bundle gets restored in the new test. If then I create a new PR with that same new commit it looks for the same cache key but does not get restored

Diagnosis:
This is a general issue of GitHub Actions' cache, see the docs:
https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache
It seems to work based on whether the base branch (for a PR) or the default branch has a cache, it's not global per repository.

Solution:
Can I have a global cache option, I often have PRs that do not affect the cached ruby bundle, so it would be beneficial to have a global cache option

**Comment by danielcompton** [comment]
I think this is because cache access is scoped only to that branch or parent branches: https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows#matching-a-cache-key

I agree that having the option to restore a cache created on any branch would be great.

**Comment by georgepalmer** [comment]
Would love to see this - it would pretty much half our run time for actions on new branches

**Comment by dinushkaherath** [comment]
@georgepalmer my solution so far has been to add another workflow that only caches ruby bundle on push commit to master/main and any staging branch (takes about 30s if nothing to be done, and saves 5+ minutes on new PRs)

**Comment by bishal-pdMSFT** [comment]
@dinushkaherath @georgepalmer The idea behind branch scoping is to avoid cross-contamination, where a branch that hasn't undergone PR review is able to inject a cache that is subsequently consumed by say a main/release branch.

Unfortunately, yes it does restrict the power of caching. Let me know what your thoughts on this.
cc @N-Usha

**Comment by danielcompton** [comment]
@bishal-pdMSFT I think it'd be great if there was the ability to opt-in to cross-branch caching. For private repositories, cache poisoning is not a big concern.

If possible, it'd still be nice to be able to exclude Dependabot PRs from saving to a global cache key, as their source is untrusted.

**Comment by georgepalmer** [comment]
@bishal-pdMSFT echoing the above - I think the current behaviour is a sensible default but having the option to use a global cache would make sense for those that know it's safe for their repos.

As a quick aside I imagine this would save GitHub a lot on bandwidth each year if it was widely used

**Comment by milahu** [comment]
workaround: use github pages to cache binary artifacts https://github.com/milahu/sccache-bin/issues/1

**Comment by audunsolemdal** [comment]
> Yes, something like this can be done - may be even a repo/org level setting so that each workflow need not specify these options.
> 
> Having said that, this is not a trivial work and not urgent, hence will need to be added to our backlog to be triaged and planned. I will close this issue and move it to our backlog. I will come back once we have planned this item.

@bishal-pdMSFT any status update you could share publicly?
