### ISSUE TITLE
Need a way to update/remove cached files

### ISSUE THREAD

**Issue by jelmd** [actions/cache#697]
Right now there is no way to either update or remove a cached archive. Wasting a lot of compute time to re-compute the archive is a pretty dumb workaround (in our case ~20 min, size ~1.3 GiB). Instead it should be possible to fetch the cached archive, to modify its content as needed, to set an env variable to signal, that the cached archive needs to be re-packaged and uploaded again. ...

**Comment by vsvipul** [comment]
This is an active feature request and is being tracked in https://github.com/actions/cache/issues/2 . Hence, closing this. You can continue the conversation for this there.
