### ISSUE TITLE
Documentation: README is insufficiently clear on how path expansions work on Windows

### ISSUE THREAD

**Issue by phlummox** [actions/cache#705]
From experimentation, it seems that when this action is used for the Windows OS, a path containing a Windows environment variable (like `%LocalAppData%\Programs\stack`) will result in errors (e.g. in one of my projects, I get the error "`could not chdir to 'C:\sr\n%LOCALAPPDATA%\Programs\stack'`"), but tilde expansions (like `~\AppData\Local\Programs\stack`) *will* work (despite the tilde not being a character that is normally expanded on Windows).

I think this is not adequately documented in the [README][readme]: it is very unusual behaviour on the Windows platform, and should be documented prominently. Something along the lines of: "**PLEASE NOTE**: **Windows environment variables (like `%LocalAppData%`) will NOT be expanded by this action; use `~\AppData\Local` instead.**").

[readme]: https://github.com/actions/cache/blob/f7a7367bb2fbf795798facf25c64844be523edde/README.md

(For that matter, the [glob][glob] action is not especially well documented either. It says that "~ *may* expand to /Users/johndoe" [my emphasis] - what on earth is that supposed to mean? The documentation  should say precisely what the action *does* do, and in what circumstances, not what it *may* do.)

[glob]: https://github.com/actions/toolkit/tree/main/packages/glob

**Comment by vsvipul** [comment]
@phlummox  Would like to open a PR to add this to the docs? For the glob change, please open an issue in the[ toolkit repo.](https://github.com/actions/toolkit)

**Comment by phlummox** [comment]
Vipul: documentation is supposed to document the *intended* behaviour of a piece of software. As an outsider to this project, I don't know what you (or other) contributors *intend* the glob behaviour to be, unless you tell me. So I don't think it would be a good idea for me to open a PR to add this to the docs.

If you *tell* me what the intended behaviour is, then I suppose massage that into something that might be suitable to add to the docs, though.
