### ISSUE TITLE
Wrong post caching output when storing multiple cache

### ISSUE THREAD

**Issue by metaclips** [actions/cache#710]
When saving `multiple cache`, post cache run indicates it caches using the same `cache key` even when different cache keys were used. I have been able to recreate the bug in a [test repo](https://github.com/metaclips/cache_test) which runs a script `file.sh` (only if cache doesn't restore) that creates a file and  is uploaded to cache.
[Running the first action with an unique key ](https://github.com/metaclips/cache_test/runs/4859905844?check_suite_focus=true) `logs` that the cache stores the key twice which shouldn't be as the first key is indicated as `value808119-./folder1/file_mod` and the second `value808119-./folder2/file_mod`.
[Running the second action which uses the unique keys specified above](https://github.com/metaclips/cache_test/runs/4859914766?check_suite_focus=true) indicates that the two keys were correctly uploaded.

**Comment by Jason3S** [comment]
@metaclips,

I'm guessing that the cache action uses the `id` to restore its state during the `Post Run`, since the code uses the same `id` I think it just uses the last one.

```
    - id: cache_hit
```
[Link to code](https://github.com/metaclips/cache_test/blob/1be2c63f34fe1c3fb4d37417bf8f282e2536dead/.github/actions/action.yml#L16)

**Comment by vsvipul** [comment]
@metaclips Will it be possible for you to rerun this scenario? I'll take a look. The logs you mentioned have expired.

**Comment by vsvipul** [comment]
I did get to check this by cloning the repo above. Looks like we store the key in the environment during the restore step which is reused in the save step. Thus, causing this bug. Marking as bug for now. Will see what we can do to fix this. Contribution are welcome as this will mostly require changes in actions/toolkit and actions/cache. 

We save the key [here](https://github.com/actions/cache/blob/d55d005ab0cbd9310b447311bcd1661be90843f5/src/restore.ts#L25) and use it [here](https://github.com/actions/cache/blob/d55d005ab0cbd9310b447311bcd1661be90843f5/src/save.ts#L30).

**Comment by aparna-ravindra** [comment]
Possibly related to - https://github.com/actions/runner/issues/1899

**Comment by vsvipul** [comment]
Looks like this is fixed by https://github.com/actions/runner/pull/1794 . Closing for now. Feel free to reopen.
