### ISSUE TITLE
CRC error during cache restore

### ISSUE THREAD

**Issue by cone56** [actions/cache#713]
Hi, I am seeing `gzip: stdin: invalid compressed data--crc error` from gzip during a cache restore. This seems to indicate that the data is corrupted. Any idea why?

Here's the full log: 

```
Run actions/cache@v2.1.7
  with:
    path: .yarn/cache
    key: Linux-yarn-202201-21-1405803878f8b90eb29be7a5f59df53c2773753609750a395970ca5aeec3e333
    restore-keys: Linux-yarn-202201-21-1405803878f8b90eb29be7a5f59df53c2773753609750a395970ca5aeec3e333
  Linux-yarn-202201-21-
  Linux-yarn-202201-
  Linux-yarn-
  
/usr/bin/docker exec  baec659a8d1af92b1cbd5c287df9a76a515220e6ba493bb5535453dcb7643fb9 sh -c "cat /etc/*release | grep ^ID"
Received 0 of 297944681 (0.0%), 0.0 MBs/sec
Received 83886080 of 297944681 (28.2%), 40.0 MBs/sec
Received 218103808 of 297944681 (73.2%), 69.3 MBs/sec
Received 297944681 of 297944681 (100.0%), 70.1 MBs/sec
Cache Size: ~284 MB (297944681 B)
/usr/bin/tar -z -xf /__w/_temp/e0b55219-28d4-4b45-a865-bca699c092e2/cache.tgz -P -C /__w/launchbox/launchbox

gzip: stdin: invalid compressed data--crc error
/usr/bin/tar: Child returned status 1
/usr/bin/tar: Error is not recoverable: exiting now
Warning: Tar failed with error: The process '/usr/bin/tar' failed with exit code 2
```

**Comment by bishal-pdMSFT** [comment]
@cone56 can you please help with few details:
1. Which runner is being used by the workflow?
2. Please share logs with job debug logs [enabled](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging).
3. Also, if you can find the earlier run which uploaded the cache, please share that as well.

**Comment by bishal-pdMSFT** [comment]
btw is this happening all the time or intermittently only? If it is happening all the times, a workaround would be to make a dummy change in your manifest file (e.g. package.json) and that will create a new cache entry.

**Comment by cone56** [comment]
Hi @bishal-pdMSFT, thanks for your reply. Here's some answers to your questions:

> Which runner is being used by the workflow?

I'm using the `ubuntu-latest` runner:

```
Current runner version: '2.286.1'
Operating System
  Ubuntu
  20.04.3
  LTS
Virtual Environment
  Environment: ubuntu-20.04
  Version: 20220111.1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20220111.1/images/linux/Ubuntu2004-Readme.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20220111.1
```

> Please share logs with job debug logs enabled.

I didn't know about this env var. If I run into this problem again or need to submit a new issue, I'll include this next time. 

> Also, if you can find the earlier run which uploaded the cache, please share that as well.

I believe this is the earlier run that uploaded the cache 6 days ago:

```
Post job cleanup.
/usr/bin/docker exec  2a6f86f767a9d2e2f39175d689dc883704faa8dd5cc32af37f6d829a164a64c7 sh -c "cat /etc/*release | grep ^ID"
/usr/bin/tar --posix -z -cf cache.tgz -P -C /__w/launchbox/launchbox --files-from manifest.txt
Cache Size: ~284 MB (297944681 B)
Cache saved successfully
Cache saved with key: Linux-yarn-202201-18-1405803878f8b90eb29be7a5f59df53c2773753609750a395970ca5aeec3e333

```

> btw is this happening all the time or intermittently only? If it is happening all the times, a workaround would be to make a dummy change in your manifest file (e.g. package.json) and that will create a new cache entry.

I tried 3 different times and the same CRC error happened each time, so I don't think it's intermittent. I was in a hurry to finish a deployment so in the end I commented out the whole workflow step as a workaround. I suspect I won't run into this again since I've already had to make a legit change to yarn.lock, however, if I do experience the same problem I will post an update

**Comment by bishal-pdMSFT** [comment]
@cone56 I looked in our backend telemetry as well and there is no indication of any sort of failure during cache save. My hunch is that it was probably a network glitch which may have resulted in a corrupted cache package. Hence best to go ahead with an updated yarn.lock and see if that fixes the issue.

Since there is not action item for now, I will close this issue. Please reactivate if you see similar issue with updated yarn.lock as well.
