### ISSUE TITLE
caching with two GitHub actions workflow

### ISSUE THREAD

**Issue by nilampatel-engineer** [actions/cache#715]
- I have done docker layer caching in one workflow, have cached folder and want to use that cached images to integration test GitHub workflow. is that possible to use if so how can I use docker image layers cached folder to integration-test githubactions workflow?
-

**Comment by bishal-pdMSFT** [comment]
Yes, it should be possible to re-use cache across workflows. Scope of a cache use is dependent on branch and on cache key. Please see more details [here](https://github.com/actions/cache#cache-scopes).

**Comment by nilampatel-engineer** [comment]
I have done caching on staging workfloe now i want to use that on integration test workflow how i can use that could u pls give me ecample

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by nilampatel-engineer** [comment]
> Yes, it should be possible to re-use cache across workflows. Scope of a cache use is dependent on branch and on cache key. Please see more details [here](https://github.com/actions/cache#cache-scopes).

Hi
the link suggest that we can use caching in same workflow, I am trying to do one time caching in one workflow and use those cached images to another workflow, is that possible? if. u hv any ex pls share.

**Comment by riccardoporreca** [comment]
@nilampatel-engineer see [Restrictions for accessing a cache](https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache)

> Multiple workflows within a repository share cache entries. A cache created for a branch within a workflow can be accessed and restored from another workflow for the same repository and branch.

The restrictions mentioned in the documentation should be kept in mind, as well as the doc about [Matching a cache key](https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows#matching-a-cache-key) linked by @bishal-pdMSFT
