### ISSUE TITLE
Cache download gets stuck mid-way

### ISSUE THREAD

**Issue by rbultje** [actions/cache#731]
Hi,

thanks for creating this feature, we've used it for a few years (2020?) and have been happy with it and until this week have never had any issues with it.

Over the last few days (basically yesterday 2/7/2022 and today 2/8/2022), we've seen intermittent and difficult-to-reproduce issues where downloading the cache gets stuck mid-way. We've never seen this before, and the fact that it happened twice in such a short time-span makes us wonder if some recent change in your code (or the github actions machine setup) may have caused this to start happening:

```
> Run actions/cache@v2
Received 0 of 54013422 (0.0%), 0.0 MBs/sec
Received 49819118 of 54013422 (92.2%), 23.8 MBs/sec
Received 49819118 of 54013422 (92.2%), 15.8 MBs/sec
Received 49819118 of 54013422 (92.2%), 11.9 MBs/sec
Received 49819118 of 54013422 (92.2%), 9.5 MBs/sec
Received 49819118 of 54013422 (92.2%), 7.9 MBs/sec
Received 49819118 of 54013422 (92.2%), 6.8 MBs/sec
Received 49819118 of 54013422 (92.2%), 5.9 MBs/sec
Received 49819118 of 54013422 (92.2%), 5.3 MBs/sec
Received 49819118 of 54013422 (92.2%), 4.7 MBs/sec
Received 49819118 of 54013422 (92.2%), 4.3 MBs/sec
Received 49819118 of 54013422 (92.2%), 4.0 MBs/sec
Received 49819118 of 54013422 (92.2%), 3.7 MBs/sec
Received 49819118 of 54013422 (92.2%), 3.4 MBs/sec
Received 49819118 of 54013422 (92.2%), 3.2 MBs/sec
Received 49819118 of 54013422 (92.2%), 3.0 MBs/sec
Received 49819118 of 54013422 (92.2%), 2.8 MBs/sec
Received 49819118 of 54013422 (92.2%), 2.6 MBs/sec
Received 49819118 of 54013422 (92.2%), 2.5 MBs/sec
```

After this, it just continues to log this message without further progress until the action times out (6hours). Again, this happened twice over the past two days, but never before. Any ideas what could cause this or how to fix/workaround this?

Thanks!

**Comment by vsvipul** [comment]
@rbultje  We were facing some issues on actions during that time period. Has this resurfaced in the past week?

**Comment by vsvipul** [comment]
Closing this for now. Feel free to reopen if you face this again.

**Comment by rbultje** [comment]
It happened a couple of times around that day, but not since then, so closing seems appropriate. Thanks for looking into it!

**Comment by wartingep** [comment]
@vsvipul this still happens multiple times each day for us :(
