### ISSUE TITLE
[Documentation] Multi-line key ?

### ISSUE THREAD

**Issue by Conchylicultor** [actions/cache#741]
When the key is very long, I would like to be able to split it in multiple lines:

```python
key: ${{  A }}- ${{  B }}-${{  C }}-${{ D }}
```
Instead I would like something like:
```python
key: |
  ${{ A }}
  ${{ B }}
  ${{ C }}
  ${{ D }}
```
Which is much more readable when the key expressions are complicated.

However it's not currently clear whether this is supported or not ? Are spaces in the key allowed ? What about newlines ?

What about ?

```python
key: >-
  ${{ A }}
  ${{ B }}
  ${{ C }}
  ${{ D }}
```

Looking at the examples, I can't find a key using newlines: https://github.com/actions/cache/blob/main/examples.md

* If this isn't supported currently, it would be a nice feature request.
* If this is supported, it would be nice if the doc was showing an example of multi-line.

**Comment by vsvipul** [comment]
@Conchylicultor Yes multiline is supported but it does add 1 extra space after every line which seems to be ok. 

I tried with this workflow - 
```
    - uses: actions/cache@757c5a8ca4ffdc40ccfb58f32d54537a4d090dfb
      id: cache
      with:
        path: cache-folder
        key: >-
          ${{ runner.os }}
          -${{ github.sha }}
          -key
```

But the key created here is "Linux -70e0ba076fc22fb98faf61422d401d6ff1313a53 -key" , which does seem to work fine. 
I would not recommend adding this to the docs as none of the keys have spaces in them. 

More context on the yaml multiline strings can be found at https://yaml-multiline.info/ . There seems to be no way for now to write multiline without adding an extra space. If you any more questions, feel free to reopen.
