### ISSUE TITLE
[meta] Review pull requests

### ISSUE THREAD

**Issue by aminya** [actions/cache#745]
Currently, there are 47 open pull requests that are left unreviewed. The oldest ones have opened ~3 years ago. Is there any plan to address the community contributions? 

https://github.com/actions/cache/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+review%3Anone

I checked the projects and discussion for @actions, but I cannot see any plans or an ongoing discussion 
https://github.com/orgs/actions/projects
https://github.com/actions/cache/discussions

**Comment by vsvipul** [comment]
@aminya Thanks for opening this up. The team handling this action was changed a couple of months back. We are still getting upto pace with the PRs and issues. About the PRs I can not give a timeline on when that will be done but rest assured, we are looking into triaging those in the coming months.
