### ISSUE TITLE
How to specifcy multiple patterns for `hashFiles`

### ISSUE THREAD

**Issue by devtonhere** [actions/cache#748]
For my sbt project I need to hash these files:

- `**/build.sbt` 
- `project/**`

The project is also important because it contains:

- sbt version `build.properties`
- sbt plugins in `plugins.sbt`
- another plugin in `assembly.sbt`

**Comment by dhadka** [comment]
@devtonhere `hashFiles` can be given a list of patterns:

```
${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
```

Full example: https://github.com/actions/cache/blob/main/examples.md#java---gradle

**Comment by vsvipul** [comment]
@devtonhere As your question has been answered by Dave, going ahead to close this. Feel free to reopen or open another issue if you have any more questions.
