### ISSUE TITLE
workflow_dispatch needs to be supported

### ISSUE THREAD

**Issue by amitojsingh366** [actions/cache#756]
Currently when the action is run on `workflow_dispatch` the following error shows up:
`Warning: Event Validation Error: The event type workflow_dispatch is not supported. Only push, pull_request events are supported at this time.`

I believe this action should work with the `workflow_dispatch` event aswell.
The workflow dispatch event can be triggered from within the actions tab of a repo, given below is an example:
![image](https://user-images.githubusercontent.com/35400192/156920779-bef85d0a-442d-431e-92e5-fba9e982d499.png)

This event is useful for me as it allows me to release my app only after multiple checks to ensure it is working properly and this is also the reason I do not use other triggers like `push`

**Comment by vsvipul** [comment]
@amitojsingh366  You must using v1 of the action. Since then we have released v2 version of the cache and 
"Allowed caching for all events with a ref" was added in v2.0.0 .
Please use actions/cache@v2 to test and let me know if its works.

**Comment by amitojsingh366** [comment]
Thanks a lot, v2 indeed fixes my issue
