### ISSUE TITLE
Question: Is it possible to use actions/cache with "release:created" event?

### ISSUE THREAD

**Issue by vitalyk-multinarity** [actions/cache#766]
I have a flow with Unity 3D build and using cache action for caching the "Library" folder. I noticed that it works when CI is triggered by the push to a certain branch but doesn't work when the workflow is triggered by the "release" event. 
Is this by design (if so, why?) or I'm missing something? 

TIA, Vitaly

**Comment by tjasmi30** [comment]
#551

**Comment by Phantsure** [comment]
I don't see why it shouldn't be possible. It is completely possible to trigger a workflow with actions/cache with "release:created" event or any supported event.
<img width="907" alt="Screenshot 2022-05-11 at 3 29 48 PM" src="https://user-images.githubusercontent.com/25999504/167824169-acf53bd8-dc0b-4b8e-9f82-c59cb9e4dbd9.png">

**Comment by vitalykarasik** [comment]
> I don't see why it shouldn't be possible. It is completely possible to trigger a workflow with actions/cache with "release:created" event or any supported event. <img alt="Screenshot 2022-05-11 at 3 29 48 PM" width="907" src="https://user-images.githubusercontent.com/25999504/167824169-acf53bd8-dc0b-4b8e-9f82-c59cb9e4dbd9.png">

[Phantsure](https://github.com/Phantsure) - thank you, I'll re-test.

**Comment by Phantsure** [comment]
Hey @vitalykarasik @vitalyk-multinarity, did you re-test this? Would love to have a closure on this. Thanks

**Comment by vitalyk-multinarity** [comment]
@Phantsure Phantsure - thank you, and sorry for delay.
I tested right now - created a release and the cache was restored.
So I'm not sure in which scenario I encountered the original issue.
Thank you again, I'm closing this as resolved.
