### ISSUE TITLE
The condition for a cache-hit may not be sufficient

### ISSUE THREAD

**Issue by syslogic** [actions/cache#767]
Currently this counts as a "cache hit", when an empty archive is being extracted:

    Cache Size: ~0 MB (30 B)

This shouldn't count as a cache hit, because there is no actual result - which leads to issues with subsequent steps `if`.
Even an estimated expected size parameter might make sense, because one often knows how large the cache should be.
Returning `true` / `false` without considering the size at all ...only requires further checking, if the cache is even there.

With optional conditions, which define what a cache hit is, this would be more reliable:

    expectedSize: 2014644496B
    expectedMinSize: 31B

Because then, subsequent steps would not receive a possibly wrongful return value.

 ---

It would also suffice, when returning the size of the cache in bytes, in case of a "hit", because one can compare the value then.

**Comment by vsvipul** [comment]
@syslogic 0 size cache is not currently created. It might be the case that you might be caching the wrong things which is leading to this. Can you please give an example where expected size is high but sometimes cache of some bytes might be created even if the cache path and key is fully correct?

**Comment by vsvipul** [comment]
Closing for now. Feel free to reopen if you have more details and if this issue is still happening.
