### ISSUE TITLE
Specify Cache TTL

### ISSUE THREAD

**Issue by mattfoley8** [actions/cache#780]
What is the cache TTL for actions/cache@v3? I had assumed that the cache TTL was infinite (or 30 days or some long period), but I'm seeing cache misses for the same cache key and restore keys a few hours apart. Is the default cache key TTL 60mins? If so, it would be great to specify how long the cache TTL is as another GitHub Actions YAML file config parameter. I.e. in addition to `path`, `key`, and `restore-keys`, it would be great if we could specify `ttl` in seconds. In practice, I don't know if I would ever want my cache to expire for the same cache key, but as a fallback, I would also appreciate the flexibility to specify a key's TTL. Then I may set it to 24h, 7d, or 30d (and am fine specifying those in seconds and doing the conversion on my end).

**Comment by LinkedInprofile** [comment]
I'm 'ocked out of my laptop any ideas to why? OR HOW I CAN FIX THIS?

**Comment by vsvipul** [comment]
I'm not sure why your are seeing cache misses a few hours apart. Can you try to reproduce this on a public repo and share that workflow here please if it occurs again? 

On https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows , it is clearly mentioned that -
```
GitHub will remove any cache entries that have not been accessed in over 7 days. There is no limit on the number of caches you can store, but the total size of all caches in a repository is limited to 10 GB. If you exceed this limit, GitHub will save your cache but will begin evicting caches until the total size is less than 10 GB.
```

**Comment by vsvipul** [comment]
Closing for now. Feel free reopen if you have any more questions.

**Comment by mvynhb** [comment]
Hi, I am also experiencing the same issue. The cache is not 7 days as described on the docs. I found the cache expiring in less than 1 day using a private repo.

**Comment by philmod-h** [comment]
> Hi, I am also experiencing the same issue. The cache is not 7 days as described on the docs. I found the cache expiring in less than 1 day using a private repo.

Maybe you reached the cache quota, in which case GitHub automatically delete the oldest caches.

**Comment by oleksandr-danylchenko** [comment]
Unfortunately, there's a related issue when you rely on the 10Gb cap policy. The `actions/cache/restore` may unexpectedly miss the newly added entry if it causes old entry's eviction: https://github.com/actions/cache/issues/1735#issuecomment-4769767669
