### ISSUE TITLE
Why this doesn't work for me

### ISSUE THREAD

**Issue by theajack** [actions/cache#782]
I always get this ERROR: 

Cache not found for input keys: Linux-node-ffd095da82fcd41af89f8278e66b668c7aa360b9494d7f000bf6fca7bb19148a, Linux-node-

[config file](https://github.com/theajack/github-action/blob/master/.github/workflows/release.yml)

[Run log](https://github.com/theajack/github-action/runs/5836651370?check_suite_focus=true)

Thanks for your help!

**Comment by ariefwijaya** [comment]
Why you close this? this happened to me too
