### ISSUE TITLE
SHA-1 checksums in package-lock.json - is this a security issue?

### ISSUE THREAD

**Issue by capncodewash** [actions/cache#793]
Hi there,
I'm submitting this here as I'm not sure if it's a security issue or not - I'm not a Node developer so am unsure of the impact.

I noticed that the package.lock file for `cache` contains a lot of SHA-1 hashes, which leads me to wonder if the package is susceptible to hash collision attacks.

Example:
```
"color-name": {
          "version": "1.1.3",
          "resolved": "https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz",
          "integrity": "sha1-p9BVi9icQveV3UIyj3QIMcpTvCU=",
          "dev": true
        },
```

Updating the package-lock.json with npm 8.5.5 resolves quite a few of these, but not all, to SHA-512. It also seems to upgrade the `lockfileVersion` to 2.

Could you please explain if this is a security issue, and if so, what the impact is?

My concern is that using builds of the 'cache' action, could lead to maliciously-crafted dependencies being used in the context of my repositories.

Thanks!

**Comment by vsvipul** [comment]
Hi @capncodewash 
We keep all our dependencies up to date and most of the dependencies used are dev-dependencies, i.e. they are only used during the development on the action and not while the action is running. 

About the sha1 vs sha512 integrity, the npm docs themselves don't mention much https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json

We also recently updated our package-lock.json by updating npm version. As long as you are using our official action, you should be safe from attacks.

This might not be true if you are using unofficial forks of our action and would need to do some checks in that case.

Closing this now. Feel free to reopen if you have any more questions.
