### ISSUE TITLE
Feature request: Add a flag for skipping post run cleanup

### ISSUE THREAD

**Issue by jlivak** [actions/cache#795]
In situations where you want to minimize the time it takes for a workflow run to complete, the cleanup step can take a significant amount of time with large caches.  A flag to disable the cleanup behavior would be especially helpful in situations where you know the runner image is going to be torn-down after each action run anyways.

**Comment by aparna-ravindra** [comment]
Hey @jlivak ,
You are right that the post run step takes some time for large caches. However, this will be a one time process. Skipping this step and not saving the cache will makes the subsequent runs slower. Effectively, there is no advantage of the cache. 

Please do get back if my understanding is incomplete.

**Comment by jlivak** [comment]
@aparna-ravindra To clarify, I'm not suggesting a way to skip the post-run step that saves a new cache when there's a miss.

Rather when there's a cache hit, there is still a "Post job cleanup" step that can take ~1 minute to complete.  My understanding is that on a cache hit this step is cleaning up and removing the cache files from the agent machine after running the job, and there are times where I'd rather skip this step and just let the files be removed when the build agent image is torn down.

Let me know if I'm not understanding correctly what that post run step is doing on a cache hit.

**Comment by bradzacher** [comment]
Definitely agree! As an example - here is a CI which uses the cache to cache yarn artefacts.
https://github.com/typescript-eslint/typescript-eslint/actions/runs/2303684433

You can see each and every job has a post-run step for the cache which takes 1-2m.
This can double the time it takes for some of the jobs to complete!

It'd be great if we could designate a specific job as the "save job" and others as a "restore-only job"

**Comment by aparna-ravindra** [comment]
Got it 👍🏽 Thanks for clarifying. I think there was another such report [here](https://github.com/actions/cache/issues/597). I will check on this and get back.

**Comment by aparna-ravindra** [comment]
In the example that @bradzacher shared, the post run cleanup takes time when there is the following message "Unable to reserve cache" . [Example](https://github.com/typescript-eslint/typescript-eslint/runs/6379223539?check_suite_focus=true) 

However, if there was a cache hit on the primary key and no attempt is made to reserve cache, the step compeletes fast.
[Example from same workflow](https://github.com/typescript-eslint/typescript-eslint/runs/6379223630?check_suite_focus=true)

Do you also have similar observations, @jlivak ?

**Comment by jlivak** [comment]
@aparna-ravindra That's not quite what I've seen.  Unfortunately I'm only using this in private repos and can't link to an example run, however I can say that in our jobs, the "Run actions/cache@v3" step completes with "Cache restored from key: ...".  And then the post-run step "Post Run actions/cache@v3" will run for ~30-45 seconds before printing the following:
`Post job cleanup.
Cache hit occurred on the primary key ...`

This was with a cache of ~600MBs.  I'm assuming that 30-45 seconds in this case is just how long it's taking to perform the "Post job cleanup."

**Comment by aparna-ravindra** [comment]
@jlivak , I am trying to reproduce this as well. I am suspecting that the runner is delayed while starting the step somehow. I will also consult with experts and get back once I have more information to share.

**Comment by jlivak** [comment]
@aparna-ravindra I'll see about recreating this behavior in a public test repository and get back to you on that.

**Comment by eduardomoroni** [comment]
https://github.com/actions/cache/pull/571
This would solve this issue

**Comment by aparna-ravindra** [comment]
@eduardomoroni ,
Thanks for the update. I see two concerns here:
1. Skipping the cache save in the "past" step for non-critical branches - since you know that it will never be used again.
2. Skipping the "post" step because of performance impact. 

This issue is related to the second concern as explained [here](https://github.com/actions/cache/issues/795#issuecomment-1122820872).
If there is a performance impact, it would be across all branches. One [observation](https://github.com/actions/cache/issues/795#issuecomment-1123567052) I found was that the post run cleanup takes time when there is the following message "Unable to reserve cache". Here most of the is spent on compressing large caches only to find later that the key is reserved by another job running in parallel. 

I am curious to learn if there is a case where cache is occurs on primary key and yet the step takes a lot of time? If you have an example of a recent run, it will help me reaching the root cause of the problem.

**Comment by eduardomoroni** [comment]
In our current set-up (in a mono repo) we do see this message quite often
<details>
<summary>Unable to reserve cache with key foo another job may be creating this cache.</summary>
<code>
Post job cleanup.
/usr/bin/tar --posix --use-compress-program zstd -T0 -cf cache.tzst -P -C /runner/_work/web/web --files-from manifest.txt
Unable to reserve cache with key yarn-[2](https://github.com/hellofresh/web/runs/6716720841?check_suite_focus=true#step:17:2)cd2e6b8a1dfe6a208d89da26806e14774229750792ffc2ecd64cbf2[3](https://github.com/hellofresh/web/runs/6716720841?check_suite_focus=true#step:17:3)0bd1e35, another job may be creating this cache. More details: Cache already exists. Scope: refs/heads/master, Key: yarn-2cd2e6b8a1dfe6a208d89da26806e14774229750792ffc2ecd64cbf230bd1e35, Version: 99db5c78d55d9c5167ce52fe7302d71068ad1db13c4e6d369c92abb72cf3a50e
</code>
</details>

It doesn't impact the duration though, what happens sometimes is that the run that actually uploads the cache takes a considerably higher amount of time to push. We do our own metrics around this, I wonder how we could share with you the runs that causes this interesting behaviour.
<details>
<summary>One Example</summary>
THey all share the same key `yarn-37e01cb697fec020a49627d1b2d08ad88dcec520213a803513644b22f7438b24`
<img width="1420" alt="image" src="https://user-images.githubusercontent.com/823150/171850329-4c1e6c7e-3373-4b09-b840-5bd0ef832e2b.png">

This is the first job
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/823150/171850561-3eb3a04a-7e0a-47db-bf85-7c9642cea01e.png">

Then these two run in parallel
<img width="1044" alt="image" src="https://user-images.githubusercontent.com/823150/171850675-4b4a6f6b-1161-4688-a860-0c97d5bcda15.png">
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/823150/171850765-b2411ab7-7a1b-4edf-bfb1-1d0b1b5e45ee.png">

Our metrics for this post step
<img width="1188" alt="image" src="https://user-images.githubusercontent.com/823150/171851058-93dee3bf-16d4-4752-b9e6-c8e2d36fcd1c.png">

The heatmap is quite interesting to me
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/823150/171851165-1159dd7f-63ac-4010-8f0d-40fbeb4c0693.png">
We don't change that often yarn.lock, let's say that in a busy week we change 20-25 times, but normally we change less than 10 times a week.  And we run yarn instal around 2k times a day
</details>

I'm happy to contribute on this.

On the other concern do you think that allowing https://github.com/actions/cache/pull/571 would it be problematic? This sound like perfect to us, and by not saving cache that often we would have even less occurrences of the problem I posted above. What do you think?

**Comment by jlivak** [comment]
I believe what's posted above is a bit different from the issue I was encountering.  I wasn't looking for a way to skip cache saving, rather just a way to skip the post-run cleanup that was taking an unusually long time when there was a cache hit and nothing to save/upload.

Apologies to @aparna-ravindra I know I still owe you a test project.  I worked on that today but am having issue replicating the issue in my test repo.  I'll look into our configuration at work next week and see if I can figure out a way to reproduce it.

**Comment by jlivak** [comment]
Here is an example pulled from our work pipelines though showing that on cache hit post-run still takes 25 seconds for some reason.
![cachepostrun](https://user-images.githubusercontent.com/71203927/172033423-4a9e9c60-01a7-41bb-abf1-87ea3cfcf635.PNG)

**Comment by aparna-ravindra** [comment]
@eduardomoroni 
Agree that the PR you linked is a possible solution to the first concern that I had listed [above](https://github.com/actions/cache/issues/795#issuecomment-1145772261). I see that it has lost traction since it was created, but it is something we can continue reviewing now. 

As @jlivak restated, we are trying to figure out what is consuming time in the post action when there is no cache save happening. @jlivak , we will not be able to skip the post action altogether. We will need to figure out what step is taking time. Unfortunately, I have not been able to reproduce this in any of my workflows. Hence, it would be a ton of help if you could share one with us where you could reproduce this.

**Comment by aparna-ravindra** [comment]
> Here is an example pulled from our work pipelines though showing that on cache hit post-run still takes 25 seconds for some reason.

@jlivak Is your workflow running on self-hosted runners or Github hosted runners? Would it be possible to share the logs from this workflow run? You should be able to download them. Also, workflow with debug logs enabled will provide more insights. [Here](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging) is how you can enable debug mode.
![image](https://user-images.githubusercontent.com/82894348/172188401-bf657a0f-7354-44f0-bc00-7ebe621de25e.png)

**Comment by jlivak** [comment]
@aparna-ravindra Thanks for pointing me to the debug logging flags, enabling those actually let me figure out what was going on.

It looks like the issue was caused by having `**/` at the beginning of our hashFiles() pattern for creating the cache key.  We unintentionally also had files within our cache that matched the file pattern and so some combination of searching the entire cache directory for matches and hashing together multiple matched files seemed to be what caused the 20-40s delay with the post run action.  Changing the pattern in hashFiles to an absolute path has fixed the issue.

I appreciate the help in tracking down the cause of this issue.

**Comment by eduardomoroni** [comment]
I know that the owner of the issue closed it, but as the title implies `[Feature request: Add a flag for skipping post run cleanup](https://github.com/actions/cache/issues/795#)` I still think this was not yet addressed, but there's a PR opened to implement this feature: https://github.com/actions/cache/pull/571
If the repo maintainers agree with the solution or wants some changed, I'd be happy to address those. As this is a big problem for us.

**Comment by kotewar** [comment]
Hey all, 👋🏽 

We have created a [discussion](https://github.com/actions/cache/discussions/1020) with a proposal that will solve this problem, do let us know your feedback, thanks 😊

**Comment by kotewar** [comment]
Hey everyone 👋🏽

Two new actions [actions/cache/restore](https://github.com/actions/cache/tree/main/restore) and [actions/cache/save](https://github.com/actions/cache/tree/main/save) are now available with tag `v3` to everyone for use. These can now be used to achieve granular control on the restore and save steps in the cache action. 

Do try them and give your feedback. We hope these new actions will take care of your use cases. 🙇🏽
