### ISSUE TITLE
README Implementation Examples are broken

### ISSUE THREAD

**Issue by sayjeyhi** [actions/cache#822]
README `Implementation Examples` url are broken on [actions page](https://github.com/marketplace/actions/cache), for example open this one:

On actions page it is like this:
https://github.com/actions/cache/blob/examples.md#node---npm

On Github Readme file it is like this:
https://github.com/actions/cache/blob/main/examples.md#node---npm

a `main/` is missing on upper URL

**Comment by pallavx** [comment]
Hi @sayjeyhi - I see that the NPM example link is working as expected. Are you still facing the issue? If so please provide more details, maybe with a small video.
