### ISSUE TITLE
Allow optionally testing for `cache-hit` without restoring old cache

### ISSUE THREAD

**Issue by ankith26** [actions/cache#831]
First of all, thanks to the maintainers and contributors who keep this project up, which helps make CI cache handling simple! 🥳

## Use case

I have a build matrix with 5 jobs, that need to access (but not write) a common cache.
To update this cache, I have a job that this matrix depends on (that runs before it). This job restores cache and populates cache on a cache miss, so that subsequent jobs can use it.

This works, but there is an unneeded step of restoring cache in my first job, when all I want to do is to just test for a cache miss, rebuild in that case and upload new cache.

## Proposal

There should be an input `dry-run`/`test-cache`/`no-pull`/`[anything-else-here]` (yes naming things is hard😅) that should control whether the cache is pulled initially (should default to yes). Then `cache-hit` should be set accordingly, and post cache step should run normally

**Comment by Exelord** [comment]
I have exactly the same case. That would be really welcome feature!

**Comment by kotewar** [comment]
Closing this and tracking the same in https://github.com/actions/cache/issues/901
