### ISSUE TITLE
Display used cache size

### ISSUE THREAD

**Issue by jcornaz** [actions/cache#84]
Hello, 

First of all, thank you very much for providing this much needed functionality!

I just have a question: How do I know how much space my cache is using?

Could it be displayed somewhere? Maybe logging it in the build console is enough?

**Comment by joshmgross** [comment]
Hey @jcornaz 

The individual cache size is printed if you turn on debug logging, see https://help.github.com/en/actions/automating-your-workflow-with-github-actions/managing-a-workflow-run#enabling-step-debug-logging

**Comment by jcornaz** [comment]
Ok, thanks for the quick answer.

**Comment by jcornaz** [comment]
Actually, I would like to reopen it as a feature request.

I would like to request that we could have access to that information *without* using the debug mode.

I don't want to *debug* my workflows. I just want to know how much space the cache is using.

Currently, if I need to:
1. Enable debug mode
2. Rerun my workflows
3. Disable the debug mode

It is quite a lot, just to access this useful information.

**Comment by joshmgross** [comment]
Fixed with #85, will be in the next release (1.02) which I'm planning on releasing sometime next week (holding off on any updates during GitHub Universe)
