### ISSUE TITLE
Explicitly document how to have cache always updated.

### ISSUE THREAD

**Issue by krpatter-intc** [actions/cache#840]
Add to Readme the best-known-method for making sure you save your cache information

It would be worth spelling out in the README the details mentioned here:

https://github.com/actions/cache/issues/342#issuecomment-673371329

for how to support the ability to always work with and then update a cache

**Comment by Jamie-** [comment]
To add to this, the docs say:
> 3) If the job completes successfully, the action automatically creates a new cache with the contents of the path directory.

https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#example-using-the-cache-action

It does not specify that the cache is *only* stored on a cache miss.
Confirmed in the code here:
https://github.com/actions/cache/blob/main/src/save.ts#L36-L41

If the code is stay as-is, the main docs need to be updated to clarify this.

**Comment by bishal-pdMSFT** [comment]
Agree, we can probably update both README as well as the docs.
