### ISSUE TITLE
Using Caches in JavaScript

### ISSUE THREAD

**Issue by lorenzolewis** [actions/cache#841]
I'm trying to retrieve a cache in JavaScript using `@actions/cache`. I am currently getting this error:

`getCacheEntry failed: Cache Service Url not found, unable to restore cache.`

Doing some research, I'm seeing this is due to ACTIONS_RUNTIME_URL, ACTIONS_RUNTIME_TOKEN and ACTIONS_CACHE_URL environment variables not being available in node (source: https://github.com/nektos/act/issues/329, note that the error I've put above is from a GitHub runner, not while I've been using act).

To test this, I looked to see if ACTIONS_RUNTIME_URL, ACTIONS_RUNTIME_TOKEN or ACTIONS_CACHE_URL environment variables are available in node via `process.env.{respective token name here}` and they are undefined.

This is where I'm currently trying to use it: https://github.com/tauri-apps/tauri-docs/blob/feat/i18n-evergreen/.scripts/ci-postbuild.js

I'm wanting to do this in JS and not directly in the Action YML because I want to loop through and dynamically pull in caches derived from a passed array.

**Comment by vsvipul** [comment]
@lorenzolewis Yes, the ACTIONS_CACHE_URL which we currently use in[ this line](https://github.com/actions/toolkit/blob/c5278cdd088a8ed6a87dbd5c80d7c1ae03beb6e5/packages/cache/src/internal/cacheHttpClient.ts#L38) in our action will not be available locally. 

They won't be undefined when running the action on a GitHub Runner. 
e.g. I tried this on a repo -
```
  const testVar = process.env['ACTIONS_CACHE_URL'] || '';
  console.log(testVar);
```

and it did print the value in the logs somewhat like this -
```
https://artifactcache.actions.githubusercontent.com/UzFjuK9TWjl0IlrYcCaOkJYTrCi1ERVIWUiCfBADZfnthjkwe3hf/
```

If you are still not able to print this environment var, please create a new public action which just prints this variable and give us the link for the workflow run. This would be helpful for us to debug the issue. 

Please reopen this issue if that is the case.

Please also note that you will need to use[ ACTIONS_RUNTIME_TOKEN ](https://github.com/actions/toolkit/blob/1cc56db0ff126f4d65aeb83798852e02a2c180c3/packages/cache/src/internal/cacheHttpClient.ts#L64)as well to authenticate the requests from a github runner.

**Comment by sakulstra** [comment]
@vsvipul I've been running into the same issue.

Here's the public ci run: https://github.com/bgd-labs/seatbelt-for-ghosts/runs/7270831627?check_suite_focus=true#step:5:10
The action code: https://github.com/bgd-labs/seatbelt-for-ghosts/pull/8/files#diff-1a63c1d4f25b94d81a0f8bc14aec9135e1b569b02467bbd0ccd31dbb75ca3ba0R49
The code being called in the action: https://github.com/bgd-labs/seatbelt-for-ghosts/pull/8/files#diff-fb72f8e5d2ee337208073d738cc9634417eec12311db3a41e0f255506f2b9672R37
