### ISSUE TITLE
Caching regardless of build status

### ISSUE THREAD

**Issue by frantzmiccoli** [actions/cache#849]
I would like to cache the built result regardless of the built status, i.e. also in case of failure. Unfortunately if something fails in the action "Post ..." steps for the cache action is not executed.

I tried to set and if statement: `if: success() || failure()` on the cache action step itself but it doesn't impact the later "Post" step execution.

**Comment by rhcarvalho** [comment]
See https://github.com/actions/cache/issues/92 (and https://github.com/actions/cache/issues/46)

**Comment by kotewar** [comment]
This has been implemented and released in the new [save](https://github.com/actions/cache/tree/main/save) action. Using `if: always()` with the save action can now achieve the desired outcome, hence closing this issue.
