### ISSUE TITLE
New option to create `path`

### ISSUE THREAD

**Issue by szepeviktor** [actions/cache#852]
Currently `mkdir -p $cache_path` should be issued to create directory specified in `path`.
`cache` does not create the `path` directory if it doesn't exist.
https://github.com/szepeviktor/Valinor/runs/7272413993?check_suite_focus=true

Please consider adding a `"create_directory": true` option to create directory specified in `path`.
Thank you!!

**Comment by kotewar** [comment]
Hey @szepeviktor 👋🏽 
The directory creation should happen at build time, and should be created by the build program itself.
Can you please specify why you would want a new directory to be specifically created?

**Comment by kotewar** [comment]
@szepeviktor, would you like to share the use case for this suggestion so that we can prioritise it?

**Comment by szepeviktor** [comment]
@kotewar On the very first run the cache is empty and many tools do not autocreate directories, mainly sub-subdirectories.
And these tools are failing because of the non-existent directory structure.

**Comment by kotewar** [comment]
Thanks for bringing this up @szepeviktor. 

Can you please share these tools as well so that we can use the same for testing the behaviour and make the necessary fixes?

**Comment by szepeviktor** [comment]
Okay. I respond within a day.

**Comment by szepeviktor** [comment]
https://github.com/CuyZ/Valinor/blob/master/infection.json.dist#L8
Using a **non-existent** temporary directory for `infection/infection` causes an error.

**Comment by kotewar** [comment]
How about using `shell:bash` to do this job for you?

Currently we haven't received much requests in this area, but this can be achieved using custom [shell commands](https://docs.github.com/en/actions/learn-github-actions/essential-features-of-github-actions#adding-scripts-to-your-workflow) to achieve this folder creation.

**Comment by szepeviktor** [comment]
Thank you.
I'm into solutions, not work-arounds.

**Comment by fquinner** [comment]
Vcpkg does this too with its binary cache. Will only use an existing directory.

    VCPKG_DEFAULT_BINARY_CACHE
