### ISSUE TITLE
Update documentation in Github Docs

### ISSUE THREAD

**Issue by guppy0356** [actions/cache#877]
> A workflow can access and restore a cache created in the current branch, the base branch (including base branches of forked repositories), or the default branch (usually main). For example, a cache created on the default branch would be accessible from any pull request. Also, if the branch feature-b has the base branch feature-a, a workflow triggered on feature-b would have access to caches created in the default branch (main), feature-a, and feature-b.

It sounds like the branch `feature-b` can access to caches created in branch `feature-a`. I could observe that it could NOT access to caches created in branch `feature-a`.

This documentation is wrong.

**Comment by guppy0356** [comment]
Hello @vsvipul . https://github.com/actions/setup-node/issues/539 helps you.

**Comment by guppy0356** [comment]
Upps. https://github.com/actions/cache/issues/823 also helps you.

**Comment by vsvipul** [comment]
Yes, we are going to update this. This only works for default branch. Thank you for reporting.

**Comment by guppy0356** [comment]
@vsvipul 
I think you need to mention https://github.com/actions/cache/issues/823. Is this same problem?

**Comment by vsvipul** [comment]
Closing this. Tracking docs change for the same at https://github.com/actions/cache/issues/823 .
