### ISSUE TITLE
setting to keep cache even if job fails

### ISSUE THREAD

**Issue by kylrth** [actions/cache#881]
I use this action for the cache of [htmltest](https://github.com/wjdp/htmltest/), a link checker. Often it'll get through plenty of links before finding a broken one, but because the job fails the cache isn't saved (and so if I re-run the action it has to check all the links again). I'd like for there to be a setting to keep the cache even if the job fails.

**Comment by Phantsure** [comment]
@kylrth cache save happens at the end of workflow run. This happens because the directory/file cached can change till the end of run. Saving cache after every step would create a lot of requests which many users won't want.

**Comment by kylrth** [comment]
That's not what I'm asking for. The checkout action has a post run step that runs regardless of the success of the run, as you can see in [this example](https://github.com/kylrth/kylrth.github.io/runs/7692731142?check_suite_focus=true). What I'd like is for there to be a setting where the same behavior can happen for the cache action.

**Comment by Phantsure** [comment]
@kylrth actions/checkout runs for cleanup. If cache was allowed to save cache even on job fail then it could create corrupted cache, in most cases. If there is more request for this feature we would work on this.

**Comment by jorgemo-fever** [comment]
I'm pretty sure that there already is more than a request for this feature (https://github.com/actions/cache/issues/92).

**Comment by Phantsure** [comment]
Thanks @jorgemo-fever for pointing that. We have internal discussions related to these issues.

**Comment by kylrth** [comment]
I guess I'll close this issue then since it's a duplicate of #92. It's a shame this hasn't been added because there is definitely interest.

**Comment by kotewar** [comment]
Hey everyone 👋🏽

Two new actions [actions/cache/restore](https://github.com/actions/cache/tree/main/restore) and [actions/cache/save](https://github.com/actions/cache/tree/main/save) are now available with tag `v3` to everyone for use. These can now be used to achieve granular control on the restore and save steps in the cache action. 

Do try them and give your feedback. We believe these new actions will take care of your use cases. 🙇🏽 

The `save` action can be made to run always by passing `always()` in the `if` condition.
