### ISSUE TITLE
Create the examples directory

### ISSUE THREAD

**Issue by imbsky** [actions/cache#9]
Currently, PR's have been submitted to add language specific examples (#4, #5, #8, #10), and probably more PRs will be submitted if you approve those. So, if you plan to approve it, you should create an examples directory to keep clean README. What do you think?

**Comment by chrispat** [comment]
We will have more comprehensive documentation going up next week and will have some samples.  I don't want to bloat this repo with a bunch of different samples.

**Comment by imbsky** [comment]
Yes, I agree completely. If we have basic API usage documentation, we don't need an example for each language.

**Comment by ad-m** [comment]
@chrispat, It may be helpful to document an example:
- using Docker, due to its specific, own cache management,
- using cache and "jobs. <job_id> .needs" to separate build from testing performed in parallel (using "jobs.<job_id>.strategy").

**Comment by chrispat** [comment]
@ad-m due to the way docker does its caching I don't think you would want to use this feature to cache docker layers.

**Comment by ad-m** [comment]
In this case, the Docker cache issue in GitHub Actions remains open. Should this be an issue in this repository or in repository ```@actions/toolkit```?

**Comment by joshmgross** [comment]
@ad-m I think it's fine to leave that in `@actions/toolkit`, as it's a general improvement to Docker actions. If the recommended step is to just cache before using every docker action, then that might be better if done by default.
