### ISSUE TITLE
SSL issue while using cache feature released in v3.5

### ISSUE THREAD

**Issue by Rajalakshmihm** [actions/cache#915]
Hi Team,
we recently upgraded our GitHub enterprise self hosted server (on-prem) to v3.5.3
while exploring the cache support [feature](https://docs.github.com/enterprise-server@3.5/admin/release-notes#cache-support-for-github-actions-on-github-enterprise-server-is-now-generally-available) , we observed connection issue between our runner and s3 storage

![image](https://user-images.githubusercontent.com/84449289/188129040-de4b44ee-d039-48e1-a9a0-69c6de56a080.png)

After fixing the connection issue, we noticed SSL issue as below
![image](https://user-images.githubusercontent.com/84449289/188129309-79cf3942-7cc8-42ed-bbcb-597fb25c5087.png)

we fixed it temporarily by disabling the SSL
![image](https://user-images.githubusercontent.com/84449289/188129614-59229ee8-8af3-406a-b906-6cab9d8e9bf3.png)
 
could you please let us know what could be the reason for this

**Comment by Rajalakshmihm** [comment]
Hi @pallavx - Any updates on the above please?

**Comment by Rajalakshmihm** [comment]
Hi @pallavx - Could you please update in which Github enterprise version this bug is fixed?

**Comment by pallavx** [comment]
Hi @Rajalakshmihm, I will check and get back.

**Comment by MrTibbles** [comment]
@pallavx are there any updates on this issue?
