### ISSUE TITLE
Keep files in cache but don't use it

### ISSUE THREAD

**Issue by Elikill58** [actions/cache#919]
I tried to use this actions as explained [here](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#example-using-the-cache-action) for the exact same use-case (npm).

The time of package keep the same (around 4m 15s). And I just received an email of github that I'm using more than 75% of storage for github actions/package ...

How can I clean all cache, and make it useful ?

**Comment by aparna-ravindra** [comment]
> How can I clean all cache, and make it useful ?

You should be able to list the caches stored for your repository and delete them using either the API described [here](https://docs.github.com/en/rest/actions/cache#list-github-actions-caches-for-a-repository) or using the gh-cli extension [here](https://github.com/actions/gh-actions-cache).

This will also tell you the storage consumed by this action. 

FYI, github.com gives 10GB storage for caches per repository. Once you consume this, older caches get evicted to make space.

**Comment by Elikill58** [comment]
The mail that I received is talking about something else:

![image](https://user-images.githubusercontent.com/17381066/189058819-eca7393d-1334-4ef3-b2de-ddde172e80b7.png)

**Comment by aparna-ravindra** [comment]
👋🏽 It is still good to check your cache usage using the links I shared above. 
The email you received might not be related. You can check your Actions and Packages usage report by following the doc [here](https://docs.github.com/en/billing/managing-billing-for-github-actions/viewing-your-github-actions-usage).

I hope your question about deleting caches was answered. Closing the issue. Please reopen it in case you have follow up questions regarding caches.
