### ISSUE TITLE
DX: improve "Cache hit occurred on the primary key 8.0.22-phpstan-result, not saving cache."

### ISSUE THREAD

**Issue by clxmstaab** [actions/cache#921]
I am using this action and after some debugging found out that I got trapped into a "caches are immutable" problem and I need to apply the [Update a Cache](https://github.com/actions/cache/blob/main/workarounds.md#update-a-cache) workaround.
I also found out, that this is a problem a lot of people have / run into, as the issue tracker suggests.

In case you know a cache is immutable and will not be updated, its pretty obvious how a fix looks like.

but if you don't know caches are immutable debugging the reason and finally finding the workaround costs a lot of time.

I think if 

> "Cache hit occurred on the primary key 8.0.22-phpstan-result, not saving cache."

would e.g. read like

> "Cache hit occurred on the primary key 8.0.22-phpstan-result, not saving cache."
> "Note: Caches are immutable. See https://github.com/actions/cache/blob/main/workarounds.md#update-a-cache

the fix and the actual problem would be pretty obvious and less time lost.

**Comment by kotewar** [comment]
Hi @clxmstaab, thanks for your feedback. So if I understood it right, your suggestion is to add a note regarding cache immutability in the `actions/cache` logs right?

**Comment by clxmstaab** [comment]
thx for getting back to me.

> regarding cache immutability in the `actions/cache` logs right?

exactly
