### ISSUE TITLE
add section for GitHub extension for cache

### ISSUE THREAD

**Issue by developer-guy** [actions/cache#927]
Recently, I was looking for an easy-to-use tool for viewing the cache usage for one of my workflows, then I noticed this[^1] GitHub extension and it helps me a lot, so, I thought that we might add a section to bring people's attention to this tool.

[^1]: https://github.com/actions/gh-actions-cache

**Comment by pallavx** [comment]
Hi @developer-guy - We have this section in our official [docs](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#managing-caches). I don't suggest adding to the README.
