### ISSUE TITLE
cross-job cache misses

### ISSUE THREAD

**Issue by tbonfort** [actions/cache#943]
I have an action setup where a first job creates a cache directory, which is then used by a second jobs which "needs" the first one.

The issue here is that the second job is not picking up the cache that has been created by the first one.

workflow run:
https://github.com/airbusgeo/godal/actions/runs/3173227767

relevant logs:
In first job:
```
Run actions/cache@v3
  with:
    path: /optgdal
    key: Linux-install-gdal-release/3.4-aae37644121b0e61978a51cb0d4481abe5363bfcd90970a442fab97c6ccf3ba2
Cache not found for input keys: Linux-install-gdal-release/3.4-aae37644121b0e61978a51cb0d4481abe5363bfcd90970a442fab97c6ccf3ba2


#create the cache artifact

Post job cleanup.
/usr/bin/tar --posix -z -cf cache.tgz --exclude cache.tgz -P -C /home/runner/work/godal/godal --files-from manifest.txt
Cache Size: ~28 MB (29473340 B)
Cache saved successfully
Cache saved with key: Linux-install-gdal-release/3.4-aae37644121b0e61978a51cb0d4481abe5363bfcd90970a442fab97c6ccf3ba2
```

In second job (ran after first one):
```
Run actions/cache@v3
  with:
    path: /optgdal
    key: Linux-install-gdal-release/3.4-aae37644121b0e61978a51cb0d4481abe5363bfcd90970a442fab97c6ccf3ba2
  env:
    GODEBUG: cgocheck=2
Cache not found for input keys: Linux-install-gdal-release/3.4-aae37644121b0e61978a51cb0d4481abe5363bfcd90970a442fab97c6ccf3ba2

#create the cache artifact , this should not be needed

Post job cleanup.
/usr/bin/tar --posix -z -cf cache.tgz --exclude cache.tgz -P -C /home/runner/work/godal/godal --files-from manifest.txt
Failed to save: Unable to reserve cache with key Linux-install-gdal-release/3.4-aae37644121b0e61978a51cb0d4481abe5363bfcd90970a442fab97c6ccf3ba2, another job may be creating this cache. More details: Cache already exists. Scope: refs/heads/main, Key: Linux-install-gdal-release/3.4-aae37644121b0e61978a51cb0d4481abe5363bfcd90970a442fab97c6ccf3ba2, Version: 319ddfe8294d1fea971696ed640f65dff510001254b261687c4d7498b02d8573
```

**Comment by tbonfort** [comment]
This action setup was working correctly beforehand, and stopped working sometime between september 13th and september 27th

**Comment by aparna-ravindra** [comment]
Hello 👋🏽 
actions/cache action is designed to suppress any failures during cache restore. It considers all failures as cache misses. Since the post cache step says that the key already exists, my assumption is that there is a failure in the `cache gdal lib` step that is currently hidden. 

Could you please enable the debug logs using steps [here](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging) or rerunning a job by enabling debug logs (the popup that appears on clicking "rerun job" has a checkbox to enable debug logs)? It will help us further identify the cause.

**Comment by tbonfort** [comment]
Hi @aparna-ravindra , thansk for your time. Here is a new run with debug logs enabled: https://github.com/airbusgeo/godal/actions/runs/3173549505 .
The cache misses in the first job are expected as I forced a cache invalidation to produce clean logs (e.g. in [install-gdal (release/3.5)](https://github.com/airbusgeo/godal/actions/runs/3173549505/jobs/5169291199#logs). However the cache miss in the second job should not be happening (e.g. [Go 1.18 + GDAL release/3.5 test](https://github.com/airbusgeo/godal/actions/runs/3173549505/jobs/5169395130#logs)

**Comment by tbonfort** [comment]
From my bug hunting the artifact version may vary depending on the platform/compression, and the logs do seem to indicate something wrong with zstd:

while checking for the cache's availability, zstd seems to be available (https://github.com/airbusgeo/godal/actions/runs/3173549505/jobs/5169291199#step:4:70) , however when saving the artifact in the case of a cache miss, zstd seems to not be available (https://github.com/airbusgeo/godal/actions/runs/3173549505/jobs/5169291199#step:9:61)

**Comment by aparna-ravindra** [comment]
Yes. I also found the same. Because of this, the cache version while restoring cache v/s saving cache is different. Is there anything in your workflow that alters the zstd package?

**Comment by tbonfort** [comment]
ok found the issue, I was deleting /usr/local/bin as a leftover step in my build script, which is probably where zstd was installed on your runners. Something must have changed on the runners this september concerning the check for zstd and/or the location where it's installed, as the issue was not present beforehand. Thnaks for your help @aparna-ravindra
