### ISSUE TITLE
cache download is significantly slower on Mac agents than Linux agents

### ISSUE THREAD

**Issue by farzonl** [actions/cache#944]
On Linux Im seeing cache download speeds between 59-92mb/s. Cache takes 1 min to download
![image](https://user-images.githubusercontent.com/1802579/193631148-43b92720-55c0-4af8-acb3-7838f533a56d.png)

on Mac agents the cache download speeds are 1.2mb/s and i'm only 68% of the way through the job after 29 minutes.
![image](https://user-images.githubusercontent.com/1802579/193631931-d3a24eff-c9d4-4c73-b022-f95b8b56f4a5.png)

**Comment by Velocity-** [comment]
Same here, it makes the cache quite literally useless because that's the point of it. 😓

**Comment by penchef** [comment]
I've posted a detailed how to reproduce here https://github.com/actions/cache/issues/631#issuecomment-1333021422

**Comment by kotewar** [comment]
@farzonl, this download issue is actually related to Azure SDK, and not macOs Runner. We are tracking it [here](https://github.com/actions/cache/issues/810).

**Comment by kotewar** [comment]
@penchef, slow downloads is something I'd agree could be related to macOS runners. I believe there are some issues already open talking about the slowness of macOs runners - https://github.com/actions/runner-images/issues/6547 , https://github.com/actions/runner-images/issues/1336

**Comment by kotewar** [comment]
Please reopen a new issue in that case @sidekick-eimantas
