### ISSUE TITLE
`save-state` and `set-output` are deprecated

### ISSUE THREAD

**Issue by zacharyburnett** [actions/cache#953]
Running this action results in the following warnings:
```
Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
https://github.com/spacetelescope/stenv/actions/runs/3234699238/jobs/5298298424#step:14:20

```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
https://github.com/spacetelescope/stenv/actions/runs/3234699238/jobs/5298298424#step:14:22

**Comment by jelmerk** [comment]
Same

**Comment by rjkerrison** [comment]
I believe this will be fixed once all code is using version 1.10.0 of `@actions/core`. [Bumping to version 1.10.0 of @actions/core](https://github.com/actions/cache/commit/b9c8bfe4426d1b96548309ee742254ebf1a4f21c#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R27) is in `main` but not yet in a release version. Unfortunately `@actions/cache` has its own dependency on `@actions/core`, which is [currently at version 1.2.6](https://github.com/actions/toolkit/blob/1bc93f3cdf638ff423193f992119be08b7bb0666/packages/cache/package.json#L40).

**Comment by fingolfin** [comment]
Actually this repo also uses `set-output`, and recommends it in the README and an example:

<img width="567" alt="Screenshot 2022-10-12 at 22 13 04" src="https://user-images.githubusercontent.com/241512/195438584-905f5a49-b085-48b1-a89b-56539c798736.png">

**Comment by oliversalzburg** [comment]
There are also several `set-output` usages on https://github.com/actions/cache/blob/main/examples.md
