### ISSUE TITLE
Add configurable timeout to cache upload

### ISSUE THREAD

**Issue by edoardopirovano** [actions/cache#958]
Over in the CodeQL team, we've recently started using the Actions cache (via [the toolkit](https://github.com/actions/toolkit)) in a scenario where we care only fairly minimally about the upload/download succeeding (it's entirely optional) but we _really_ care about returning quickly. In the cache downloading options, we found the `segmentTimeoutInMs` field ([here](https://github.com/actions/toolkit/blob/ffb7e3e14ed5e28ae00e9c49ba02b2764d57a6b7/packages/cache/src/options.ts#L50-L55)) which serves our use case well since we can set this to a small number to make sure we return quickly (our caches are small so they always fit in one segment).

However, there is no such option in the [uploading options](https://github.com/actions/toolkit/blob/ffb7e3e14ed5e28ae00e9c49ba02b2764d57a6b7/packages/cache/src/options.ts#L3-L19). Is there any chance you would be able to support this? We've considered some hacky workarounds like spawning a new process to do the upload, but it would really be much more robust if we could configure a timeout there in the same way we can do for the download.

**Comment by edoardopirovano** [comment]
Greetings @bishal-pdMSFT and @kotewar! Just wanted to check in whether this is something you'll be able to prioritise or whether we should invest more time in a workaround?

**Comment by kotewar** [comment]
Hi @edoardopirovano,

Right now we have some other areas in `actions/cache` that we are focusing on which have been asked by multiple folks in the existing open issues. So we might take some time to come back on this. That being said, if you are looking for any workaround, I can help you in creating one and testing it out if you have the bandwidth.

**Comment by kotewar** [comment]
Closing this issue as the CodeQL team went with a custom implementation of the same.

**Comment by edoardopirovano** [comment]
We would still prefer if there was a native way to get the library to timeout, as our workaround isn't particularly robust and requires extra maintenance on our end. We're in no rush to have this, but I would still like to leave this issue open to track this.

**Comment by bishal-pdMSFT** [comment]
@edoardopirovano just curious if you have observed hung upload on multiple occasions. We have not heard about upload being stuck feom other corners.

**Comment by edoardopirovano** [comment]
We have certainly seen downloads hang without the `segmentTimeoutInMs` option specified (e.g. [here](https://github.com/github/codeql-action/actions/runs/3152962897/jobs/5128863320#step:4:163)). Even _with_ that option specified, in fact, we sometimes get hangs before the actual download starts (e.g. [here](https://github.com/zooniverse/panoptes/actions/runs/3420941934/jobs/5696413442#step:3:259) we observed a 15 minute 
hang before the download started, presumably on the API call that looks for where to get the cache from).

We have not actually observed uploads failing nor hanging, but would still like to defend against this possibility so that a potential future outage in your service doesn't cause a knock-on one for us.

**Comment by rasharab** [comment]
We have noticed uploads hanging many times in our projects (for cache uploads of 2gb+).
We're considering moving to a custom s3 implementation as this is untenable for our team. :(
