### ISSUE TITLE
tar run fails on windows

### ISSUE THREAD

**Issue by jakoch** [actions/cache#972]
un-taring the cache.tgz fails with "Can't create" folder.
using actions/cache@v3.0.11

```
Run actions/cache@v3.0.[11](https://github.com/hikogui/hikogui/actions/runs/3360930212/jobs/5570704831#step:6:12)
Received [13](https://github.com/hikogui/hikogui/actions/runs/3360930212/jobs/5570704831#step:6:14)8813725 of 138813725 (100.0%), 1[14](https://github.com/hikogui/hikogui/actions/runs/3360930212/jobs/5570704831#step:6:15).3 MBs/sec
Cache Size: ~132 MB (138813725 B)
C:\Windows\System32\tar.exe -z -xf D:/a/_temp/08bcf992-1dfd-42e9-9848-4de6d36386c5/cache.tgz -P -C D:/a/hikogui/hikogui
C:/VulkanSDK/1.3.231.1/: Can't create '\\\\?\\C:\\VulkanSDK\\1.3.231.1'
C:/VulkanSDK/1.3.231.1/Bin/: Can't create '\\\\?\\C:\\VulkanSDK\\1.3.231.1\\Bin'
C:/VulkanSDK/1.3.231.1/Config/: Can't create '\\\\?\\C:\\VulkanSDK\\1.3.231.1\\Config'
C:/VulkanSDK/1.3.231.1/Include/: Can't create '\\\\?\\C:\\VulkanSDK\\1.3.231.1\\Include'
C:/VulkanSDK/1.3.231.1/Lib/: Can't create '\\\\?\\C:\\VulkanSDK\\1.3.231.1\\Lib'
C:/VulkanSDK/1.3.231.1/README.txt: Can't create '\\\\?\\C:\\VulkanSDK\\1.3.231.1\\README.txt'
C:/VulkanSDK/1.3.231.1/runtime/: Can't create '\\\\?\\C:\\VulkanSDK\\1.3.231.1\\runtime'
C:/VulkanSDK/1.3.231.1/share/: Can't create '\\\\?\\C:\\VulkanSDK\\1.3.231.1\\share'
C:/VulkanSDK/1.3.231.1/share/vulkan/: Can't create '\\\\?
```

**Comment by kotewar** [comment]
Hi @jakoch,

Few questions:
1. Is this a new workflow or is it something that had been running successfully with old version of `actions/cache`?
2. If it is an old workflow, what version `actions/cache` were you using previously?

**Comment by jakoch** [comment]
Hi kotewar,
this is an old workflow. it was running successfully before. 
we used `action/cache@v1` before and updated to `v3.0.11`.
we also updated the cache `key`, when updating the version number to `v3`: [see change diff](https://github.com/hikogui/hikogui/commit/2f2cf58960f678feb0680a5f5742d34e81d1ff50#diff-9978b2faa67a1e8d058ea4b5d2553788ef9fe54f2eba9ce72a0117910484af99L74)

**Comment by Phantsure** [comment]
@jakoch Can you try the same workflow with latest `v3`?

**Comment by jakoch** [comment]
test with `v3` and issue is resolved, 
see https://github.com/jakoch/hikogui/actions/runs/3874064901/jobs/6604814406#step:6:74
thank you!
