### ISSUE TITLE
Allow caches to be removed via a Workflow

### ISSUE THREAD

**Issue by ovflowd** [actions/cache#973]
One thing I really feel is missing on this `action` is to allow to cleanup of cache keys. For example, when I close a PR, I want all the caches from that `ref` to get removed.

Right now either I need to make cURL requests or the new UI feature to delete one per one. On repositories that have a massive amount of runs (such as https://github.com/nodejs/nodejs.dev), this becomes a little bit unmaintainable...

**Comment by w-bonelli** [comment]
[An alternative](https://gist.github.com/w-bonelli/f84a18e985eb43175a7c0eecdb442d3f) to manual HTTP requests is [the `gh-actions-cache` extension](https://github.com/actions/gh-actions-cache) for the `gh` CLI, e.g. from `bash`

```shell
gh extension install actions/gh-actions-cache
gh actions-cache list | tail -n +5 | cut -f1 | xargs -I@ gh actions-cache delete @ --confirm
```

**Comment by pallavx** [comment]
Thanks @w-bonelli for suggesting the `gh` CLI approach.

Hi @ovflowd, we have added some guidance in our [tips-and-workarounds](https://github.com/actions/cache/blob/main/tips-and-workarounds.md#force-deletion-of-caches-overriding-default-cache-eviction-policy) docs. It provides a sample workflow that you can introduce to remove caches for PRs. It uses the same `gh` CLI and the logic is similar to the one mentioned by @w-bonelli.

You can use this workflow as an alternate to making `cURL` requests or using the `gh` CLI directly.
