### ISSUE TITLE
Any idea to implement to cache policy ?

### ISSUE THREAD

**Issue by asvny** [actions/cache#974]
It makes sense in few cases to have cache policy and skip post save steps in certain jobs. For example, I can have a `Deps install` step which will install all the deps and save to the cache, then all other jobs would like to just pull the deps and not save again. 

Similar ideas - https://docs.gitlab.com/ee/ci/yaml/index.html#cachepolicy

**Comment by kotewar** [comment]
Hi @asvny ,
 
We have received this question/ similar recommendation(s) in multiple issues- 

- https://github.com/actions/cache/pull/571
- https://github.com/actions/cache/pull/489
- https://github.com/actions/cache/pull/474
- https://github.com/actions/cache/issues/795
- https://github.com/actions/cache/issues/334
- https://github.com/actions/cache/issues/350
- https://github.com/actions/cache/issues/457

We are working on making this experience better for everyone and will get back soon. :)

**Comment by tanuj077** [comment]
Closing as duplicate.
