### ISSUE TITLE
[Request] Add ability to run tar extract in silent mode

### ISSUE THREAD

**Issue by apearce-nov** [actions/cache#985]
The `tar` command currently used to download cached files does so with the list operation `-t`. When caching node_modules of large projects (especially for monorepos), this can lead to ridiculously large logs, like the one below that created a +40 MB log file just printing every node_module file for the +500 MB cached tar.

(Workflow GUI)
<img width="666" alt="Screen Shot 2022-11-15 at 12 10 00 PM" src="https://user-images.githubusercontent.com/74783074/201994550-46e1bf91-b351-4b24-988c-9ba6b1b775b4.png">

(Downloaded log files)
<img width="499" alt="Screen Shot 2022-11-15 at 12 20 20 PM" src="https://user-images.githubusercontent.com/74783074/201996286-62d4fd1f-faa3-472a-a044-dd62bc06029e.png">

It would be great if the action had an optional param to extract the tar without listing the files.

**Comment by Phantsure** [comment]
Listing is only done with debug step enabled. Please disable or remove that step to don't print this

**Comment by Phantsure** [comment]
@apearce-nov Does this resolve your issue?

**Comment by apearce-nov** [comment]
Where would I be setting this debug value?

 - name: Restore cached node modules
      id: cache_node_modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ inputs.CACHE_KEY_NODE_MODULES }}

**Comment by Phantsure** [comment]
@apearce-nov This doc explains well: 
https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging
There should be secret which would be set

**Comment by Phantsure** [comment]
@apearce-nov Closing this issue as it seems to be addressed. Thank you. Please re-open if need more clarification
