### ISSUE TITLE
Scope of cache being stored

### ISSUE THREAD

**Issue by YashMathur** [actions/cache#99]
If a PR restores cache that was scoped to master and saves it at the end of the action, does the scope of the cache change to that of the PR's or does it remain in master's scope?

For example - 
Let's say I have folder `tempFolder` cached on the master branch. 
I create a PR that restores cache from master and downloads `tempFolder`. The action then makes some changes `tempFolder`, and at the end, the cache is saved. 

Does the scope of `tempFolder` change from master to that of the PR?

**Comment by dhadka** [comment]
It would create a new cache in the scope of the PR.  This would result in a cache in `master` with the old `tempFolder` and a cache in the PR with the modified `tempFolder`.

**Comment by dhadka** [comment]
Closing this issue.  Please feel free to re-open if you have any further questions.
